### ISSUE TITLE
请问如何实现局部楷体

### ISSUE THREAD

**Issue by dnsilence** [x-magus/ThesisUESTC#100]
使用了\CJKfontspec{simkai}提示没找到楷体，求助如何局部临时使用楷体

**Comment by stone-zeng** [comment]
Windows 上面的楷体文件名是 `simkai.ttf`，字体名是 `KaiTi`，所以试一下 `\CJKfontspec{simkai.ttf}` 或者 `\CJKfontspec{KaiTi}`。
