### ISSUE TITLE
可以修改缩略语为3列

### ISSUE THREAD

**Issue by murphyliu81** [x-magus/ThesisUESTC#101]
把缩略词表改成3列，给其他有同样需求的同学做参考。
替换cls文件里面原有的\newglossarystyle{long-uestc}：
\newglossarystyle{long-uestc}{
  \renewenvironment{theglossary}%
    {\begin{longtable}{lp{\glsdescwidth}p{\glspagelistwidth}}}%
    {\end{longtable}}%
	\setlength{\glsdescwidth}{75mm}
	\setlength{\glspagelistwidth}{10em}
  \renewcommand*{\glossaryheader}{}%
  \renewcommand*{\glsgroupheading}[1]{}%
  \renewcommand{\glossentry}[2]{
   \glsentryitem{##1}\glstarget{##1}{\glossentryname{##1}} &
   \glsentrylong{##1} & \glsentrydesc{##1}\tabularnewline
  }
  \renewcommand*{\subglossentry}[3]{
  \glossentry{##2}{##3}}
}

**Comment by yanghaoxie** [comment]
给缩略词表的每一列加上标题，即`缩略词，英文全称和中文全称`，基于@murphyliu81和https://github.com/shifujun/UESTCthesis的相关代码编写。
```
\newcommand{\acronymheader@uestcthesis}{缩略词}
\newcommand{\acronymfull@uestcthesis}{英文全称}
\newcommand{\acronymtranslation@uestcthesis}{中文全称}
\newglossarystyle{long-uestc}{
  \renewenvironment{theglossary}%
  % {\begin{longtable}{lp{\glsdescwidth}p{\glspagelistwidth}}}%
  {\begin{longtable}{lp{\glsdescwidth}p{\glspagelistwidth}}}%
    {\end{longtable}}%
  % \setlength{\glsdescwidth}{65mm}
  % \setlength{\glspagelistwidth}{15em}
  \setlength{\glsdescwidth}{.45\textwidth}
  \setlength{\glspagelistwidth}{.25\textwidth}
  % \renewcommand*{\glossaryheader}{}%
  \renewcommand*{\glossaryheader}{%
    \heiti\acronymheader@uestcthesis&\heiti\acronymfull@uestcthesis&
    \heiti\acronymtranslation@uestcthesis\tabularnewline\endhead}%
  \renewcommand*{\glsgroupheading}[1]{}%
  \renewcommand{\glossentry}[2]{
    \glsentryitem{##1}\glstarget{##1}{\glossentryname{##1}} &
    \glsentrylong{##1} & \glsentrydesc{##1}\tabularnewline
  }
  \renewcommand*{\subglossentry}[3]{
    \glossentry{##2}{##3}}
}

```
