### ISSUE TITLE
如何引用arxiv的文献呢

### ISSUE THREAD

**Issue by perryupan** [x-magus/ThesisUESTC#102]
你好，
提问如标题。不得已需要引用arxiv，但是编译通不过，不知道该怎么办

**Comment by x-magus** [comment]
可以按照电子出版物的类型饮用，比如：
```
@digital{clerc2010discrete,
  author = {M. Clerc},
  title = {Discrete particle swarm optimization: a fuzzy combinatorial box},
  type = {EB/OL},
  date = {July 16, 2010},
  url = {http://clere.maurice.free.fr/pso/Fuzzy_Discrere_PSO/Fuzzy_DPSO.htm}
}
```

**Comment by perryupan** [comment]
> 可以按照电子出版物的类型引用，比如：
> 
> ```
> @digital{clerc2010discrete,
>   author = {M. Clerc},
>   title = {Discrete particle swarm optimization: a fuzzy combinatorial box},
>   type = {EB/OL},
>   date = {July 16, 2010},
>   url = {http://clere.maurice.free.fr/pso/Fuzzy_Discrere_PSO/Fuzzy_DPSO.htm}
> }
> ```

谢谢了哈

**Comment by blackwatchcup** [comment]
请文一下如何可以使文献引用在正文中是上角标？

**Comment by muzimuzhi** [comment]
> 请文一下如何可以使文献引用在正文中是上角标？

新问题，请创建新 issue 提问。

**Comment by dnsilence** [comment]
> 请文一下如何可以使文献引用在正文中是上角标？

\citing{}

**Comment by chenjl12** [comment]
author = {{Ge}, Zheng and {Liu}, Songtao and {Wang}, Feng and {Li}, Zeming and {Sun}, Jian},
        title = "{YOLOX: Exceeding YOLO Series in 2021}",
      journal = {arXiv e-prints},
     keywords = {Computer Science - Computer Vision and Pattern Recognition},
         year = 2021,
        month = jul,
          eid = {arXiv:2107.08430},
        pages = {arXiv:2107.08430},
archivePrefix = {arXiv},
       eprint = {2107.08430},
 primaryClass = {cs.CV},
       adsurl = {https://ui.adsabs.harvard.edu/abs/2021arXiv210708430G},
      adsnote = {Provided by the SAO/NASA Astrophysics Data System}
}

**Comment by sikouhjw** [comment]
> author = {{Ge}, Zheng and {Liu}, Songtao and {Wang}, Feng and {Li}, Zeming and {Sun}, Jian}, title = "{YOLOX: Exceeding YOLO Series in 2021}", journal = {arXiv e-prints}, keywords = {Computer Science - Computer Vision and Pattern Recognition}, year = 2021, month = jul, eid = {arXiv:2107.08430}, pages = {arXiv:2107.08430}, archivePrefix = {arXiv}, eprint = {2107.08430}, primaryClass = {cs.CV}, adsurl = {[https://ui.adsabs.harvard.edu/abs/2021arXiv210708430G}](https://ui.adsabs.harvard.edu/abs/2021arXiv210708430G%7D), adsnote = {Provided by the SAO/NASA Astrophysics Data System} }

你发这个是为了什么呢？
