### ISSUE TITLE
在生成图目录后，如何将子图的子标题单独列出来。

### ISSUE THREAD

**Issue by lamesoeur** [x-magus/ThesisUESTC#103]
需要生成的目录样式
![fig2](https://user-images.githubusercontent.com/33130499/76700519-4f323d00-66f3-11ea-973c-49d939857422.png)

实际生成的目录：
![fig1](https://user-images.githubusercontent.com/33130499/76700523-59543b80-66f3-11ea-8766-8385065e486c.png)

使用的代码：
![fig3](https://user-images.githubusercontent.com/33130499/76700527-62dda380-66f3-11ea-9e86-b3d5074ea5e6.png)

学院论文写作要求子图在原文中不允许有子标题，统一在主标题中说明。请问如何解决？

**Comment by x-magus** [comment]
这种样式在latex中实现恐怕是非常困难的。

**Comment by muzimuzhi** [comment]
凑合用。`subfig` 十几年无人维护，我不够熟悉它，可能有更简单的做法。强烈建议用 `subcaption` 宏包替换 `subfig`。

```tex
\documentclass[master]{thesis-uestc}

\setlength{\cftfignumwidth}{40pt}

\newcommand\subfigureCaption[1]{%
  \addtocounter{figure}{1}%
  \addcontentsline{lof}{figure}
    {\protect\numberline{\thefigure\thesubfigure}{#1}}%
  \addtocounter{figure}{-1}%
}

\begin{document}

%\thesistableofcontents
\thesisfigurelist
\thesischapterexordium

\section{研究工作的背景与意义}

\begin{figure}[h]
  \centering
  
  \subfloat[子图题注][]{\includegraphics[width=8em]{example-image}}%
  \subfigureCaption{子图题注，仅出现在图目录}
  \qquad
  \subfloat[]{\includegraphics[width=8em]{example-image}}%
  \subfigureCaption{子图题注，仅出现在图目录}
  
  \captionsetup{list=no}
  \caption{浮动体整体的题注，不产生图目录项}
\end{figure}
\end{document}
```

图目录
![image](https://user-images.githubusercontent.com/6376638/76722563-13dd5000-677f-11ea-8137-87a1f4621a5e.png)
正文
![image](https://user-images.githubusercontent.com/6376638/76722566-1a6bc780-677f-11ea-86c9-f9c1a23d43a5.png)

PS：提问时，提供文本形式的代码，提供别人复制后就能编译的完整例子，不要截图、不要给代码片段。

**Comment by x-magus** [comment]
我们学校同时还要求子图题显示在总图题后面，以上面的例子图题输出应该是：
```
图1-1 浮动体整体的题注，不产生图目录项。(a)子图题注，仅出现在图目录； (b)子图题注，仅出现在图目录。
```
同时整体悬挂缩进。再考虑字体图的目录，实现起来估计是很困难的。

**Comment by lamesoeur** [comment]
> 凑合用。`subfig` 十几年无人维护，我不够熟悉它，可能有更简单的做法。强烈建议用 `subcaption` 宏包替换 `subfig`。
> 
> ```
> \documentclass[master]{thesis-uestc}
> 
> \setlength{\cftfignumwidth}{40pt}
> 
> \newcommand\subfigureCaption[1]{%
>   \addtocounter{figure}{1}%
>   \addcontentsline{lof}{figure}
>     {\protect\numberline{\thefigure\thesubfigure}{#1}}%
>   \addtocounter{figure}{-1}%
> }
> 
> \begin{document}
> 
> %\thesistableofcontents
> \thesisfigurelist
> \thesischapterexordium
> 
> \section{研究工作的背景与意义}
> 
> \begin{figure}[h]
>   \centering
>   
>   \subfloat[]{\includegraphics[width=8em]{example-image}}%
>   \subfigureCaption{子图题注，仅出现在图目录}%
>   \qquad
>   \subfloat[]{\includegraphics[width=8em]{example-image}}%
>   \subfigureCaption{子图题注，仅出现在图目录}
>   
>   \captionsetup{list=no}
>   \caption{浮动体整体的题注，不产生图目录项}
> \end{figure}
> \end{document}
> ```
> 
> 图目录
> ![image](https://user-images.githubusercontent.com/6376638/76722563-13dd5000-677f-11ea-8137-87a1f4621a5e.png)
> 正文
> ![image](https://user-images.githubusercontent.com/6376638/76722566-1a6bc780-677f-11ea-86c9-f9c1a23d43a5.png)
> 
> PS：提问时，提供文本形式的代码，提供别人复制后就能编译的完整例子，不要截图、不要给代码片段。
谢谢！

**Comment by muzimuzhi** [comment]
> 我们学校同时还要求子图题显示在总图题后面，以上面的例子图题输出应该是：
> 
> ```
> 图1-1 浮动体整体的题注，不产生图目录项。(a)子图题注，仅出现在图目录； (b)子图题注，仅出现在图目录。
> ```
> 
> 同时整体悬挂缩进。再考虑子体图的目录，实现起来估计是很困难的。硬要追求这种效果的话需要不同命令重复填写内容。

@lamesoeur 你完整的需求是怎样的？和上面的要求哪里相同、哪里不同？
@x-magus 只是提供一个 workaround，因为我感觉题主的需求是「非普遍、可以接受一定手动输入的」

**Comment by lamesoeur** [comment]
> > 我们学校同时还要求子图题显示在总图题后面，以上面的例子图题输出应该是：
> > ```
> > 图1-1 浮动体整体的题注，不产生图目录项。(a)子图题注，仅出现在图目录； (b)子图题注，仅出现在图目录。
> > ```
> > 
> > 
> > 同时整体悬挂缩进。再考虑子体图的目录，实现起来估计是很困难的。硬要追求这种效果的话需要不同命令重复填写内容。
> 
> @lamesoeur 你完整的需求是怎样的

**Comment by lamesoeur** [comment]
子图在正文中不能带标题，有编号a,b,c ...即可；
子图标题在总图后面添加，和你生成的图片效果一致；
子图在图目录中要单独的列出来每个子图及其对应的标题，如“图2-1 (a) 子图标题内容”；

@muzimuzhi

**Comment by muzimuzhi** [comment]
> 子图在正文中不能带标题，有编号a,b,c ...即可；
> 子图标题在总图后面添加，和你生成的图片效果一致；
> 子图在图目录中要单独的列出来每个子图及其对应的标题，如“图2-1 (a) 子图标题内容”；
> 
> @muzimuzhi

所以 https://github.com/x-magus/ThesisUESTC/issues/103#issuecomment-599336680 提供的临时方案能满足你的需求，是这样吗？
