### ISSUE TITLE
关于图、表、公式与正文之间的行间距的问题

### ISSUE THREAD

**Issue by sikouhjw** [x-magus/ThesisUESTC#104]
参考[如何满足subfigure图过多需要跨页排版需求？](https://github.com/x-magus/ThesisUESTC/issues/91)，反映出模板并未设置段前段后，读了下源码，结合论文格式要求
> （5）图、表、公式与正文之间对行间距要求如下：
>    ①图：图题的段前为6磅，段后为12磅；
>    ②表：表题的段前为12磅，段后为6磅；
>    ③公式：公式的段前段后为6磅。

https://github.com/x-magus/ThesisUESTC/blob/70b2ffa11673ba1ca31fdd86e4275b14908f4462/thesis-uestc.cls#L1078-L1083
发现这里不对，是 `6pt`，至于
>    ①图：图题的段前为6磅，段后为12磅；
>    ②表：表题的段前为12磅，段后为6磅；

不知道怎么区分 `table` 和 `figure` 这两个，如果统一设置就是 `\floatsep`、`\textfloatsep`、`\intextsep`

**Comment by muzimuzhi** [comment]
你引用的源码段不对。`\[above|below]display(short)skip` 控制的是行间公式前后的纵向间距，参考 `texdoc texbytopic`, chap. 24.

控制浮动体题注前后间距的是 `\[above|below]captionskip`。在加载 `caption` 宏包后，可以为每一浮动体类型单独设置题注前后的间距。对应的源码是
https://github.com/x-magus/ThesisUESTC/blob/70b2ffa11673ba1ca31fdd86e4275b14908f4462/thesis-uestc.cls#L150-L151

**Comment by sikouhjw** [comment]
> 你引用的源码段不对。`\[above|below]display(short)skip` 控制的是行间公式前后的纵向间距，参考 `texdoc texbytopic`, chap. 24.

我写的顺序有点乱，引用的部分是为了说明设置行间公式的纵向间距设置错了，后面才是图表题注前后的纵向间距

> 控制浮动体题注前后间距的是 `\[above|below]captionskip`。在加载 `caption` 宏包后，可以为每一浮动体类型单独设置题注前后的间距。对应的源码是
> 
> https://github.com/x-magus/ThesisUESTC/blob/70b2ffa11673ba1ca31fdd86e4275b14908f4462/thesis-uestc.cls#L150-L151

这部分是我看漏了，没有全面的去读源码，也误解了
> ①图：图题的段前为6磅，段后为12磅；
> ②表：表题的段前为12磅，段后为6磅；

这句话的意思，但模板中的设置似乎与规范又对不上
那么[如何满足subfigure图过多需要跨页排版需求？](https://github.com/x-magus/ThesisUESTC/issues/91)中反映的问题，究竟是需要修改
https://github.com/x-magus/ThesisUESTC/blob/70b2ffa11673ba1ca31fdd86e4275b14908f4462/thesis-uestc.cls#L150-L151
还是 `\floatsep` 等参数呢？

**Comment by muzimuzhi** [comment]
如果进行扣字眼地理解，你引用的论文要求
  - 对行间公式，只要求了「段前段后间距」。而大部分时候行间公式是不独占一段的。在下面的例子中，text a、行间公式和 text b 处于同一段落，这样再怎么要求段前段后间距也不影响这类行间公式的前后间距。
    ```tex
    text a
    \[ ... \]
    text b
    ```
 - 对图表，只要求了「题注段前段后的间距」，对应的是 `正文 <间距 1> 图片 <间距 2> 题注 <间距 3> 正文` 中的 `<间距 2>` 和 `<间距 3>`。对 `<间距 1>` 没有提出具体要求。
假设把论文要求理解为 `<间距 1/3> = 12pt, <间距 2> = 6pt`，那么可以设置成浮动体间距 12pt，`\usepackage[strut=false]{caption}` 和 `\captionsetup{skip=6pt}`。要一起改。这样也能满足 #91 的情况。

**Comment by sikouhjw** [comment]
> 对行间公式，只要求了「段前段后间距」。而大部分时候行间公式是不独占一段的。在下面的例子中，text a、行间公式和 text b 处于同一段落，这样再怎么要求段前段后间距也不影响这类行间公式的前后间距。

我理解了你的意思，我怀疑写规范的人认为段前段后间距是指行间公式与前后文字之间的纵向间距，并且模板中也出现了
https://github.com/x-magus/ThesisUESTC/blob/70b2ffa11673ba1ca31fdd86e4275b14908f4462/thesis-uestc.cls#L1078-L1083
所以应该将参数改为`\[above|below]display(short)skip=6pt`
> 对图表，只要求了「题注段前段后的间距」，对应的是 `正文 <间距 1> 图片 <间距 2> 题注 <间距 3> 正文` 中的 `<间距 2>` 和 `<间距 3>`。对 `<间距 1>` 没有提出具体要求。
>       假设把论文要求理解为 `<间距 1/3> = 12pt, <间距 2> = 6pt`，那么可以设置成浮动体间距 12pt，`\usepackage[strut=false]{caption}` 和 `\captionsetup{skip=6pt}`。要一起改。这样也能满足 #91 的情况。

赞同，建议 @x-magus 修改

**Comment by x-magus** [comment]
6pt很难看的，还是不要改了。

**Comment by muzimuzhi** [comment]
PS：学校（或院系）提供的 WORD 模板没有完全遵循对应的样式规范，这种可能也是存在的。不建议过分抠字眼。
