### ISSUE TITLE
为什么需要使用latexmk编译三次才能正常显示引用的参考文献？

### ISSUE THREAD

**Issue by hjnnjh** [x-magus/ThesisUESTC#105]
学长你好，最近在使用你的模板写毕业论文，遇到了如题的问题，有解决的方法吗？

**Comment by sikouhjw** [comment]
结论：
不是 bug，是 latex 的正常行为

为什么？
[关于 LaTeX 入门的一些东西](https://sikouhjw.gitee.io/2020/03/08/2020-03-08-Learn-LaTeX/)，自己看吧，有视频，有 pdf 文档

想说的话：
麻烦补点基础再用 latex，或者不要注意这些细节，没有报错 / 警告，能输出 pdf 就行
