### ISSUE TITLE
反馈一个关于封面可能是bug的小问题

### ISSUE THREAD

**Issue by handsomeleepeifeng** [x-magus/ThesisUESTC#106]
在制作封面时，英文标题题目如果超过了三行，那么英文封面就会变成两页，如果在两行之内则是正确的一页。

**Comment by dnsilence** [comment]
不是bug，英文标题和论文类型之间的间距过宽，修改
https://github.com/x-magus/ThesisUESTC/blob/70b2ffa11673ba1ca31fdd86e4275b14908f4462/thesis-uestc.cls#L707
中的7.3cm为更小的值就可以

**Comment by x-magus** [comment]
应该只有图书馆的模版有这种问题，建议从GitHub上下载模版。
