### ISSUE TITLE
请问，专利应该怎么写bibtex呢

### ISSUE THREAD

**Issue by perryupan** [x-magus/ThesisUESTC#108]

**Comment by x-magus** [comment]
在`reference.bib`中提供的有例子：
```
@patent{xiao2012yi,
  author = {肖珍新},
  title = {一种新型排渣阀调节降温装置},
  date = {2012年4月25日},
  type = {实用新型专利},
  country = {中国},
  id = {ZL201120085830.0}
}
```

**Comment by perryupan** [comment]
> 在`reference.bib`中提供的有例子：
> 
> ```
> @patent{xiao2012yi,
>   author = {肖珍新},
>   title = {一种新型排渣阀调节降温装置},
>   date = {2012年4月25日},
>   type = {实用新型专利},
>   country = {中国},
>   id = {ZL201120085830.0}
> }
> ```

疏忽了，谢谢
