### ISSUE TITLE
参考文献中[R]格式的文献都不会生成年份。

### ISSUE THREAD

**Issue by ghghgh0001** [x-magus/ThesisUESTC#114]
A. Krizhevsky, G. Hinton, et al. Learning multiple layers of features from tiny images[R]. Citeseer,

R. M. Haralick. Texture­tone study with application to digitized imagery.[R]. Kansas
Univ/Center for Research Inc Lawrence Remote Sensing Lab,

例如上面两个，在bib格式的文件里都是写了year的，但是生成出的参考文献中末尾是没有年份的。

**Comment by x-magus** [comment]
[R]类文献是这样填写的：
```
@techreport{feng997he,
  author = {冯西桥},
  title = {核反应堆压力容器的{LBB}分析},
  institution = {清华大学核能技术设计研究院},
  date = {1997年6月25日},
  address = {北京}
}
```

**Comment by ghghgh0001** [comment]
嗯，感谢，我google学术上down下来的日期是year，所以一直都不生成，后来改成data就可以用了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Wang Wen"<notifications@github.com&gt;; 
发送时间: 2020年4月28日(星期二) 晚上7:18
收件人: "x-magus/ThesisUESTC"<ThesisUESTC@noreply.github.com&gt;; 
抄送: "ghghgh"<965326168@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [x-magus/ThesisUESTC] 参考文献中[R]格式的文献都不会生成年份。 (#114)





 
[R]类文献是这样填写的：
@techreport{feng997he,   author = {冯西桥},   title = {核反应堆压力容器的{LBB}分析},   institution = {清华大学核能技术设计研究院},   date = {1997年6月25日},   address = {北京} }
