### ISSUE TITLE
使用\subfloat命令插入子图时遇到的问题

### ISSUE THREAD

**Issue by hjnnjh** [x-magus/ThesisUESTC#117]
使用\subfloat命令插入子图，子图caption在空间足够的情况下换行了，但我不想它换行，请问如何解决这个问题？
![image](https://user-images.githubusercontent.com/37699150/81384088-c4dee600-9143-11ea-8a30-8e7464ba1791.png)
![image](https://user-images.githubusercontent.com/37699150/81384126-cd372100-9143-11ea-8144-1cf939f35844.png)

**Comment by muzimuzhi** [comment]
单个换行符会转换为空格，从而增加内容的宽度，试试用 `%` 注释它们，例如

```tex
\subfloat[...]{%
    \includegraphics[...]{...}%
    \label{...}%
}%
```

**Comment by x-magus** [comment]
可能是`\hfill`命令的问题，为什么要使用这个命令？

**Comment by hjnnjh** [comment]
> 可能是`\hfill`命令的问题，为什么要使用这个命令？

不使用这个命令也会出现这个问题。。。

**Comment by hjnnjh** [comment]
> 单个换行符会转换为空格，从而增加内容的宽度，试试用 `%` 注释它们，例如
> 
> ```
> \subfloat[...]{%
>     \includegraphics[...]{...}%
>     \label{...}%
> }%
> ```

试过了，不行。。。

**Comment by muzimuzhi** [comment]
@hjnnjh 
我本地，注释换行符后是可行的。你具体是怎么写的，用的是模板的哪个版本，能否提供一个完整的例子？

```tex
\documentclass[master]{thesis-uestc}

\begin{document}
\thesistableofcontents
\thesischapterexordium

\section{研究工作的背景与意义}

\begin{figure}[H]
  \centering
  \subfloat[]{%
      \includegraphics[width=.48\textwidth]{example-image}%
      \label{...}%
  }%
  \hfill
  \subfloat[]{%
      \includegraphics[width=.48\textwidth]{example-image}%
      \label{...}%
  }%
  \caption{text}
  \label{key}
\end{figure}
\end{document}
```

![image](https://user-images.githubusercontent.com/6376638/81412225-20c26280-9176-11ea-860f-2c780b6c7714.png)

**Comment by wendili-cs** [comment]
我也遇到了这个问题，我最后在thesis-uestc.cls我文件中

> \captionsetup[subfigure]{font=small, belowskip=6pt, width=36pt}

这一行去掉了width这个，改成"\captionsetup[subfigure]{font=small, belowskip=6pt}"就恢复了。

**Comment by x-magus** [comment]
学校要求子图题写在主图题后面，用分号隔开。你这样写子图题是不符合要求的。

**Comment by x-magus** [comment]
学校的要求是这样的：
<img width="484" alt="Screen Shot 2020-05-09 at 8 47 26 AM" src="https://user-images.githubusercontent.com/3732959/81459282-b808d380-91d1-11ea-8ed4-da334071c8c4.png">

**Comment by hjnnjh** [comment]
> @hjnnjh
> 我本地，注释换行符后是可行的。你具体是怎么写的，用的是模板的哪个版本，能否提供一个完整的例子？
> 
> ```
> \documentclass[master]{thesis-uestc}
> 
> \begin{document}
> \thesistableofcontents
> \thesischapterexordium
> 
> \section{研究工作的背景与意义}
> 
> \begin{figure}[H]
>   \centering
>   \subfloat[]{%
>       \includegraphics[width=.48\textwidth]{example-image}%
>       \label{...}%
>   }%
>   \hfill
>   \subfloat[]{%
>       \includegraphics[width=.48\textwidth]{example-image}%
>       \label{...}%
>   }%
>   \caption{text}
>   \label{key}
> \end{figure}
> \end{document}
> ```
> 
> ![image](https://user-images.githubusercontent.com/6376638/81412225-20c26280-9176-11ea-860f-2c780b6c7714.png)

谢谢大佬，看了后面学长的回复，我按学校的要求写就没这个问题了

**Comment by hjnnjh** [comment]
> 学校的要求是这样的：
> <img alt="Screen Shot 2020-05-09 at 8 47 26 AM" width="484" src="https://user-images.githubusercontent.com/3732959/81459282-b808d380-91d1-11ea-8ed4-da334071c8c4.png">

这样写的话就没这个问题了。
