### ISSUE TITLE
摘要后有空页

### ISSUE THREAD

**Issue by hjnnjh** [x-magus/ThesisUESTC#118]
中、英文摘要后都有空页，请问怎么处理，本科模板
![image](https://user-images.githubusercontent.com/37699150/81404763-d71f4b00-9168-11ea-9625-5fcf9cfcf19e.png)
![image](https://user-images.githubusercontent.com/37699150/81404798-e900ee00-9168-11ea-9e4f-4c89bda44c45.png)

**Comment by x-magus** [comment]
刚更新了模版（commit 8796a5d3d6719351398174afedc3d3cc08d90297），现在应该没有这个问题了。
