### ISSUE TITLE
消除三个 bad box

### ISSUE THREAD

**Issue by sikouhjw** [x-magus/ThesisUESTC#120]
- https://github.com/x-magus/ThesisUESTC/blob/c3117db7775b6fc7e171ad993469ace5747bafc1/thesis-uestc.cls#L280
```tex
  \parbox[t]{\linewidth - 48pt}{#1}
```
- https://github.com/x-magus/ThesisUESTC/blob/c3117db7775b6fc7e171ad993469ace5747bafc1/thesis-uestc.cls#L307
```tex
  \parbox[t]{\linewidth - 2.1cm}{#1}
```
- https://github.com/x-magus/ThesisUESTC/blob/c3117db7775b6fc7e171ad993469ace5747bafc1/thesis-uestc.cls#L628
```tex
\noindent 分类号 \uline{\hspace{2.496in}} 密级 \uline{\hspace{2.496in}} \\[12bp]
```

**Comment by x-magus** [comment]
这个\parbox 不这样的话一页摘要写满会有多余的空页。

**Comment by x-magus** [comment]
再说减去一个更大的值得到的宽度应该更小才对，按道理应该没有bad box。

**Comment by sikouhjw** [comment]
> 再说减去一个更大的值得到的宽度应该更小才对，按道理应该没有bad box。

MWE：
```tex
\documentclass{ctexart}
\usepackage[showframe]{geometry}
\usepackage{calc}
\newcommand{\chinesekeyword}[1]{
  \noindent%
  \parbox[t]{48pt}{\textbf{关键词：}}%
  \parbox[t]{\linewidth - 48.06pt}{#1}
}
\begin{document}
\chinesekeyword{劳仑衣普桑，认至将指点效则机，最你更枝。想极整月正进好志次回总般，段然取向}

\noindent%
\parbox[t]{48pt}{\textbf{关键词：}}%
\parbox[t]{\linewidth - 48.06pt}{劳仑衣普桑，认至将指点效则机，最你更枝。想极整月正进好志次回总般，段然取向}
\end{document}
```
不知道为什么，第一种会有 bad box；

> 这个\parbox 不这样的话一页摘要写满会有多余的空页。

https://github.com/x-magus/ThesisUESTC/blob/c3117db7775b6fc7e171ad993469ace5747bafc1/thesis-uestc.cls#L280
```tex
  \parbox[t]{\linewidth - 48pt}{#1}\xeCJKnobreak
```
https://github.com/x-magus/ThesisUESTC/blob/c3117db7775b6fc7e171ad993469ace5747bafc1/thesis-uestc.cls#L307
```tex
  \parbox[t]{\linewidth - 2.1cm}{#1}\xeCJKnobreak
```
参考《[`tasks` 宏包在处理溢出的时候会多出一行，如何解决？](https://wenda.latexstudio.net/q-1811.html)》

**Comment by x-magus** [comment]
我很仔细地调整了摘要行数才发现多余的空页的。

**Comment by sikouhjw** [comment]
> 我很仔细地调整了摘要行数才发现多余的空页的。

用 `\xeCJKnobreak` 可以抑制，我试了没有问题

**Comment by muzimuzhi** [comment]
> > 再说减去一个更大的值得到的宽度应该更小才对，按道理应该没有bad box。
> 
> MWE：
> 
> ```
> \documentclass{ctexart}
> \usepackage[showframe]{geometry}
> \usepackage{calc}
> \newcommand{\chinesekeyword}[1]{
>   \noindent%
>   \parbox[t]{48pt}{\textbf{关键词：}}%
>   \parbox[t]{\linewidth - 48.06pt}{#1}
> }
> \begin{document}
> \chinesekeyword{劳仑衣普桑，认至将指点效则机，最你更枝。想极整月正进好志次回总般，段然取向}
> 
> \noindent%
> \parbox[t]{48pt}{\textbf{关键词：}}%
> \parbox[t]{\linewidth - 48.06pt}{劳仑衣普桑，认至将指点效则机，最你更枝。想极整月正进好志次回总般，段然取向}
> \end{document}
> ```
> 
> 不知道为什么，第一种会有 bad box；

这里可以适当简化，例如
```tex
\makeatletter
\newcommand{\chinesekeyword}[1]{%
  \@hangfrom{\makebox[48pt][l]{\textbf{关键词：}}}#1\par
}
\makeatother
```

`\@hangfrom` 是 latex2e 的内部宏，能生成悬挂缩进的效果。
