### ISSUE TITLE
页眉不论奇偶页都对应chapter标题，页码编号为阿拉伯数字并且从摘要开始(摘要后面的空页不编号)，请问如何修改cls文件？

### ISSUE THREAD

**Issue by hjnnjh** [x-magus/ThesisUESTC#121]
学长好，毕业论文已顺利完成，但是现在还有一个报告要写，格式要求和毕业论文差不多，有一点小区别，需求如题，请问应该如何修改cls文件？

**Comment by hjnnjh** [comment]
word的格式调的我太难受了。。。

**Comment by sikouhjw** [comment]
> 页眉不论奇偶页都对应chapter标题

https://github.com/x-magus/ThesisUESTC/blob/c3117db7775b6fc7e171ad993469ace5747bafc1/thesis-uestc.cls#L780-L790
```tex
\newcommand{\standardhead}{
  \fancyhf{}
  \ifchinesebook{
    \fancyhead[CE]{\fontsize{10.5pt}{12.6pt}\selectfont\leftmark}
    \fancyhead[CO]{\fontsize{10.5pt}{12.6pt}\selectfont\leftmark}
  }{
    \fancyhead[CE]{\fontsize{10.5pt}{12.6pt}\selectfont\nouppercase\display@englishheader}
    \fancyhead[CO]{\fontsize{10.5pt}{12.6pt}\selectfont\nouppercase\leftmark}
  }
  \fancyfoot[CE,CO]{\fontsize{9pt}{10.8pt}\selectfont\thepage}
}
```

**Comment by hjnnjh** [comment]
> > 页眉不论奇偶页都对应chapter标题
> 
> 
> 
> https://github.com/x-magus/ThesisUESTC/blob/c3117db7775b6fc7e171ad993469ace5747bafc1/thesis-uestc.cls#L780-L790
> 
> ```tex
> 
> \newcommand{\standardhead}{
> 
>   \fancyhf{}
> 
>   \ifchinesebook{
> 
>     \fancyhead[CE]{\fontsize{10.5pt}{12.6pt}\selectfont\leftmark}
> 
>     \fancyhead[CO]{\fontsize{10.5pt}{12.6pt}\selectfont\leftmark}
> 
>   }{
> 
>     \fancyhead[CE]{\fontsize{10.5pt}{12.6pt}\selectfont\nouppercase\display@englishheader}
> 
>     \fancyhead[CO]{\fontsize{10.5pt}{12.6pt}\selectfont\nouppercase\leftmark}
> 
>   }
> 
>   \fancyfoot[CE,CO]{\fontsize{9pt}{10.8pt}\selectfont\thepage}
> 
> }
> 
> ```

谢谢大佬，虽然已经用不到了，报告最后还是用word写了。
