### ISSUE TITLE
学位论文引用格式问题

### ISSUE THREAD

**Issue by Zuohua-Song** [x-magus/ThesisUESTC#122]
![image](https://user-images.githubusercontent.com/34480466/83005131-0972e880-a043-11ea-9765-d8008903fc6d.png)
在参考文献中引用学位论文时，在年份前后会有两个多余的逗号。
学位论文中的信息只有标题、作者、年份和学校，bib信息完整，请问如何处理？

**Comment by x-magus** [comment]
引用学位论文信息要填完整，参考reference.bib给出的例子：
```
@thesis{chen2001hao,
  author = {陈念永},
  title = {毫米波细胞生物效应及抗肿瘤研究},
  institution = {电子科技大学},
  year = {2001},
  pages = {50-60},
  address = {成都}
}
```
缺失的项只能自己想办法搜集了。
