### ISSUE TITLE
攻读学位期间成果中的小标题缩进问题

### ISSUE THREAD

**Issue by WolfgangFred** [x-magus/ThesisUESTC#125]
使用thesistheaccomplish环境生成攻读学位期间成果时，添加的小标题会默认缩进。请问如何取消小标题的缩进？

**Comment by sikouhjw** [comment]
> 使用thesistheaccomplish环境生成攻读学位期间成果时，添加的小标题会默认缩进。请问如何取消小标题的缩进？

1. 没有 `thesistheaccomplish` 环境，只有 `\thesisaccomplish` 命令
2. 提问要给完整的例子，你说的小标题是怎么输入的？

**Comment by WolfgangFred** [comment]
> > 使用thesistheaccomplish环境生成攻读学位期间成果时，添加的小标题会默认缩进。请问如何取消小标题的缩进？
> 
> 1. 没有 `thesistheaccomplish` 环境，只有 `\thesisaccomplish` 命令
> 2. 提问要给完整的例子，你说的小标题是怎么输入的？

在首页有提示说“手动添加使用\bibitem命令将文章条目列在thesistheaccomplish环境下，方法与参考文献相同，这种方法优势在于可以在条目间加小标题区分项目或论文成果。” 这里主要是想用来分隔发表论文和专利。
目前我具体的使用例子是：
\begin{thesistheaccomplish}
	\section*{一、发表论文}
	\item 张三, 李四. 时间步进算法中阻抗矩阵的高效存储新方法[J]. 电波科学学报, 2010, 25(4):624-631.
	\section*{二、专利}
\end{thesistheaccomplish}

使用后的效果如下图所示：


![image](https://user-images.githubusercontent.com/67274430/85309158-c17d9f00-b4e4-11ea-842c-93d66a0f74d8.png)

**Comment by sikouhjw** [comment]
复现问题的MWE：
```tex
\documentclass{ctexart}
\usepackage{titlesec}
\titleformat{\section}[block]
  {\fontsize{14pt}{14pt}\selectfont\strong}
  {\thesection}{7pt}{}
\begin{document}
\begin{thebibliography}{9}
  \section{test}
  \bibitem{a} test
\end{thebibliography}
\end{document}
```
是 `thebibliography` 导致的问题

**Comment by WolfgangFred** [comment]
> 复现问题的MWE：
> 
> ```
> \documentclass{ctexart}
> \usepackage{titlesec}
> \titleformat{\section}[block]
>   {\fontsize{14pt}{14pt}\selectfont\strong}
>   {\thesection}{7pt}{}
> \begin{document}
> \begin{thebibliography}{9}
>   \section{test}
>   \bibitem{a} test
> \end{thebibliography}
> \end{document}
> ```
> 
> 是 `thebibliography` 导致的问题

谢谢提示

**Comment by WolfgangFred** [comment]
> 复现问题的MWE：
> 
> ```
> \documentclass{ctexart}
> \usepackage{titlesec}
> \titleformat{\section}[block]
>   {\fontsize{14pt}{14pt}\selectfont\strong}
>   {\thesection}{7pt}{}
> \begin{document}
> \begin{thebibliography}{9}
>   \section{test}
>   \bibitem{a} test
> \end{thebibliography}
> \end{document}
> ```
> 
> 是 `thebibliography` 导致的问题
    
```\documentclass[master]{thesis-uestc}
\title{时域积分方程时间步进算法及其快速算法}
{The Time Marching Scheme of Time Domain
    Integral Equation and Corresponding Fast Algorithm}
\author{王稳}{Wang Wen}
\advisor{赖生建\chinesespace 副教授}{Dr. Shengjian Lai}
\school{物理电子学院}{School of Physical Electronics}
\major{无线电物理}{Radio Physics}
\studentnumber{201421040223}
\begin{document}
\makecover
\input{misc/chinese_abstract}
\input{misc/english_abstract}
\thesistableofcontents
\input{chapter/c1_exordium}
\input{chapter/c2}
\input{chapter/c3}
\input{chapter/c4}
\input{chapter/c5}
\input{misc/acknowledgement}
\input{misc/appendix}
\thesisbibliography{reference}
\begin{thesistheaccomplish}
	\setlength{\parindent}{2em}
	\section*{一、发表论文}
	\item 张三, 李四. 时间步进算法中阻抗矩阵的高效存储新方法[J]. 电波科学学报, 2010, 25(4):624-631
	\section*{二、专利}
\end{thesistheaccomplish}
\input{misc/translate_original}
\input{misc/translate_chinese}
\end{document}```

**Comment by x-magus** [comment]
加带号数的小标题用的命令是\section而不是\section*，\section*命令会自动缩进\section的号数所占的空间。如果要修改\section的号数样式要使用相应的命令修改样式，而不是使用\section*命令。

**Comment by WolfgangFred** [comment]
> 加带标号的小标题用的命令是`\section`而不是`\section*`，`\section*`命令会自动缩进`\section`的标号所占的空间。如果要修改`\section`的标号样式要使用相应的命令修改样式，而不是使用`\section*`命令。

谢谢师兄指点，已解决
