### ISSUE TITLE
请问overleaf模板中独创声明那一页肿么添加进去呢？生成的PDF里面肿么没有呢，谢谢

### ISSUE THREAD

**Issue by Jornen** [x-magus/ThesisUESTC#127]
请问overleaf模板中独创声明那一页肿么添加进去呢？生成的PDF里面肿么没有呢，谢谢

**Comment by sikouhjw** [comment]
> 论文封面和扉页由 `\makecover` 命令添加，可以显示论文题目，作者，指导老师等。正式提交论文时文印中心会统一提供封面和扉页，无论自己排版的封面是否符合格式要求。已经包含的封面也不会影响任何前期的审核。独创性声明可以由 `\originalitydeclaration` 命令生成。
ref: https://x-magus.github.io/ThesisUESTC/

**Comment by Jornen** [comment]
> > 论文封面和扉页由 `\makecover` 命令添加，可以显示论文题目，作者，指导老师等。正式提交论文时文印中心会统一提供封面和扉页，无论自己排版的封面是否符合格式要求。已经包含的封面也不会影响任何前期的审核。独创性声明可以由 `\originalitydeclaration` 命令生成。
> 
> ref: https://x-magus.github.io/ThesisUESTC/

好的，谢谢你，明白了
