### ISSUE TITLE
模板中关于100以及100之后的参考文献对齐问题。

### ISSUE THREAD

**Issue by Jornen** [x-magus/ThesisUESTC#129]
![41913ee17245877c06bf5df82953b56](https://user-images.githubusercontent.com/66385249/94421100-a55e5d80-01b7-11eb-88fd-6a8e16bab0f1.png)
请问，100以前的参考文献没有问题。100以及100以后的参考文献的第二行总是比第一行向前突出来一小截儿，请问如何对齐哇？感谢

**Comment by x-magus** [comment]
README里面有写，当参考文献数目超过100时，可以使用large选项调整编号的宽度，如\thesisbibliography[large]{reference}。
