### ISSUE TITLE
建议封面Logo使用学校标准的矢量图

### ISSUE THREAD

**Issue by boyzkm** [x-magus/ThesisUESTC#130]
感谢王同学的模板！！
有个小建议，学校的[VI系统](http://vi.uestc.edu.cn/)里面给出了标准的logo矢量文件，现在模板中封面学校logo(pdf)和系统中还是略有差别，并且清晰度不高，建议在下次的更新中替换成官方的文件。

**Comment by boyzkm** [comment]
[logo.zip](https://github.com/x-magus/ThesisUESTC/files/5445225/logo.zip)

**Comment by x-magus** [comment]
这个校徽logo的蓝色外圈明显比通常见到的校徽图案要宽一些，尤其是郭沫若题写的校名内侧的边框有点大，不知道有没有人注意到了。

**Comment by boyzkm** [comment]
细看是有点儿，这个是学校党委宣传部给出的标准图以及相应的规范，应该是最权威的，与这个不符的就是乱用。
问题是大家还看这标准的有点儿别扭，错误的反而更习惯。。。

**Comment by x-magus** [comment]
呃，这个校徽明摆着就是党委宣传部给错了。

**Comment by boyzkm** [comment]
> 呃，这个校徽明摆着就是党委宣传部给错了。
