### ISSUE TITLE
专硕的封面和扉页和研究生官网的不一致

### ISSUE THREAD

**Issue by Chenmi08** [x-magus/ThesisUESTC#131]
1. 学硕封面是"学科专业"， 专硕则是“专业学位类别”
2. 在扉页中，专硕少了工程领域那一栏

 差别用红色框标明了
![专硕封面](https://user-images.githubusercontent.com/37946111/101351214-37c36180-38cb-11eb-8793-794acf573824.PNG)

**Comment by sikouhjw** [comment]
论文封面和扉页由 `\makecover` 命令添加，可以显示论文题目，作者，指导老师等。正式提交论文时文印中心会统一提供封面和扉页，无论自己排版的封面是否符合格式要求。已经包含的封面也不会影响任何前期的审核。
