### ISSUE TITLE
能不能提供支持overleaf的版本呢

### ISSUE THREAD

**Issue by 541968679** [x-magus/ThesisUESTC#132]
貌似很多字体都不能在overleaf上面用

**Comment by sikouhjw** [comment]
https://x-magus.github.io/ThesisUESTC/

**Comment by sikouhjw** [comment]
https://x-magus.github.io/ThesisUESTC/

**Comment by 541968679** [comment]
啊，感激不尽，我眼睛瞎了不好意思

**Comment by 541968679** [comment]
不过我搜到了，貌似只需要把字体文件放进去就可以了

**Comment by sikouhjw** [comment]
> 不过我搜到了，貌似只需要把字体文件放进去就可以了

ThesisUESTC 在 Overleaf 的版本就是帮你把字体文件放进去了

**Comment by 541968679** [comment]
是的，字体文件是在谷歌字体上面找到的吗

**Comment by sikouhjw** [comment]
> 是的，字体文件是在谷歌字体上面找到的吗

我怎么知道（

应该是缺了 Time News Roman 吧，从 win 系统里复制就好了

**Comment by 541968679** [comment]
这个模板是现在最新的模板吗

**Comment by 541968679** [comment]
不是很清楚每年的官方模板在哪里可以下载

**Comment by sikouhjw** [comment]
> 这个模板是现在最新的模板吗

是最新的

> 不是很清楚每年的官方模板在哪里可以下载

 我记得 @x-magus 是不推荐使用官方模板的，就用这个就行了

**Comment by 541968679** [comment]
好的，感谢大佬
大佬有WX吗

**Comment by sikouhjw** [comment]
> 好的，感谢大佬
> 大佬有WX吗

我不是维护者，你有问题发 issue 就好了
