### ISSUE TITLE
在Miktex下使用模板在命令\makecover处报错

### ISSUE THREAD

**Issue by DozzzeN** [x-magus/ThesisUESTC#133]
在WinEdt中添加了latexmk包并进行了配置，在编译时报错
![1](https://user-images.githubusercontent.com/13940316/103750141-50957300-5041-11eb-8da6-e914360aea05.jpg)
![2](https://user-images.githubusercontent.com/13940316/103750152-5428fa00-5041-11eb-9b4b-66d6d35d92f9.jpg)

**Comment by sikouhjw** [comment]
排查后，应该是 `uline` 宏包的问题

**Comment by DozzzeN** [comment]
> 排查后，应该是 `ulem` 宏包的问题

我这边环境中`ulem`包是有的，请问需要如何解决

**Comment by metaCoder-00** [comment]
我和你的问题一样，请问你后来解决了吗？

**Comment by sikouhjw** [comment]
> 
> 
> 我和你的问题一样，请问你后来解决了吗？

设置 `-interaction=nostopmode` 可以让输出效果无误，但交叉引用会出现问题。

建议在本地端写好文本，去 Overleaf 输出终稿。

**Comment by metaCoder-00** [comment]
好的 谢谢

**Comment by x-magus** [comment]
最好使用latexmk编译模版。

**Comment by sikouhjw** [comment]
> 
> 
> 最好使用latexmk编译模版。

跟 `latexmk` 无关，就是 bug

**Comment by x-magus** [comment]
这个MikTeX版本没问题吗，我看最新的已经是21.1了。

**Comment by muzimuzhi** [comment]
需要问题复现时的版本信息，例如 `\listoffiles` 输出到 log 的版本信息。

**Comment by x-magus** [comment]
不知道这个解决方案是否使用这种情况 https://github.com/x-magus/ThesisUESTC/issues/136#issuecomment-775326696

**Comment by Henning742** [comment]
> 排查后，应该是 `ulem` 宏包的问题

感谢您指出`ulem`的问题，我今日在SO上搜到了解决方法：
https://tex.stackexchange.com/questions/582383/ulem-with-hspace-error

`calc`包更改了`\hspace`的功能，但是`ulem`包没有对该修改做出更新。

可以在`\begin{document}`前加上如下字段解决问题：

```
\makeatletter
\def\@hspace#1{\begingroup\setlength\skip@{#1}%
    \edef\x{\endgroup\hskip\the\skip@\relax}\x}%
\makeatletter
```

**Comment by DozzzeN** [comment]
问题解决了，感谢 @x-magus @Henning742 @sikouhjw

**Comment by x-magus** [comment]
是&符号的问题吗？

**Comment by x-magus** [comment]
只有miktex的ulem包有问题吗？

**Comment by yanghaoxie** [comment]
> 只有miktex的ulem包有问题吗？

我是archlinux 的texlive，也有这个问题。
添加了
```
\makeatletter
\def\@hspace#1{\begingroup\setlength\skip@{#1}%
    \edef\x{\endgroup\hskip\the\skip@\relax}\x}%
\makeatletter
```
解决了问题。

**Comment by x-magus** [comment]
注释掉cls文件93行的`\RequirePackage{calc}`能解决问题吗，可以的话就不用强行注入代码了。 @yanghaoxie @Henning742 @DozzzeN

**Comment by yanghaoxie** [comment]
> 注释掉cls文件93行的`\RequirePackage{calc}`能解决问题吗，可以的话就不用强行注入代码了。 @yanghaoxie @Henning742 @DozzzeN

`archlinux 5.11.2-arch1-1, texlive-core  2020.57066-1`，似乎没有解决问题。

**Comment by x-magus** [comment]
https://tex.stackexchange.com/questions/568732/uline-does-not-work-with-hspace 这个方案应该更好一些。

**Comment by x-magus** [comment]
最新的commit (9aaba310c903d02ec1103dbdddb9bed989a21974)应该已经没有这问题了。

**Comment by yanghaoxie** [comment]
> 最新的commit ([9aaba31](https://github.com/x-magus/ThesisUESTC/commit/9aaba310c903d02ec1103dbdddb9bed989a21974))应该已经没有这问题了。

非常感谢，`archlinux 5.11.2-arch1-1, texlive-core 2020.57066-1`下，问题已经被解决(https://github.com/x-magus/ThesisUESTC/commit/9aaba310c903d02ec1103dbdddb9bed989a21974).

**Comment by logan0czy** [comment]
非常感谢！使用最新一版的模板\makecover报错的问题已经解决！
(texlive2020-basic-x86_64-darwin
