### ISSUE TITLE
建议对不同的数学定理环境重新编号

### ISSUE THREAD

**Issue by boyzkm** [x-magus/ThesisUESTC#138]
研究生院给出的模型中只出现了一次关于数学定理环境的描述，并没有对是否重新编号作出特别的要求。
不同环境使用相同的编号，比如 《定理2.1》 后使用定义时为 《定义2.2》，再接例子成了《例子2.3》，从编号的角度看不太便于区分。
个人建议不同环境可以重新编号，比如定理从1开始，定义也从1开始，方便区分。

此外，经管学科会经常使用的 假设,assumption 和 结果,result，也建议在模板中增加，方便直接使用。

感谢付出！

**Comment by x-magus** [comment]
模版是按照专业数学书的习惯排版的，这样确实对理解内容有很好的帮助。分别编号的话索隐会很混乱，不方便前后翻找。
