### ISSUE TITLE
listings包无法使用

### ISSUE THREAD

**Issue by qq12cvhj** [x-magus/ThesisUESTC#140]
Environment lstlisting undefined.
使用listings包报的错误，没办法显示代码啊

**Comment by sikouhjw** [comment]
提供一份mwe可以吗？

**Comment by qq12cvhj** [comment]
环境:Tex Live 2020 on Windows
模板使用的本模板
使用`listings`包提示`Environment lstlisting undefined.`
代码如下:
```
\documentclass{standalone}
\usepackage{listings}
\begin{document}
\begin{lstlisting}[language=C, label=lst:helloworld, caption=Helloworld, numbers=left, basicstyle=\ttfamily]
int main()
{
    printf("Hello world!\n");
    return 0;
}
\end{lstlisting}
\end{document}

```
需要注意的是，直接在main_file.tex插入本代码没问题，能够编译出来。
但是正常情况下本模板通过include的方式来引入的，即在main_file.tex中引入一个tex文件，该被include的tex文件里面使用的listings包，这个时候就报错了。
[demo.zip](https://github.com/x-magus/ThesisUESTC/files/5938478/demo.zip)

**Comment by qq12cvhj** [comment]
问题暂时解决，但是`\usepackage{listings}`是通过在main_file.tex中声明才管用的。为什么其他的包，在各自被include的文件中声明就好，但是`listings`需要在main_file.tex中声明？

**Comment by sikouhjw** [comment]
> 为什么其他的包，在各自被include的文件中声明就好，但是`listings`需要在main_file.tex中声明？

你提供的 `demo.zip` 中的写法是错误的，被 `\include` 的文件里面不能有 `\documentclass`，也不能在正文去引用宏包，应当直接写内容。

建议使用 github 上的最新版，看看示例是怎么写的。

**Comment by qq12cvhj** [comment]
好的，谢谢哈。可能不是bug，只是由于不熟悉语法规则导致的。
