### ISSUE TITLE
"彧“字无法显示

### ISSUE THREAD

**Issue by TATangZY** [x-magus/ThesisUESTC#142]

**Comment by sikouhjw** [comment]
你用的是 Overleaf？提供编译环境、操作系统、发行版信息。

**Comment by TATangZY** [comment]
![图片](https://user-images.githubusercontent.com/40294324/110330760-1f451d80-8059-11eb-9af0-8847ee26a135.png)

**Comment by TATangZY** [comment]
> 
> 
> 你用的是 Overleaf？提供编译环境、操作系统、发行版信息。

对，我用的 Overleaf

**Comment by sikouhjw** [comment]
> > 你用的是 Overleaf？提供编译环境、操作系统、发行版信息。
> 
> 对，我用的 Overleaf

简单的说，添加文档类选项 `fontset=ubuntu`。

详细的说，去看 `texdoc ctex`

**Comment by TATangZY** [comment]
> 
> 
> > > 你用的是 Overleaf？提供编译环境、操作系统、发行版信息。
> > 
> > 
> > 对，我用的 Overleaf
> 
> 简单的说，添加文档类选项 `fontset=ubuntu`。
> 
> 详细的说，去看 `texdoc ctex`。

OK, 多谢

**Comment by sikouhjw** [comment]
问题解决了，就关掉 issue 吧。
