### ISSUE TITLE
关于图题中“-”字体的问题

### ISSUE THREAD

**Issue by qiankun214** [x-magus/ThesisUESTC#145]
您好
在2021届毕业生中开始使用自动格式审查系统进行格式审查，使用本模板会产生图题/表题“-”字体无法通过检查的问题，原文为：
```latex
图 2-1 这是一个图题
```
其中的“-”字体按格式要求应当为TNR，但是在审查格式系统中，要求使用宋体的“-”，否则自动格式审查系统会报错：
“xx-x-图题-错误-编号格式(要求：图x-x实际：图x)

**Comment by sikouhjw** [comment]
https://github.com/x-magus/ThesisUESTC/issues/144
