### ISSUE TITLE
在英文关键词遇到Overfull \hbox (23.65533pt too wide)问题，最后一个单词schizophrenia，关键词超出页边距

### ISSUE THREAD

**Issue by infzo** [x-magus/ThesisUESTC#149]

**Comment by infzo** [comment]
另外在学校规范里没有找到，英文单词截断后通过连字符-连接，是符合规范的吗？不太清楚^^

**Comment by sikouhjw** [comment]
> 
> 
> 另外在学校规范里没有找到，英文单词截断后通过连字符-连接，是符合规范的吗？不太清楚^^
> 
> 环境是TexLive2020+VSCode

法无禁止即可为。

如果不愿意用 `-` 断词，可以试试 `\tolerance=10000`

**Comment by x-magus** [comment]
可以试试`\hyphenation`命令手动设置断词。

**Comment by infzo** [comment]
嗯嗯，好的，谢谢^^
