### ISSUE TITLE
【关于表格横置问题】

### ISSUE THREAD

**Issue by lschenjing** [x-magus/ThesisUESTC#150]
想问下大型表格，想横置要怎么操作呀？
我现在试了landscape和\usepackage[figuresright]{rotating}都不起作用，请问有谁遇到过相同的问题吗

**Comment by sikouhjw** [comment]
ref: 刘海洋, sec 5.2.3 页面旋转
```tex
% \usepackage{rotfloat}
\begin{sidewaysfigure}[p]
\includegraphics[width=7in]{example-image.pdf}
\caption{test}
\end{sidewaysfigure}
```

**Comment by lschenjing** [comment]
> ref: 刘海洋, sec 5.2.3 页面旋转
> 
> ```
> % \usepackage{rotfloat}
> \begin{sidewaysfigure}[p]
> \includegraphics[width=7in]{example-image.pdf}
> \caption{test}
> \end{sidewaysfigure}
> ```
谢谢回复！这个意思是插入图片然后旋转吗？

**Comment by sikouhjw** [comment]
> 
> 
> > ref: 刘海洋, sec 5.2.3 页面旋转
> > ```
> > % \usepackage{rotfloat}
> > \begin{sidewaysfigure}[p]
> > \includegraphics[width=7in]{example-image.pdf}
> > \caption{test}
> > \end{sidewaysfigure}
> > ```
> 
> 谢谢回复！这个意思是插入图片然后旋转吗？

可以使用 `rotfloat` 宏包提供的 `sidewaystable` 和 `sidewaysfigure` 环境来插入浮动的表格或图形，同时不会影响浮动页前后的内容。

**Comment by muzimuzhi** [comment]
> > ref: 刘海洋, sec 5.2.3 页面旋转
> > ```
> > % \usepackage{rotfloat}
> > \begin{sidewaysfigure}[p]
> > \includegraphics[width=7in]{example-image.pdf}
> > \caption{test}
> > \end{sidewaysfigure}
> > ```
> 
> 谢谢回复！这个意思是插入图片然后旋转吗？

@lschenjing 是指放在 `sidewaysfigure` 环境里

**Comment by sikouhjw** [comment]
> 
> 
> > > ref: 刘海洋, sec 5.2.3 页面旋转
> > > ```
> > > % \usepackage{rotfloat}
> > > \begin{sidewaysfigure}[p]
> > > \includegraphics[width=7in]{example-image.pdf}
> > > \caption{test}
> > > \end{sidewaysfigure}
> > > ```
> > 
> > 
> > 谢谢回复！这个意思是插入图片然后旋转吗？
> 
> @lschenjing 是指放在 `sidewaysfigure` 环境里

实际上应该是 `sidewaystable`，我偷懒了（

**Comment by muzimuzhi** [comment]
我也没仔细看

**Comment by lschenjing** [comment]
> > > > ref: 刘海洋, sec 5.2.3 页面旋转
> > > > ```
> > > > % \usepackage{rotfloat}
> > > > \begin{sidewaysfigure}[p]
> > > > \includegraphics[width=7in]{example-image.pdf}
> > > > \caption{test}
> > > > \end{sidewaysfigure}
> > > > ```
> > > 
> > > 
> > > 谢谢回复！这个意思是插入图片然后旋转吗？
> > 
> > 
> > @lschenjing 是指放在 `sidewaysfigure` 环境里
> 
> 实际上应该是 `sidewaystable`，我偷懒了（

想问个很蠢的问题，\usepackage{rotfloat} 是放在.tex里面的\documentclass[master]{thesis-uestc}
之前吗？\usepackage[figuresright]{rotating}也是用sidewaystable环境，然后试了也不行（刚刚试了下）

**Comment by lschenjing** [comment]
> > > ref: 刘海洋, sec 5.2.3 页面旋转
> > > ```
> > > % \usepackage{rotfloat}
> > > \begin{sidewaysfigure}[p]
> > > \includegraphics[width=7in]{example-image.pdf}
> > > \caption{test}
> > > \end{sidewaysfigure}
> > > ```
> > 
> > 
> > 谢谢回复！这个意思是插入图片然后旋转吗？
> 
> @lschenjing 是指放在 `sidewaysfigure` 环境里

感谢回复！d

> > > ref: 刘海洋, sec 5.2.3 页面旋转
> > > ```
> > > % \usepackage{rotfloat}
> > > \begin{sidewaysfigure}[p]
> > > \includegraphics[width=7in]{example-image.pdf}
> > > \caption{test}
> > > \end{sidewaysfigure}
> > > ```
> > 
> > 
> > 谢谢回复！这个意思是插入图片然后旋转吗？
> 
> @lschenjing 是指放在 `sidewaysfigure` 环境里

感谢回复！但是我还没有搞定，哈哈哈哈哈

**Comment by sikouhjw** [comment]
```tex
\documentclass[master]{thesis-uestc}
\usepackage{rotfloat}
\begin{document}
\begin{sidewaystable}[p]
\begin{tabular}{c}
    test \\
    test
\end{tabular}
\caption{test}
\end{sidewaystable}
\end{document}
```

**Comment by lschenjing** [comment]
> ```
> \documentclass[master]{thesis-uestc}
> \usepackage{rotfloat}
> \begin{document}
> \begin{sidewaystable}[p]
> \begin{tabular}{c}
>     test \\
>     test
> \end{tabular}
> \caption{test}
> \end{sidewaystable}
> \end{document}
> ```
太感谢了！我把\usepackage{rotfloat}放在了最前面去了。。。被自己蠢哭了。已经搞定了！谢谢！！
