### ISSUE TITLE
help, how to deal with this error

### ISSUE THREAD

**Issue by saiftumrani** [x-magus/ThesisUESTC#152]
Couldn't open `OT:script=hani;language=dfl.cfg' hbf2gf (CJK v
er. 4.8.4)

Sorry, but miktex-maketfm did not succeed. The log file hopefully contains the information to get MiKTeX going again: C:\Users\saift\AppData\Local\MiKTeX\miktex\log\miktex-maketfm.log
Sorry, but miktex-makemf did not succeed. The log file hopefully contains the information to get MiKTeX going again: C:\Users\saift\AppData\Local\MiKTeX\miktex\log\miktex-makemf.log

Couldn't open `OT:script=hani;language=dfl.cfg' hbf2gf (CJK v
er. 4.8.4)
Sorry, but miktex-maketfm did not succeed. The log file hopefully contains the information to get MiKTeX going again: C:\Users\saift\AppData\Local\MiKTeX\miktex\log\miktex-maketfm.log
Sorry, but miktex-makemf did not succeed. The log file hopefully contains the information to get MiKTeX going again: C:\Users\saift\AppData\Local\MiKTeX\miktex\log\miktex-makemf.log

Couldn't open `OT:script=hani;language=dfl.cfg' hbf2gf (CJK v
er. 4.8.4)

**Comment by sikouhjw** [comment]
Please type from the command line `xelatex --help`.

**Comment by saiftumrani** [comment]
Sorry, but miktex-makemf did not succeed.

The log file hopefully contains the information to get MiKTeX going again:

  C:\Users\saift\AppData\Local\MiKTeX\miktex\log\miktex-makemf.log
Running miktex-ttf2pk.exe...
Running miktex-ttf2pk.exe...
Creating unisong8b.pk...
Installing C:\Users\saift\AppData\Local\MiKTeX\fonts/pk/modeless/zhmetrics/unisong/dpi723\unisong8b.pk...
 <C:\Users\saift\AppData\
Local\MiKTeX\fonts/pk/modeless/zhmetrics/unisong/dpi723\unisong8b.pk>Trying to make PK font unisong75 at 723 DPI...
The METFAONT mode is: ljfour
Running miktex-makemf.exe...

Sorry, but miktex-makemf did not succeed.

**Comment by sikouhjw** [comment]
It seems that miktex was not installed successfully. Please use `install-latex-guide-zh-cn.pdf` to install texlive2020.

**Comment by saiftumrani** [comment]
can't i solve this problem on miktex?

**Comment by sikouhjw** [comment]
Make sure your Miktex installation is correct.

**Comment by saiftumrani** [comment]
how can i make correct miktex installation do you have document for miktex too like this install-latex-guide-zh-cn.pdf

**Comment by sikouhjw** [comment]
no

**Comment by saiftumrani** [comment]
can you please guide how to install miktex correctly then ? should i update all the packages?

**Comment by sikouhjw** [comment]
I don't understand miktex.

**Comment by sikouhjw** [comment]
You can try Overleaf.
