### ISSUE TITLE
添加缩略词导致缩写前空格消失

### ISSUE THREAD

**Issue by yanghaoxie** [x-magus/ThesisUESTC#154]
使用\makeglossaries及\thesisglossarylist添加缩略词表之后，发现缩写之前与中文的空格消失，如下图第三行所以。如果不添加别两个命令的话，前面的空格不消失。
![space-between-acronyms](https://user-images.githubusercontent.com/10540480/112279182-9831af80-8cbe-11eb-8a2f-23f75b2856e2.jpg)

WME如下：
```
\documentclass[doctor]{thesis-uestc}


\makeglossaries
\newacronym[description=随机优化]{so}{SO}{Stochastic Optimization}

\begin{document}

\thesisglossarylist


 我喜欢\gls{so}方法

 我喜欢\gls{so}方法

 我喜欢SO方法
 
\end{document}
```

**Comment by sikouhjw** [comment]
老 bug 了，https://github.com/CTeX-org/ctex-kit/issues/392

结论是：手动添加空格

**Comment by yanghaoxie** [comment]
> 老 bug 了，[CTeX-org/ctex-kit#392](https://github.com/CTeX-org/ctex-kit/issues/392)
> 
> 结论是：手动添加空格

非常感谢你的如此高时效的回复。:smile:

**Comment by yanghaoxie** [comment]
想到了一个workaround，不知你觉得这样好吗？
我发现只有使用了宏`\makeglossaries`才会出现这种现象，于是可以用模板中介绍的不使用`\makeglossaries`来生成缩略词表，即
```
若想在缩略词表中列出所有定义过的条目，无论在正文中是否引用，可以在\thesisglossarylist之前使用\glsaddall命令。
```
WME如下，
```
\documentclass[doctor]{thesis-uestc}


% \makeglossaries
\newacronym[description=随机优化]{so}{SO}{Stochastic Optimization}

\begin{document}

\glsaddall
\thesisglossarylist


\thesischapterexordium

 我喜欢\gls{so}方法

 我喜欢\gls{so}方法
 
\end{document}
```
