### ISSUE TITLE
摘要编号问题

### ISSUE THREAD

**Issue by logan0czy** [x-magus/ThesisUESTC#155]
论文中先后使用chinese_abstract和english_abstract命令生成摘要，编译之后的pdf中，页码编号却是从英文摘要那里开始的（罗马数字1），中文摘要的那一部分没有任何显示（即没有被编号），请问这是什么问题呢

**Comment by sikouhjw** [comment]
https://github.com/x-magus/ThesisUESTC/issues/153

**Comment by logan0czy** [comment]
十分感谢！
