### ISSUE TITLE
公式字符大小不一样

### ISSUE THREAD

**Issue by lzdnico** [x-magus/ThesisUESTC#156]
如果公式中含有分号，公式各个字符大小不一样。
如图，分母sin就明显小于分子的L

![image](https://user-images.githubusercontent.com/12426615/112837115-0ebf1a80-90ce-11eb-97db-979498241eae.png)

**Comment by sikouhjw** [comment]
`texdoc lshort-zh-cn`, sec 4.2.1 行内和行间公式

这不是 bug，这是你们看不惯 LaTeX 的风格的审美问题

**Comment by lzdnico** [comment]
> `texdoc lshort-zh-cn`, sec 4.2.1 行内和行间公式
> 
> 这不是 bug，这是你们看不惯 LaTeX 的风格的审美问题

指导老师点名说这样不行，请问如何修改呢？保证所有字符大小一致

**Comment by sikouhjw** [comment]
在导言区加上 `\everymath{\displaystyle}`

**Comment by sikouhjw** [comment]
> 
> 
> 在导言区加上 `\everymath{\displaystyle}`

感觉还不够，再重定义 `\frac` 好了
```tex
\documentclass{article}
\usepackage{amsmath}
\everymath{\displaystyle}
\let\frac\dfrac
\begin{document}
  $\frac{1}{2\frac{1}{2}}$
\end{document}
```

**Comment by lzdnico** [comment]
实在抱歉，只会使用。可否告知在哪个文件修改呢

> > 在导言区加上 `\everymath{\displaystyle}`
> 
> 感觉还不够，再重定义 `\frac` 好了
> 
> ```
> \documentclass{article}
> \usepackage{amsmath}
> \everymath{\displaystyle}
> \let\frac\dfrac
> \begin{document}
>   $\frac{1}{2\frac{1}{2}}$
> \end{document}
> ```

**Comment by sikouhjw** [comment]
```tex
\documentclass[master]{thesis-uestc}
\everymath{\displaystyle}
\let\frac\dfrac
\begin{document}
....
\end{document}
```

**Comment by sikouhjw** [comment]
这样会有一系列未知的问题，比如
```tex
\documentclass[master]{thesis-uestc}
\everymath{\displaystyle}
\let\frac\dfrac
\begin{document}
  $\frac{L}{\int \frac{\sin x}{x}}$
\end{document}
```
分母的积分符号不够大，这时候要加上 `\displaystyle`，也就是
```tex
$\frac{L}{\displaystyl\int \frac{\sin x}{x}}$
```
所以这样很麻烦，既然是老师要求的，那就手动改吧

**Comment by lzdnico** [comment]
![image](https://user-images.githubusercontent.com/12426615/112839303-9d349b80-90d0-11eb-8a25-db293121a348.png)

非常感谢，大小已经一致了

**Comment by lzdnico** [comment]
积分符号等盲审看看结果了

**Comment by sikouhjw** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/12426615/112839303-9d349b80-90d0-11eb-8a25-db293121a348.png)
> 
> 非常感谢，大小已经一致了

导师：你这个积分符号不行（（（
