### ISSUE TITLE
bibtex期卷号不完整的问题

### ISSUE THREAD

**Issue by boyzkm** [x-magus/ThesisUESTC#159]
如果bibitem里面只有volume没有number可以编译出期号，如果只有number没有volume就啥都编译不出来。有些期刊只给出出期号number没有卷号volume，这种情况帮助处理一下，感谢！（现在是用onlynote暂时替代着的）

**Comment by yanghaoxie** [comment]
没记错的话，卷号都是有的吧，期号有可能没有。你的是什么期刊，给个`只给出期号number没有卷号volume`的链接呢？

**Comment by yanghaoxie** [comment]
没看错的话，学校规范没有定义无卷号如何处理。如果是我的话，我直接把期号当卷号，期号为空。

**Comment by boyzkm** [comment]
我之前就这么干的，但被老板批了，说我有期卷号不规范的明显错误。

**Comment by yanghaoxie** [comment]
```
有些期刊只给出出期号number没有卷号volume，这种情况帮助处理一下，感谢！
```
你需要给出一个符合要求的格式，学校没有定义如何处理，模板开发者也是不知道如何处理的。
你可以问问你们老师什么格式才是规范的，然后才可以latex实现。

**Comment by zepinglee** [comment]
可以参考《[GB/T 7714 新标准对旧标准的主要修改及实施要点提示](http://bjxb.cessp.org.cn/ch/reader/view_abstract.aspx?file_no=20150411&flag=1)》，作者是 GB/T 7714—2015 起草人。
<img width="332" alt="Screen Shot 2022-02-18 at 12 14 16" src="https://user-images.githubusercontent.com/12290822/154616326-5878ddd8-4cba-4ea7-8a70-99b791f9b730.png">

**Comment by zepinglee** [comment]
> 没看错的话，学校规范没有定义无卷号如何处理。如果是我的话，我直接把期号当卷号，期号为空。

这个是错误的。
