### ISSUE TITLE
怎么将参考文献左对齐

### ISSUE THREAD

**Issue by wly0218** [x-magus/ThesisUESTC#16]
怎么才能将参考文献在如下红线处对齐？资格审查提出的问题，谢谢！
![default](https://user-images.githubusercontent.com/25203670/38202284-c8dfeace-36cd-11e8-831c-dfae064963c1.png)

**Comment by wanygen** [comment]
现在编号那一列的宽度是固定的，100以内是没问题，100以上会有点窄。如果强行变得太宽的话前面的数字后面空白太大会很难看。能不能建议学校改一下格式规范，这样规定真的很瘆人。

**Comment by FFengIll** [comment]
这个事情被challenge其实是不合理的，学校word的模板到了三位数index一样会有偏移（而且比issue的明显严重更多）。
关于格式规范这个事情，还是非常尴尬的。
![image](https://user-images.githubusercontent.com/7359555/38225161-20d05ab8-3726-11e8-8f83-a25cfdd626c5.png)

**Comment by wly0218** [comment]
word是他们没做好，但是现在要求都必须在红线处对齐，100之前的距离大点没关系，给段代码，谢谢！

**Comment by wly0218** [comment]
以解决，谢谢！

**Comment by Cubernet** [comment]
@wly0218 请问你最后怎么解决的对齐问题？
