### ISSUE TITLE
专业硕士封面格式有误

### ISSUE THREAD

**Issue by mh-lan** [x-magus/ThesisUESTC#165]
1. 第一封面页“学科专业”应为“专业学位类别”
2. 第二封面页“申请学位级别”与“学科专业”应为“申请学位级别”、“专业学位类别”，并在下一行写“工程领域名称”

**Comment by sikouhjw** [comment]
https://github.com/x-magus/ThesisUESTC/blob/master/README.md#%E8%AE%BA%E6%96%87%E5%B0%81%E9%9D%A2

**Comment by MH-Lan** [comment]
> https://github.com/x-magus/ThesisUESTC/blob/master/README.md#%E8%AE%BA%E6%96%87%E5%B0%81%E9%9D%A2

图书馆上传版本无法依赖文印中心制作封面。

**Comment by sikouhjw** [comment]
> 
> 
> > https://github.com/x-magus/ThesisUESTC/blob/master/README.md#%E8%AE%BA%E6%96%87%E5%B0%81%E9%9D%A2
> 
> 图书馆上传版本无法依赖文印中心制作封面。

用 word 生成封面 pdf 文件，再 `texdoc pdfpages`，`\includepdf`

**Comment by MH-Lan** [comment]
> > > https://github.com/x-magus/ThesisUESTC/blob/master/README.md#%E8%AE%BA%E6%96%87%E5%B0%81%E9%9D%A2
> > 
> > 
> > 图书馆上传版本无法依赖文印中心制作封面。
> 
> 用 word 生成封面 pdf 文件，再 `texdoc pdfpages`，`\includepdf`

这个问题当然有很多解决方法，我希望有能力的同学能直接改一下cls文件。觉得没必要也ok，我就是反映一下。

**Comment by x-magus** [comment]
主要是感觉专硕的封面有点难看吧，就没什么动力去整了。。

**Comment by MH-Lan** [comment]
> 主要是感觉专硕的封面有点难看吧，就没什么动力去整了。。

好的，毕竟现有的cls已经能满足绝大多数需求了。那我建议在readme部分单独说一句专硕封面没有调，我之前就以为设置promaster就完全合适了，闹了笑话。。。
