### ISSUE TITLE
知网查重报告是否能检验出目录层次

### ISSUE THREAD

**Issue by Freedomisgood** [x-magus/ThesisUESTC#167]
使用了基于ThesisUESTC的Latex模板，但知网查重提交论文后发现无法检验出目录层次，paperyy是可以的。

**Comment by sikouhjw** [comment]
无法检测会有什么影响吗

**Comment by Freedomisgood** [comment]
> 无法检测会有什么影响吗

:disappointed_relieved: 据说是不影响答辩。 但真的是有不能检测出目录层次这个问题，是么？

**Comment by sikouhjw** [comment]
> 
> 
> > 无法检测会有什么影响吗
> 
> 😥 据说是不影响答辩。 但真的是有不能检测出目录层次这个问题，是么？

不重要就不要去担心
