### ISSUE TITLE
关于避开参考文献被查重的方法

### ISSUE THREAD

**Issue by sikouhjw** [x-magus/ThesisUESTC#168]
由于用 pdf 查重时，查重系统不会识别「参考文献」，可能会导致查重率增加。

降重方法（有风险）：
1. 将需要处理的 pdf 单独弄出来，用 pdfpages 宏包
2. 将 pdf 处理成“不能复制的”位图 pdf
3. 用 pdfpages 宏包，在适当的位置输出你处理过的 pdf
4. 会有一些问题：交叉引用失败、页眉页脚可能会有问题
1. 交叉引用留到最后手动加上
2. 页眉页脚手动处理异常位置
3. 超链接（目录），手动加上

**Comment by x-magus** [comment]
这个模板查重我记得一直是没问题的，知网的系统都会识别参考文献部分。其他的查重工具就不好说了。

**Comment by sikouhjw** [comment]
> 
> 
> 这个模板查重我记得一直是没问题的，知网的系统都会识别参考文献部分。其他的查重工具就不好说了。

他应该是去淘宝买的查重，所以不能识别参考文献。
