### ISSUE TITLE
makecover编译错误

### ISSUE THREAD

**Issue by wyixiang** [x-magus/ThesisUESTC#17]
ubuntu16.04，texlive，编译初始文件出了这种错误
![2018-04-15 17 42 34](https://user-images.githubusercontent.com/21034627/38777102-eaf05156-40d4-11e8-97e6-6c15d164c476.png)
请问应该怎样解决

**Comment by wanygen** [comment]
ubuntu需要的字体有么？另外能不能给一下原始输出？

**Comment by wyixiang** [comment]
拷贝了宋体，黑体，和新罗马这几种字体
日志是这样的
.................................................
. LaTeX info: "xparse/redefine-command"
. 
. Redefining command \Pifont with sig. 'm' on line 13.
.................................................
File: ./pic/logo.pdf Graphic file (type QTm)
<use  "./pic/logo.pdf" >
LaTeX Font Info:    Calculating math sizes for size <10.5> on input line 15.
LaTeX Font Info:    Try loading font information for OT1+lmr on input line 15.
 (/usr/share/texmf/tex/latex/lm/ot1lmr.fd
File: ot1lmr.fd 2009/10/30 v1.6 Font defs for Latin Modern
)
LaTeX Font Info:    Try loading font information for OML+lmm on input line 15.

(/usr/share/texmf/tex/latex/lm/omllmm.fd
File: omllmm.fd 2009/10/30 v1.6 Font defs for Latin Modern
)
LaTeX Font Info:    Try loading font information for OMS+lmsy on input line 15.


(/usr/share/texmf/tex/latex/lm/omslmsy.fd
File: omslmsy.fd 2009/10/30 v1.6 Font defs for Latin Modern
)
LaTeX Font Info:    Try loading font information for OMX+lmex on input line 15.


(/usr/share/texmf/tex/latex/lm/omxlmex.fd
File: omxlmex.fd 2009/10/30 v1.6 Font defs for Latin Modern
)
LaTeX Font Info:    External font `lmex10' loaded for size
(Font)              <10.5> on input line 15.
LaTeX Font Info:    External font `lmex10' loaded for size
(Font)              <7.34996> on input line 15.
LaTeX Font Info:    External font `lmex10' loaded for size
(Font)              <5.25> on input line 15.
LaTeX Font Info:    Try loading font information for U+msa on input line 15.

(/usr/share/texlive/texmf-dist/tex/latex/amsfonts/umsa.fd
File: umsa.fd 2013/01/14 v3.01 AMS symbols A
)
LaTeX Font Info:    Try loading font information for U+msb on input line 15.

(/usr/share/texlive/texmf-dist/tex/latex/amsfonts/umsb.fd
File: umsb.fd 2013/01/14 v3.01 AMS symbols B
)
! Missing number, treated as zero.
<to be read again> 
                   [
l.15 \makecover
               
A number should have been here; I inserted `0'.
(If you can't figure out why I needed to see a number,
look up `weird error' in the index to The TeXbook.)

! Missing number, treated as zero.
<to be read again> 
                   t
l.15 \makecover
               
A number should have been here; I inserted `0'.
(If you can't figure out why I needed to see a number,
look up `weird error' in the index to The TeXbook.)

! Illegal unit of measure (pt inserted).
<to be read again> 
                   t
l.15 \makecover
               
Dimensions can be in units of em, ex, in, pt, pc,
cm, mm, dd, cc, bp, or sp; but yours is a new one!
I'll assume that you meant to say pt, for printer's points.
To recover gracefully from this error, it's best to
delete the erroneous units; e.g., type `2' to delete
two letters. (See Chapter 27 of The TeXbook.)


Overfull \hbox (2.91724pt too wide) in paragraph at lines 15--15
[]\EU1/times.ttf(0)/m/n/10.5 t 
 []


Overfull \hbox (3.49658pt too wide) in paragraph at lines 15--15
[]|\EU1/times.ttf(0)/m/n/10.5 ]|  
 []


Overfull \vbox (29.02425pt too high) detected at line 15
 []

(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/se-ascii-print.def
File: se-ascii-print.def 2011/12/02 v1.10 stringenc: Printable ASCII characters

)
[1

\openout3 = `main_multifile.ist'.

]
LaTeX Font Info:    External font `lmex10' loaded for size
(Font)              <12> on input line 15.
LaTeX Font Info:    External font `lmex10' loaded for size
(Font)              <8> on input line 15.
LaTeX Font Info:    External font `lmex10' loaded for size
(Font)              <6> on input line 15.

Overfull \hbox (0.55862pt too wide) in paragraph at lines 15--15
\EU1/simsun.ttc(0)/m/n/12 分 类 号     密 级     
 []


Underfull \hbox (badness 10000) in paragraph at lines 15--15

 []

\g__fontspec_family_simhei.ttf_int=\count286
.................................................
. fontspec info: "defining-font"
. 
. Font family 'simhei.ttf(0)' created for font 'simhei.ttf' with options
. [Script={CJK}].
. 
. This font family consists of the following NFSS series/shapes:
. - 'normal' (m/n) with NFSS spec.:
. <->"[simhei]/OT:script=hani;language=DFLT;"
. - 'small caps'  (m/sc) with NFSS spec.: 
.................................................

Overfull \hbox (29.81761pt too wide) in paragraph at lines 15--15
[] 
 []


Overfull \hbox (30.01863pt too wide) in paragraph at lines 15--15
[] 
 []


Overfull \hbox (28.12064pt too wide) in paragraph at lines 15--15
[] 
 []

[2]
\openout2 = `misc/chinese_abstract.aux'.

 (./misc/chinese_abstract.tex
Overfull \hbox (2.0pt too wide) in paragraph at lines 10--11
[] []
 []

LaTeX Font Info:    Font shape `EU1/times.ttf(0)/m/sl' in size <12> not availab
le
(Font)              Font shape `EU1/times.ttf(0)/m/it' tried instead on input l
ine 11.
[1


] [2])
\openout2 = `misc/english_abstract.aux'.

 (./misc/english_abstract.tex
Underfull \hbox (badness 3260) in paragraph at lines 8--8
[]\EU1/times.ttf(0)/m/n/12 time-domain electromagnetic scattering, time-domain 
integral equation
 []


Overfull \hbox (2.0pt too wide) in paragraph at lines 8--9
[] []
 []

[3



] [4])
\tf@toc=\write8
\openout8 = `main_multifile.toc'.

 [5


]
\openout2 = `chapter/exordium.aux'.

 (./chapter/exordium.tex
Chapter 第一章.

**Comment by wanygen** [comment]
你用什么命令编译的？感觉输出还是不完整。

**Comment by Rocuku** [comment]
makecover 出问题可能和 multirow 的版本也有关系，v2.0 之前的版本`\multirow[t]{2}{4.6in}{}`这句貌似会出错。

https://github.com/x-magus/ThesisUESTC/blob/a5e3ffd8e3ce5609c711c0bac2326e5dfff0eee7/thesis-uestc.cls#L546
这里
`\multirow[t]{2}{4.6in}`
改成
`\multirow{2}{4.6in}[1em]`
应该也可以解决

**Comment by x-magus** [comment]
现在没法复现这个问题。现有的版本编译\makecover并没有发现报错。
