### ISSUE TITLE
overleaf更新

### ISSUE THREAD

**Issue by wfjlulu** [x-magus/ThesisUESTC#171]
应该更新一下overleaf的版本，overleaf编译出来的pdf不是最新版本。或者使用此模板的同学在overleaf中更新cls文件

**Comment by sikouhjw** [comment]
> 使用Overleaf在线编辑只需点击下方图片链接打开发布在 Overleaf Gallery 里的模版，点击 Open as Template 即可使用，在线自动编译和预览。Overleaf模板唯一的区别在于直接使用放置在项目根目录的字体文件。

自己加一下字体不就好了

**Comment by x-magus** [comment]
Overleaf已经更新了
