### ISSUE TITLE
参考文献跨页问题

### ISSUE THREAD

**Issue by JontyYu** [x-magus/ThesisUESTC#173]
模板里设置的是参考文献过长不跨页，导致底部可能会留白，怎么设置弹性itemseq？

**Comment by sikouhjw** [comment]
> 参考文献**不跨页编排**，即一条文献所在段中不分页；

我真心建议用 word 呢

**Comment by x-magus** [comment]
学校的规定是不能跨页的。

**Comment by sikouhjw** [comment]
如果你非要设置，那么设置 `\bibsep` 即可。弹性距离是什么请自行读入门手册。
