### ISSUE TITLE
分割文件编译不显示目录问题（2022年1月版本）

### ISSUE THREAD

**Issue by MOGUSIJI** [x-magus/ThesisUESTC#174]
main_multifile.tex文件

**Comment by sikouhjw** [comment]
1. 你的发行版、编译方式是什么？
2. 用命令行编译 `latexmk -xelatex main_multifile.tex`

**Comment by MOGUSIJI** [comment]
texlive2020+winedt10.3   编译直接在winedt使用Xelatex编译，编译未分割版本有目录

**Comment by sikouhjw** [comment]
分不分割对编译结果毫无影响，请确保你编译了多次。
请提供 log 文件。

**Comment by MOGUSIJI** [comment]
试了Compile之后再xelatex编译目录就出来了，感谢！

**Comment by MOGUSIJI** [comment]
试了Compile之后再xelatex编译目录就出来了，感谢！

**Comment by hmwang1206** [comment]
请问现在overleaf中的是2022年1月的新模板吗？还是使用新模板只能下载您这个包，在自己主机离线运行？

**Comment by sikouhjw** [comment]
> 请问现在overleaf中的是2022年1月的新模板吗？还是使用新模板只能下载您这个包，在自己主机离线运行？

1. 不要在多个地方重复提问
2. 单个问题单独提问

**Comment by hmwang1206** [comment]
> > 请问现在overleaf中的是2022年1月的新模板吗？还是使用新模板只能下载您这个包，在自己主机离线运行？
> 
> 1. 不要在多个地方重复提问
> 2. 单个问题单独提问

已收到您的解答，谢谢!
