### ISSUE TITLE
digital类型参考文献格式问题

### ISSUE THREAD

**Issue by TpstCoder** [x-magus/ThesisUESTC#175]
依照学校给出的参考文献格式和该网址 https://www.zhihu.com/question/20876064?sort=created
似乎对于digital类型的文献（如白皮书），访问日期（format.date）应该在网址（format.url）前面。是否需要修改呢？

**Comment by sikouhjw** [comment]
`texdoc gbt7714`
```tex
\usepackage{gbt7714}
\bibliographystyle{gbt7714-numerical}
```

**Comment by TpstCoder** [comment]
> `texdoc gbt7714`
> 
> ```
> \usepackage{gbt7714}
> \bibliographystyle{gbt7714-numerical}
> ```

我用这个包，作者的名字全是大写的。而且字体和间距都比较大，感觉很丑。

**Comment by muzimuzhi** [comment]
> 我用这个包，作者的名字全是大写的。

这是 gb/t 7714 的「要求/样式」

**Comment by sikouhjw** [comment]
> > `texdoc gbt7714`
> > ```
> > \usepackage{gbt7714}
> > \bibliographystyle{gbt7714-numerical}
> > ```
> 
> 我用这个包，作者的名字全是大写的。而且字体和间距都比较大，感觉很丑。

1. 《GB/T 7714-2015》规定了作者名要大写
2. 直接复制我的代码是不能在模板里编译成功的，说明你没有『真正的』去适配模板
3. 那么你所说的『字体和间距都比较大，感觉很丑』是没什么意义的
4. 1. 将 cls 的三处 `thesis-uestc` 改为 `gbt7714-numerical`
   2. 将 `\RequirePackage{cite}` 换成 `\RequirePackage{gbt7714}`
   3. `latexmk -xelatex main`

**Comment by TpstCoder** [comment]
> > > `texdoc gbt7714`
> > > ```
> > > \usepackage{gbt7714}
> > > \bibliographystyle{gbt7714-numerical}
> > > ```
> > 
> > 
> > 我用这个包，作者的名字全是大写的。而且字体和间距都比较大，感觉很丑。
> 
> 1. 《GB/T 7714-2015》规定了作者名要大写
> 2. 直接复制我的代码是不能在模板里编译成功的，说明你没有『真正的』去适配模板
> 3. 那么你所说的『字体和间距都比较大，感觉很丑』是没什么意义的
> 4. 1. 将 cls 的三处 `thesis-uestc` 改为 `gbt7714-numerical`
>    2. 将 `\RequirePackage{cite}` 换成 `\RequirePackage{gbt7714}`
>    3. `latexmk -xelatex main`

1. 我没有直接复制你的代码。在这个版本发布前我已经自己改了gbt7714的reference style。只是我个人不太喜欢。
2. 学校给的规范文件示例里，作者名字只有首字母大写。字体大小和间距也是和当前的bst一致而不是和gbt7714一致。所以最后到底以什么为准我也不确定。在那之前我按自己喜好先不用gbt7714

**Comment by sikouhjw** [comment]
导言区加上
```tex
\pretocmd{\bibliography}{
  \thispagestyle{fancy}
  \interlinepenalty=10000
  \begin{spacing}{1.667}
  \small
}{}{}
\apptocmd{\bibliography}{
  \end{spacing}
}{}{}
\setlength{\bibsep}{0pt}
```
cls 除了上面说的，还要注释
```tex
\pretocmd{\bibliography}{
  \thispagestyle{fancy}
  \interlinepenalty=10000
  \begin{spacing}{1.667}
}{}{}

\apptocmd{\bibliography}{
  \end{spacing}
}{}{}
```

结果对比
![图片](https://user-images.githubusercontent.com/49770925/152635160-c90bd504-ec35-4a3d-98fb-8848a009fcb6.png)
![图片](https://user-images.githubusercontent.com/49770925/152635173-965c8684-5e4e-47d7-9f99-0685d10334fe.png)

**Comment by rangerpcx** [comment]
> 导言区加上
> 
> ```
> \pretocmd{\bibliography}{
>   \thispagestyle{fancy}
>   \interlinepenalty=10000
>   \begin{spacing}{1.667}
>   \small
> }{}{}
> \apptocmd{\bibliography}{
>   \end{spacing}
> }{}{}
> \setlength{\bibsep}{0pt}
> ```
> 
> cls 除了上面说的，还要注释
> 
> ```
> \pretocmd{\bibliography}{
>   \thispagestyle{fancy}
>   \interlinepenalty=10000
>   \begin{spacing}{1.667}
> }{}{}
> 
> \apptocmd{\bibliography}{
>   \end{spacing}
> }{}{}
> ```
> 
> 结果对比 ![图片](https://user-images.githubusercontent.com/49770925/152635160-c90bd504-ec35-4a3d-98fb-8848a009fcb6.png) ![图片](https://user-images.githubusercontent.com/49770925/152635173-965c8684-5e4e-47d7-9f99-0685d10334fe.png)

老哥，按照你说的改了，还是所有字母都大写要怎么弄啊，可以给一个明确具体一点的方法吗，不知道我哪里弄错了

**Comment by sikouhjw** [comment]
> 老哥，按照你说的改了，还是所有字母都大写要怎么弄啊，可以给一个明确具体一点的方法吗，不知道我哪里弄错了。另外，每条参考文献结尾还应该有句号，这个要怎么修改呢

1. 什么叫『所有字母都大写』？
2. 为什么会没有句号？
3. 你是不是没有删除辅助文件？

**Comment by rangerpcx** [comment]
> 

1. 我没表述清楚，是作者名字还是每个字母都大写。
2. 你发的结果对比里面，第一张图的每一条结尾没有句号（点）,而第二张有。我的情况就是第一种。
3. 辅助文件是什么意思，不太懂。需要删除哪个？

**Comment by rangerpcx** [comment]
> * 我没表述清楚，是作者名字还是每个字母都大写。
> * 你发的结果对比里面，第一张图的每一条结尾没有句号（点）,而第二张有。我的情况就是第一种。
> * 辅助文件是什么意思，不太懂。需要删除哪个？

1. 我没表述清楚，是作者名字还是每个字母都大写。
2. 你发的结果对比里面，第一张图的每一条结尾没有句号（点）,而第二张有。我的情况就是第一种。
3. 辅助文件是什么意思，不太懂。需要删除哪个？

**Comment by muzimuzhi** [comment]
重读了 issue，好像现在走偏了。
 - 题主想问的是，digital 类型文献，访问日期（format.date）应该在网址（format.url）前面，现在的顺序不对
 - 现状是，较早的回复推荐了 `gbt7714` 包，但这个包的样式和题主的「学校规范」有较大出入，然后最近的几条回复就反复在纠结这些差异。

@TpstCoder 不加载 `gbt7714` 包时，是不是除了你反馈的问题，模板的参考文献均符合你的「学校规范」？

**Comment by sikouhjw** [comment]
我的建议是，既然用了《GB/T 7714-2015》，那就不需要看学校给的例子。

**Comment by xlshan666** [comment]
![05f12dc0d8bc60e227b213e5b918eea](https://user-images.githubusercontent.com/99854213/154395115-cedb4805-909b-4cc8-8630-a5a97fffb1f7.jpg)
还是得按照示例的来

**Comment by sikouhjw** [comment]
`texdoc gbt7714` 给了取消全大写的方法；`texdoc biblatex-gb7714-2015` 可以在导言区设置参考文献的诸多格式。

**Comment by xlshan666** [comment]
好的&nbsp; 感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年2月17日(星期四) 上午10:53
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [x-magus/ThesisUESTC] digital类型参考文献格式问题 (Issue #175)





 
texdoc gbt7714 给了取消全大写的方法；texdoc biblatex-gb7714-2015 可以在导言区设置参考文献的诸多格式。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by sikouhjw** [comment]
我仔细看了规范和《GB/T 7714-2015》的不同之处。
著录格式：
1. 期刊论文一致
2. 会议论文差别较大
3. 专著一致
4. 学位论文一致
5. 报纸文章一致
6. 报告一致
7. 授权专利一致
8. 标准一致
9. 电子文献一致

著作细则：
1. 英文文献标题仅第一个单词的首字母大写
2. 英文文献出处（期刊名、会议名等）一般每个单词的首字母大写

也就是说完全可以用 `texdoc gbt7714` 替代现有的处理方案，只需要修改部分地方即可。

**Comment by sikouhjw** [comment]
# 如何修改作者字母全大写？

1. `kpsewhich gbt7714-numerical.bst`，找到 bst 文件的位置，复制一份到工作目录；如果是 Overleaf，就从 ctan 下一份
2. 用文本编辑器打开 bst 文件，将第 64 行的 `  #1 'uppercase.name :=` 改为 `  #0 'uppercase.name :=`
3. 删除全部辅助文件再编译

**Comment by sikouhjw** [comment]
# 如何调节编号与参考文献之间的间距？

在编号较大时，可能无法悬挂对齐，此时可以设置 `\labelsep` 来调节，长度自己定。
```
\setlength{\labelsep}{10pt}
```

**Comment by deareh** [comment]
自己改了一晚上终于把英文姓名大写和会议格式的问题解决了。
需要把gbt7714-numerical.bst文件里边的
 `#1 'uppercase.name :=`
里边的1改成0。
然后把
`FUNCTION {inproceedings}
{ "C" set.entry.mark
  incollection
}`
改成
`FUNCTION {inproceedings}
{ "C" set.entry.mark
  journal.article
}`
之后把bib文件里边的booktitle全部改成journal，这样就可以把会议的格式弄成和期刊一样的了。效果如图
![论文参考文献](https://user-images.githubusercontent.com/48943903/154485304-32bf8989-99db-46df-8083-403fb31d3eeb.png)

**Comment by zepinglee** [comment]
> 将这个模板的 bst 换成 gbt7714 后，编号太大时，前后的编号不能纵向对齐，我解决不了，谁帮忙看看（

这是 `multibib` 的 `resetlabels` 功能的 bug，复现的 MWE：
```latex
\documentclass{article}
\usepackage[numbers]{natbib}
\usepackage[resetlabels]{multibib}
\begin{document}
\begin{thebibliography}{12}
  \bibitem{foo1} foo
  \bibitem{foo2} foo
  \bibitem{foo3} foo
  \bibitem{foo4} foo
  \bibitem{foo5} foo
  \bibitem{foo6} foo
  \bibitem{foo7} foo
  \bibitem{foo8} foo
  \bibitem{foo9} foo
  \bibitem{foo10} foo
  \bibitem{foo11} foo
  \bibitem{foo12} foo
\end{thebibliography}
\end{document}
```

<img width="160" alt="Screen Shot 2022-02-18 at 00 44 09" src="https://user-images.githubusercontent.com/12290822/154529117-d9564784-91fb-43ba-a9c8-622caa3183ff.png">

解决方案：
```latex
\AtBeginDocument{%
  \def\thebibliography#1{%
    \@isnumber{#1}{%
      \ifnum\mb@biblabelwidth=0
        % \@tempcnta\c@NAT@ctr %% changed here to c@NAT@ctr
        \@tempcnta=#1\relax
        \ifcontinuouslabels
          \advance\@tempcnta\c@NAT@ctr
          % \advance\@tempcnta#1%
        \fi
        \std@thebibliography{\@arabic\@tempcnta}%
      \else
        \std@thebibliography{\@arabic\mb@biblabelwidth}%
        \global\mb@biblabelwidth 0
      \fi
    }{%
      \std@thebibliography{#1}%
    }%
  }%
}
```

我对 `multibib` 不太熟，不确定会不会导致别的问题。

**Comment by zepinglee** [comment]
GB/T 7714—2015 要求姓氏圈大写，不过你们学校格式的优先级更高。

**Comment by zepinglee** [comment]
> 导言区加上
> 
> ```
> \pretocmd{\bibliography}{
>   \thispagestyle{fancy}
>   \interlinepenalty=10000
>   \begin{spacing}{1.667}
>   \small
> }{}{}
> \apptocmd{\bibliography}{
>   \end{spacing}
> }{}{}
> \setlength{\bibsep}{0pt}
> ```

@sikouhjw 建议用 `natbib` 的接口设置参考文献内容的格式：
```latex
\renewcommand\bibpreamble{%
  \thispagestyle{fancy}%
  \interlinepenalty=10000%
}
\setlength\bibsep{0bp}
\renewcommand\bibfont{\small\linespread{1.667}\selectfont}
```

另外 `\interlinepenalty=10000%` 禁止在一条文献中间分页太严格了，建议把  `\bibsep` 设成弹性距离允许撑开，这样可以防止可能出现的页面底部大片空白。

**Comment by zepinglee** [comment]
> 自己改了一晚上终于把英文姓名大写和会议格式的问题解决了。 需要把gbt7714-numerical.bst文件里边的 `#1 'uppercase.name :=` 里边的1改成0。 然后把 `FUNCTION {inproceedings} { "C" set.entry.mark incollection }` 改成 `FUNCTION {inproceedings} { "C" set.entry.mark journal.article }` 之后把bib文件里边的booktitle全部改成journal，这样就可以把会议的格式弄成和期刊一样的了。

@deareh 差不多就是这样改，但不建议把  `booktitle` 改成 `journal`。需要帮你们学校改编一份吗？

**Comment by deareh** [comment]
> > 自己改了一晚上终于把英文姓名大写和会议格式的问题解决了。 需要把gbt7714-numerical.bst文件里边的 `#1 'uppercase.name :=` 里边的1改成0。 然后把 `FUNCTION {inproceedings} { "C" set.entry.mark incollection }` 改成 `FUNCTION {inproceedings} { "C" set.entry.mark journal.article }` 之后把bib文件里边的booktitle全部改成journal，这样就可以把会议的格式弄成和期刊一样的了。
> 
> @deareh 差不多就是这样改，但不建议把 `booktitle` 改成 `journal`。需要帮你们学校改编一份吗？

那就很感谢了，我看到他是把会议全部归到了incollection分类里边，但是这个incollection的格式修改我就不会了，不得已出此下策。

**Comment by zepinglee** [comment]
> > > 自己改了一晚上终于把英文姓名大写和会议格式的问题解决了。 需要把gbt7714-numerical.bst文件里边的 `#1 'uppercase.name :=` 里边的1改成0。 然后把 `FUNCTION {inproceedings} { "C" set.entry.mark incollection }` 改成 `FUNCTION {inproceedings} { "C" set.entry.mark journal.article }` 之后把bib文件里边的booktitle全部改成journal，这样就可以把会议的格式弄成和期刊一样的了。
> > 
> > 
> > @deareh 差不多就是这样改，但不建议把 `booktitle` 改成 `journal`。需要帮你们学校改编一份吗？
> 
> 那就很感谢了，我看到他是把会议全部归到了incollection分类里边，但是这个incollection的格式修改我就不会了，不得已出此下策。

已经定制好了，见 https://github.com/x-magus/ThesisUESTC/pull/178#issuecomment-1044584034 。

**Comment by xlshan666** [comment]
请教一个问题哇，参考文献用了双栏对齐\usepackage[keeplastbox]{flushend}或者balance这个包还是无法解决，有没有老哥帮忙看一下。
![image](https://user-images.githubusercontent.com/99854213/154993072-54556101-5f1e-470e-9ce0-d585283f4a04.png)
参考文献的第一行跟第二行怎么对齐

**Comment by sikouhjw** [comment]
> 请教一个问题哇，参考文献用了双栏对齐\usepackage[keeplastbox]{flushend}或者balance这个包还是无法解决，有没有老哥帮忙看一下。 ![image](https://user-images.githubusercontent.com/99854213/154993072-54556101-5f1e-470e-9ce0-d585283f4a04.png) 参考文献的第一行跟第二行怎么对齐

#178
