### ISSUE TITLE
Undefined control sequence. ^^I\subfloat

### ISSUE THREAD

**Issue by Zexylitol** [x-magus/ThesisUESTC#176]
使用支持2022格式规范之后的模板，编译报错了。。

**Comment by x-magus** [comment]
你用的哪个版本的TexLive？

**Comment by Zexylitol** [comment]
2019版的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Wang ***@***.***&gt;; 
发送时间: 2022年2月10日(星期四) 中午11:24
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [x-magus/ThesisUESTC] Undefined control sequence. ^^I\subfloat (Issue #176)





 
你用的哪个版本的TexLive？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Zexylitol** [comment]
> 你用的哪个版本的TexLive？

2019版本的

**Comment by x-magus** [comment]
换成2021版的texlive试试，如果还不行的话再说。

**Comment by Zexylitol** [comment]
> 换成2021版的texlive试试，如果还不行的话再说。

换成2021版的没问题了
