### ISSUE TITLE
图的标题格式

### ISSUE THREAD

**Issue by unsatisfying** [x-magus/ThesisUESTC#177]
似乎模板的图标题格式和latex版本的不太一样，是不是需要修复一下
![image](https://user-images.githubusercontent.com/19465692/153344330-d17ec289-ad9b-4e1b-8a77-f2ae351b3b93.png)
![image](https://user-images.githubusercontent.com/19465692/153344360-89b172a9-71e5-4ffe-b10c-78a6bbefa7b6.png)

Latex的图2-2会突出来，但是要求好像是不突出来。

**Comment by sikouhjw** [comment]
将这行覆盖应该就行了
https://github.com/x-magus/ThesisUESTC/blob/e64c9c5fe6a175f44f912200ba4e66d185095df6/thesis-uestc.cls#L151
在导言区加上
```tex
\captionsetup{format=plain}
```

**Comment by HandMa** [comment]
> 将这行覆盖应该就行了
> 
> https://github.com/x-magus/ThesisUESTC/blob/e64c9c5fe6a175f44f912200ba4e66d185095df6/thesis-uestc.cls#L151
> 
> 
> 在导言区加上
> ```
> \captionsetup{format=plain}
> ```

修改后的缩进字符数与模版不符：

修改后：
![截屏2022-02-22 下午12 29 53](https://user-images.githubusercontent.com/28891837/155063451-ee3ba252-23cc-4749-be70-1ab4d7c6f88e.png)

模版：
![截屏2022-02-22 下午12 30 05](https://user-images.githubusercontent.com/28891837/155063457-ee273ee3-6c2c-4bed-9201-7fcfa00f49c3.png)

**Comment by sikouhjw** [comment]
```tex
\captionsetup{width=\textwidth - 96pt}
```

> > 将这行覆盖应该就行了
> > https://github.com/x-magus/ThesisUESTC/blob/e64c9c5fe6a175f44f912200ba4e66d185095df6/thesis-uestc.cls#L151
> > 
> > 在导言区加上
> > ```
> > \captionsetup{format=plain}
> > ```
> 
> 修改后的缩进字符数与模版不符：
> 
> 修改后： ![截屏2022-02-22 下午12 29 53](https://user-images.githubusercontent.com/28891837/155063451-ee3ba252-23cc-4749-be70-1ab4d7c6f88e.png)
> 
> 模版： ![截屏2022-02-22 下午12 30 05](https://user-images.githubusercontent.com/28891837/155063457-ee273ee3-6c2c-4bed-9201-7fcfa00f49c3.png)
> 
> 感觉还需要修改 （本地测试，不一定正确
> 
> https://github.com/x-magus/ThesisUESTC/blob/e64c9c5fe6a175f44f912200ba4e66d185095df6/thesis-uestc.cls#L152
> 
> 为：
> 
> ```
> \captionsetup{width=\textwidth - 100pt}
> ```
