### ISSUE TITLE
新版格式问题

### ISSUE THREAD

**Issue by HandMa** [x-magus/ThesisUESTC#179]
1、图、表名的缩进问题
repo中的格式：
![截屏2022-02-21 下午8 16 10](https://user-images.githubusercontent.com/28891837/154955056-35e2e0a9-6c8f-4a3e-9311-faa36d0474d7.png)
规范文档中的格式：
![截屏2022-02-21 下午8 16 29](https://user-images.githubusercontent.com/28891837/154955187-47b803e2-1e72-4c64-826b-205cd8d7dcb6.png)

2、repo中参考文献名前姓后，规范为姓前名后

3、repo中好像没有将“攻读学位期间取得的成果”中的论文的本人姓名标粗

**Comment by sikouhjw** [comment]
1. https://github.com/x-magus/ThesisUESTC/issues/177
2. https://github.com/x-magus/ThesisUESTC/issues/175
3. 你自己可以加粗

**Comment by HandMa** [comment]
了解，感谢！
