### ISSUE TITLE
攻读硕士学位期间取得的成果没有显示

### ISSUE THREAD

**Issue by luyifan123654** [x-magus/ThesisUESTC#180]
直接编译repo的main.tex后没看到“攻读硕士学位期间取得的成果”一页

**Comment by HandMa** [comment]
README里面明明有说明。。。

**Comment by MonsterZzT** [comment]
> 直接编译repo的main.tex后没看到“攻读硕士学位期间取得的成果”一页

请问怎么解决的呢？小白看了README还是不懂怎么执行命令，现在用的手动输入TUT
