### ISSUE TITLE
the style file is an illegal style-file command

### ISSUE THREAD

**Issue by Logicino** [x-magus/ThesisUESTC#183]
This is BibTeX, Version 0.99d (TeX Live 2021)
The top-level auxiliary file: main.aux
The style file: thesis-uestc.bst
⁃ is an illegal style-file command---line 20 of file thesis-uestc.bst
 :  ⁃
 :      ENTRY
language is an unknown function---line 266 of file thesis-uestc.bst
author is an unknown function---line 267 of file thesis-uestc.bst
language is an unknown function---line 269 of file thesis-uestc.bst
author is an unknown function---line 270 of file thesis-uestc.bst
author is an unknown function---line 271 of file thesis-uestc.bst
title is an unknown function---line 279 of file thesis-uestc.bst
publisher is an unknown function---line 284 of file thesis-uestc.bst
booktitle is an unknown function---line 289 of file thesis-uestc.bst
journal is an unknown function---line 295 of file thesis-uestc.bst
address is an unknown function---line 300 of file thesis-uestc.bst
year is an unknown function---line 305 of file thesis-uestc.bst
date is an unknown function---line 310 of file thesis-uestc.bst
country is an unknown function---line 315 of file thesis-uestc.bst
type is an unknown function---line 320 of file thesis-uestc.bst
id is an unknown function---line 325 of file thesis-uestc.bst
pages is an unknown function---line 354 of file thesis-uestc.bst
institution is an unknown function---line 360 of file thesis-uestc.bst
url is an unknown function---line 365 of file thesis-uestc.bst
translator is an unknown function---line 383 of file thesis-uestc.bst
translator is an unknown function---line 386 of file thesis-uestc.bst
address is an unknown function---line 390 of file thesis-uestc.bst
pages is an unknown function---line 397 of file thesis-uestc.bst
journal is an unknown function---line 416 of file thesis-uestc.bst
address is an unknown function---line 424 of file thesis-uestc.bst
volume is an unknown function---line 452 of file thesis-uestc.bst
pages is an unknown function---line 453 of file thesis-uestc.bst
number is an unknown function---line 460 of file thesis-uestc.bst
volume is an unknown function---line 460 of file thesis-uestc.bst
volume is an unknown function---line 462 of file thesis-uestc.bst
number is an unknown function---line 462 of file thesis-uestc.bst
pages is an unknown function---line 465 of file thesis-uestc.bst
address is an unknown function---line 475 of file thesis-uestc.bst
journal is an unknown function---line 501 of file thesis-uestc.bst
address is an unknown function---line 518 of file thesis-uestc.bst
note is an unknown function---line 566 of file thesis-uestc.bst
Illegal, read command before entry command---line 570 of file thesis-uestc.bst
 : read
 :     
(There were 37 error messages)
出现错误

这个报错好诡异啊，昨天下午突然写着写着就报错了，之前什么问题都没有的
我看了一下之前出现了一个添加了两次的参考文献，但是删掉了那个参考文献以后还是这个报错
有没有大佬遇到过类似问题解决的能交流一下，感激

**Comment by sikouhjw** [comment]
1. 删除全部辅助文件后再编译
2. 整理不出 MWE 就把文件发我邮箱

**Comment by Logicino** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Logicino** [comment]
> 1. 删除全部辅助文件后再编译
> 2. 整理不出 MWE 就把文件发我邮箱

您好，我把所有的aux log这些删除了重新编译还是遇到这个问题，把模板里原来的引用和参考文献删除了还是有问题。
我觉得还是需要麻烦您帮忙看下～非常感谢～
想请问您的邮箱是wangwen1192@outlook.com这个嘛？
我是把我的main.tex和reference.bib发送给您就行，还是需要把整个文件夹都发给您呢？
谢谢～

**Comment by sikouhjw** [comment]
1. 不是
2. 整个文件夹

**Comment by Logicino** [comment]
请问您的邮箱是多少呀，抱歉我没找到，可以告知嘛，谢谢～
整个文件夹我理解的MWE是把辅助文件删掉以后的，不知道对嘛？
谢谢！

**Comment by sikouhjw** [comment]
> 请问您的�邮箱是多少呀，抱歉我没找到，可以告知嘛，谢谢～ �整个文件夹我理解的MWE是把辅助文件删掉以后的，不知道对嘛？ 谢谢！

1. email: [sikouhjw@gmail.com](mailto:sikouhjw@gmail.com)
2. MWE 是最小工作示例，你的代码不是最小的，直接发就可以了

**Comment by Logicino** [comment]
> > 请问您的�邮箱是多少呀，抱歉我没找到，可以告知嘛，谢谢～ �整个文件夹我理解的MWE是把辅助文件删掉以后的，不知道对嘛？ 谢谢！
> 
> 1. email: [sikouhjw@gmail.com](mailto:sikouhjw@gmail.com)
> 2. MWE 是最小工作示例，你的代码不是最小的，直接发就可以了

好的，我已经发送到您的邮箱了，请查收，非常感谢！
另外我是qq邮箱发送的，不知道是否能顺利发送gmail？如果没有收到的话请告知，我再拿校内邮箱之类的发一下😊

**Comment by sikouhjw** [comment]
> 好的，我已经发送到您的邮箱了，请查收，非常感谢！ 另外我是qq邮箱发送的，不知道是否能顺利发送gmail？如果没有收到的话请告知，我再拿校内邮箱之类的发一下😊

已收到，我有空看看

**Comment by Logicino** [comment]
> > 好的，我已经发送到您的邮箱了，请查收，非常感谢！ 另外我是qq邮箱发送的，不知道是否能顺利发送gmail？如果没有收到的话请告知，我再拿校内邮箱之类的发一下😊
> 
> 已收到，我有空看看

我又重新下载了模板把我这个原来的贴进去试了下，感觉可能是参考文献缺少部分字段的原因，我再研究下！

**Comment by sikouhjw** [comment]
1. 276 行的 `\pif`、`\piK`未定义，改成 `\pi f`、`\pi K`
2. 将 523 行的 `\textsl{}` 删掉
3. 将 `thesis-uestc.bst` 第 20 行改成 `ENTRY`
4. 自行将缺少的字段补上
5. 这完全是你乱写的结果，忽略报错、乱改 bst 文件

**Comment by x-magus** [comment]
既然改动过代码提问一开始就应该说一下。还有自己改动过的代码不属于模板的问题。

**Comment by Logicino** [comment]
> 既然改动过代码提问一开始就应该说一下。还有自己改动过的代码不属于模板的问题。
非常抱歉，在这之前我不知道bst文件被修改了，可能是编译的时候手误点到，非常抱歉！给您带来了麻烦，深表歉意！也对您的解答表示非常感谢！

**Comment by Logicino** [comment]
> 1. 276 行的 `\pif`、`\piK`未定义，改成 `\pi f`、`\pi K`
> 2. 将 523 行的 `\textsl{}` 删掉
> 3. 将 `thesis-uestc.bst` 第 20 行改成 `ENTRY`
> 4. 自行将缺少的字段补上
> 5. 这完全是你乱写的结果，忽略报错、乱改 bst 文件

已修改，非常感谢您的帮助！
耽误了您宝贵的时间，深表歉意与感激。
12 的小错误之前没有注意 非常感谢提醒
3 我在这之前不知道我修改过bst文件，可能是电脑不小心碰到了，修改的时候也没有注意到这里
4 已经改正
5 第一次用模板写大论文，有很多问题还要多多学习，谢谢您的解答！

另外，我想加那个群讨论交流下，但是上个月开始加群一直没有人通过，请问是不是有新的群或者讨论组呢，谢谢！

**Comment by sikouhjw** [comment]
> 另外，我想加那个群讨论交流下，但是上个月开始加群一直没有人通过，请问是不是有新的群或者讨论组呢，谢谢！

可能是群主没注意或没时间通过，没有新的群。

**Comment by Logicino** [comment]
> > 另外，我想加那个群讨论交流下，但是上个月开始加群一直没有人通过，请问是不是有新的群或者讨论组呢，谢谢！
> 
> 可能是群主没注意或没时间通过，没有新的群。

好的～已经进群啦！非常感谢～！
