### ISSUE TITLE
插入伪代码报错“amsmath”相关错误

### ISSUE THREAD

**Issue by bulinx** [x-magus/ThesisUESTC#184]
引用包：
```
\documentclass[master]{thesis-uestc}
\usepackage{algorithm}
\usepackage{algorithmicx}
\usepackage{algpseudocode}
\usepackage{amsmath}
\usepackage{amssymb}
\usepackage[UTF8]{ctex}

\floatname{algorithm}{算法}
\renewcommand{\algorithmicrequire}{\textbf{输入:}}
\renewcommand{\algorithmicensure}{\textbf{输出:}}
\begin{document}`
```
报错
`amsmath' must be loaded earlier than mathspec'`
伪代码输出情况：**end if ，end while** 等输出不全
![1646142663(1)](https://user-images.githubusercontent.com/52736133/156181213-763e6401-bd27-47cd-b1a7-4e5ec11ee70e.png)
请问这个可以怎么解决呢，百度说引用mathspce包，换顺序等方法我都做了，但是没有实际效果。
盼回复~

**Comment by sikouhjw** [comment]
> ```
> \documentclass[master]{thesis-uestc}
> \usepackage{algorithm}
> \usepackage{algorithmicx}
> \usepackage{algpseudocode}
> \usepackage{amsmath}
> \usepackage{amssymb}
> \usepackage[UTF8]{ctex}
> 
> \floatname{algorithm}{算法}
> \renewcommand{\algorithmicrequire}{\textbf{输入:}}
> \renewcommand{\algorithmicensure}{\textbf{输出:}}
> \begin{document}`
> ```


为什么要加这几个包？
```tex
\usepackage{amsmath}
\usepackage{amssymb}
\usepackage[UTF8]{ctex}
```

**Comment by bulinx** [comment]
谢谢提醒，我现在引用
```
 \usepackage{algorithm}
\usepackage{algorithmic}
```
就足够了
