### ISSUE TITLE
参考文献的问题

### ISSUE THREAD

**Issue by deareh** [x-magus/ThesisUESTC#185]
新参考文献在过英文文献这里有个小问题，学校的规定时间作者的名字是姓在前，名在后，例如Li M，姓名中间没有点。然后新的这个文件编译出来是名在前，姓在后，并且姓名中间有点。
学校的规定
![未命名1646213753](https://user-images.githubusercontent.com/48943903/156335424-11d90c41-0473-4145-9ec3-a7b2734768a3.png)
新的问题
![未命名1646213840](https://user-images.githubusercontent.com/48943903/156335449-c00362b7-83cb-4baa-9ef6-38d9a82ee18e.png)

**Comment by deareh** [comment]
还有就是学校要求结尾有点，新的这个模板也没有

**Comment by sikouhjw** [comment]
https://github.com/x-magus/ThesisUESTC/issues/175

**Comment by deareh** [comment]
> #175

这个我看过，但是前几天不是已经重新编写了一份bst文件了吗，有的问题解决了有的没解决

**Comment by deareh** [comment]
> #175

已解决，需更新texlive
