### ISSUE TITLE
项目中参考文献的显示格式与要求的格式似乎不一致

### ISSUE THREAD

**Issue by lixiangpengcs** [x-magus/ThesisUESTC#192]
格式要求文档正文11页第（3）条要求“作者姓在前，名在后，英文姓全拼、首字母大写，英文名大写缩写且不加点”，但是目前项目中的引用是：名在前姓在后，并且多加了一个点。这一点应该对照哪里来进行修改呢？

**Comment by YKX-A** [comment]
`thesis-uestc.bst`中

```
STRINGS  { bibinfo}

FUNCTION {format.names}
{ 'bibinfo :=
  duplicate$ empty$ 'skip$ {
  's :=
  "" 't :=
  #1 'nameptr :=
  s num.names$ 'numnames :=
  numnames 'namesleft :=
    { namesleft #0 > }
    { s nameptr
%      "{f.~}{vv~}{ll}{, jj}"
		 "{vv~}{ll}{, jj}{ f{}}"
      format.name$
```

**Comment by lixiangpengcs** [comment]
多谢，顺利解决

**Comment by Eldad27** [comment]
With this code, Authors with both middle name and last names still have the initials put together without any space (combined together) like below


![Reference problem](https://user-images.githubusercontent.com/37579457/159703925-6de8cb40-e32c-46eb-8efb-047b1d1a95cf.PNG)

Can anyone help please?

> `thesis-uestc.bst`middle
> 
> ```
> STRINGS  { bibinfo}
> 
> FUNCTION {format.names}
> { 'bibinfo :=
>   duplicate$ empty$ 'skip$ {
>   's :=
>   "" 't :=
>   #1 'nameptr :=
>   s num.names$ 'numnames :=
>   numnames 'namesleft :=
>     { namesleft #0 > }
>     { s nameptr
> %      "{f.~}{vv~}{ll}{, jj}"
> 		 "{vv~}{ll}{, jj}{ f{}}"
>       format.name$
> ```
