### ISSUE TITLE
章节序号怎么加粗

### ISSUE THREAD

**Issue by Abraham12580** [x-magus/ThesisUESTC#197]
如题，模板里面章节序号未加粗，怎么改，大佬们有说法吗

**Comment by ZhuGeKongKong** [comment]
把these-uestc.cls文件里的thesection，thesubsection，thesubsubsection加上textbf。具体如下：
\titleformat{\section}[block]
  {\fontsize{14pt}{14pt}\selectfont\strong}
  {\textbf{\thesection}}{7pt}{}

\titleformat{\subsection}[block]
  {\fontsize{14pt}{14pt}\selectfont\strong}
  {\textbf{\thesubsection}}{7pt}{}

\titleformat{\subsubsection}[block]
  {\fontsize{12pt}{12pt}\selectfont\strong}
  {\textbf{\thesubsubsection}}{6pt}{}

**Comment by Abraham12580** [comment]
谢谢大佬！
