### ISSUE TITLE
目录怎么设置深度

### ISSUE THREAD

**Issue by wly0218** [x-magus/ThesisUESTC#21]
现在四级标题在目录中，能不能把深度改成3？在哪里改？谢谢！
![default](https://user-images.githubusercontent.com/25203670/40290937-3590cdf4-5cf4-11e8-86bf-682f93a19fda.png)

**Comment by FFengIll** [comment]
标题的引入是因为使用了section或者subsection （and so on）。
请尝试将对应内容用其他命令分段，而不是section。
这并非生成深度的问题，而是section在latex的处理中就是标题级别。

**Comment by callofdutyops** [comment]
> 四级标题是允许出现在目录的
@FFengIll 请问这个有没有标准的出处？我看到给的`研究生学位论文（含研究报告）撰写范例（中文）`是没有将四级标题加入目录的

**Comment by FFengIll** [comment]
@callofdutyops 这里我的回复有个描述错误。以下补充更正。
如我所回复的：
> 四级标题是允许出现在目录的
是指latex里是允许section相关的各级标题出现在目录中的。

官方的规范里面也没有提及四级标题（实际也有人使用，对此无法评判）。

但一般来说，本硕的论文结构，内容和丰富程度 都不至于使用到四级标题，一般来说用到三级标题即可，其他内容建议通过其他命令分段，如enumeration（· xxx，1) xxx 等）。这种组织结构也比较常见。

latex生成目录含多级这一功能是无需修改的（这是正常的功能），相应地，文章结构或可考虑进行调整。

**Comment by callofdutyops** [comment]
问题似乎已经在https://github.com/x-magus/ThesisUESTC/commit/957b950a79bb2a549648e24c4130665ada5920e1中得到了解决， @FFengIll 可以考虑close issue
