### ISSUE TITLE
本科毕业论文模版存在bug

### ISSUE THREAD

**Issue by FesianXu** [x-magus/ThesisUESTC#22]
学长你好，因为学长这个模版可能是针对于研究生论文格式优化的，对本科的毕业论文支持上可能存在一些bug，现提出望得到解答。

1. 按照“2018本科毕业设计管理办法”（下面简称管理方法），本科毕业论文页眉应为“电子科技大学学士学位论文”而非“电子科技大学本科学位论文”。
2. 按照管理办法，封面有较大差异，具体体现在“电子科技大学”字体，校徽区别等。见下图所示，为学校本科官方封面：
![CWMRKg.png](https://s1.ax1x.com/2018/05/24/CWMRKg.png)
3. 按照管理办法，第二页为空白页而非学位论文页（存疑）
4. 有同学反应在目录页后会凭空多出一页空白页。
5. 按照管理办法，末章题目应为“结论”，两字之间一个**6pt**间距，如绪论一般。
6. 按照管理办法，图题和表题应为**10.5pt**，现好像是**11pt**（存疑）。

感谢学长制作的latex模版方便了广大成电人，希望学长可以完善项目，谢谢！

**Comment by FesianXu** [comment]
补充：
7. 按照管理办法，在引用公式时应该形式如“如式（3-2）”，而目前模版里面出现的是“如式3-2”，需要手动添加中文括号。

**Comment by FFengIll** [comment]
如可能，可否附件添加 最新版 的管理办法？

**Comment by FesianXu** [comment]
电子档管理办法和word版本的模版见百度云：
link: https://pan.baidu.com/s/1Tlta5nlH9-7G3cZL5ght6A
passwd: 94gw

**Comment by wly0218** [comment]
公式引用用\eqref
