### ISSUE TITLE
“\;”报错，“\bm”无效

### ISSUE THREAD

**Issue by Mrneet** [x-magus/ThesisUESTC#26]
论文当中使用了\;在公式中插入适当间隔，但是报错
“Undefined control sequence. ^^I \;”

使用\bm加粗希腊字母时，无效，但不报错。而且希腊字母的字体明显和其他模板（如IEEE，Elsevier）的不一样。

**Comment by wanygen** [comment]
\mathbf是可以加粗的。这个模版用的mathspec包设置的数学字体，可能跟bm包有冲突。其他模版有自己的风格，这个模版只考虑学校给出的格式要求。

**Comment by Mrneet** [comment]
是“\;”，好像没有显示出来分号前面那个斜杠。这个我在IEEE和Elsevier的模板中都是可以正常使用的。现在使用“\,”来代替了，虽然要多输入几个。感谢

**Comment by wanygen** [comment]
学校硕是Times New Roman，模板字体设置从45行开始。空格有很多命令可以用，https://tex.stackexchange.com/questions/74353/what-commands-are-there-for-horizontal-spacing 。

**Comment by Mrneet** [comment]
![image](https://user-images.githubusercontent.com/30075289/42423436-bad092c4-82bf-11e8-97e5-4e89f3647e07.png)
这一个不行，用\thickmuskip也不行，已经改用其他的了
