### ISSUE TITLE
使用latexmk编译后缩略词表为空

### ISSUE THREAD

**Issue by Mrneet** [x-magus/ThesisUESTC#27]
TeXstudio的build设置如下
![image](https://user-images.githubusercontent.com/30075289/42426228-f64c362e-82eb-11e8-8344-20a284a8aa01.png)
主文件代码为
%!TEX options = --shell-escape

\documentclass[doctor]{thesis-uestc}

\title{时域积分方程时间步进算法及其快速算法}
\author{王稳}
\advisor{赖生建\chinesespace 副教授}
\school{物理电子学院}
\major{无线电物理}
\studentid{201421040223}

\usepackage{econometrics,amsmath,bm}
\usepackage{glossaries}

\def \diag {\operatorname{diag}}
\def \blkdiag {\operatorname{blkdiag}}
\def \cov {\operatorname{cov}}

\begin{document}

\makecover

% this is a thesis template with mutiple files: the chapters and the misc in standalone mode
% to avoid too many files in current folder, template add extra direcotry: chapter and misc
% please do not change the sequence of each one except the chapters themselves.
% by FengYouzheng.

% abstract
\include{misc/chinese_abstract}
\include{misc/english_abstract}

% table of contents
\thesisfigurelist
\thesistablelist
\thesisglossarylist

% thesis contents
\include{chapter/ch1}
\include{chapter/ch6}

% misc
\include{misc/acknowledgement}
%\thesisloadbibliography[nocite]{reference}

%
% Uncomment following codes to load bibliography database with native
% \bibliography command.
%
%\nocite{*}
\bibliographystyle{thesis-uestc}
\bibliography{IEEEfull,mybibfile}

% comment while no need
\include{misc/appendix}
\thesisloadachievement{publications_author.bib}

\end{document}

缩略词列表定义在ch1.tex中

%% 缩略词表
\newacronym[description=到达时间]{TOA}{TOA}{Time of Arrival}
\newacronym[description=到达时间差]{TDOA}{TDOA}{Time Difference of Arrival}
\newacronym[description=到达角度]{AOA}{AOA}{Angle of Arrival}
\newacronym[description=波达方向]{DOA}{DOA}{Direction of Arrival}
\newacronym[description=克拉美罗下界]{CRLB}{CRLB}{Cram\'{e}r Rao Lower Bound}
\newacronym[description=均匀线阵]{ULA}{ULA}{Uniform Linear Array}
\newacronym[description=最大似然估计]{MLE}{MLE}{Maximum Likelihood Estimator}
\newacronym[description=多重信号分类]{MUSIC}{MUSIC}{MUltiple SIgnal Classification}
\newacronym[description=最小方差无畸变响应]{MVDR}{MVDR}{Minimum Variance Distortionless Response}
\newacronym[description=均方根误差]{RMSE}{RMSE}{Root Mean Square Error}
\newacronym[description=基于旋转不变技术的信号参数估计]{ESPRIT}{ESPRIT}{Estimation of Signal Parameters by Rotational Invariance Techniques}

编译结果缩略词为空白，但文中\gls引用缩略词正常。

编译时输出消息如下
Process started: latexmk.exe -pdf -silent -synctex=1 "main_multifile"

Latexmk: Run number 1 of rule 'bibtex main_multifile'

Latexmk: Run number 1 of rule 'pdflatex'

Latexmk: Summary of warnings: Latex failed to resolve 4 reference(s)

Latexmk: Run number 2 of rule 'bibtex main_multifile'

Latexmk: Run number 2 of rule 'pdflatex'

Latexmk: Summary of warnings: Latex failed to resolve 4 reference(s)

Latexmk: Run number 3 of rule 'bibtex main_multifile'

Latexmk: Run number 3 of rule 'pdflatex'

Latexmk: Summary of warnings: Latex failed to resolve 4 reference(s)

Latexmk: Run number 4 of rule 'bibtex main_multifile'

Latexmk: Run number 4 of rule 'pdflatex'

Latexmk: Summary of warnings: Latex failed to resolve 4 reference(s)

Latexmk: Run number 5 of rule 'bibtex main_multifile'

Latexmk: Run number 5 of rule 'pdflatex'

Latexmk: Summary of warnings: Latex failed to resolve 4 reference(s)

Latexmk: Maximum runs of bibtex main_multifile reached without getting stable files

Latexmk: Did not finish processing file 'main_multifile': 'bibtex main_multifile' needed too many passes Latexmk: Use the -f option to force complete processing, unless error was exceeding maximum runs of latex/pdflatex.

...s\Dr. Sun\Documents\texlive\2017\bin\win32\runscript.tlu:708: command failed with exit code 12: perl.exe "c:\Users\Dr. Sun\Documents\texlive\2017\texmf-dist\scripts\latexmk\latexmk.pl" -pdf -silent -synctex=1 main_multifile

Process exited with error(s)

**Comment by x-magus** [comment]
缩略词表的宏包已经导入了，显示缩略词表需要`\thesisglossarylist`命令。

**Comment by zhangji2015zhj** [comment]
在目录后加入\thesisglossarylist命令后编译失败，这个命令的使用位置有什么要求吗?

**Comment by x-magus** [comment]
要在document之后目录之前，就是缩略词表页显示的位置。

**Comment by zhangji2015zhj** [comment]
报错信息：
=== Creating rule for 'cusdep glo gls thesis'
Latexmk: applying rule 'cusdep glo gls thesis'...
For rule 'cusdep glo gls thesis', running '&do_cusdep( run_makeglossaries )' ...
Auxiliary file ''thesis'.aux' doesn't exist. Have you run LaTeX?
makeglossaries version 4.37 (2018-04-07)
D:\texlive\2018\bin\win32\runscript.tlu:790: command failed with exit code 2:
perl d:\texlive\2018\texmf-dist\scripts\glossaries\makeglossaries 'thesis'
Rule 'cusdep glo gls thesis', function 'run_makeglossaries'
   failed with return code = 512
Collected error summary (may duplicate other messages):
Latexmk: Errors, so I did not complete making targets
  cusdep glo gls thesis: Command for 'cusdep glo gls thesis' gave return code 512
Latexmk: Use the -f option to force complete processing,
 unless error was exceeding maximum runs of latex/pdflatex.
D:\texlive\2018\bin\win32\runscript.tlu:790: command failed with exit code 12:
perl.exe d:\texlive\2018\texmf-dist\scripts\latexmk\latexmk.pl -synctex=1 -interaction=nonstopmode -file-line-error -pdf e:/OneDrive/2019Thesis/thesis

文档结构（以模板为例，部分修改以下内容）
% abstract
\include{misc/chinese_abstract}
\include{misc/english_abstract}

%% 在此添加
% \thesisglossarylist

% table of contents
\thesistableofcontents

\thesisfigurelist
\thesistablelist

%% 或在此添加
% \thesisglossarylist


%%%略缩词信息
\newacronym[description=逻辑卷管理器]{lvm}{LVM}{Logical Volume Manager}

% thesis contents


两种修改均不行

**Comment by garylavayou** [comment]
@zhangji2015zhj @x-magus 我试过手动编译方式，在生成bbl，gls等辅助文件以后，如果没有对参考文献、缩略语等改动，再使用latexmk编译其实可以正常工作。不过如果没有以上文件的话，latexmk会出错，需要手动编译。 #53

**Comment by zhangji2015zhj** [comment]
确实是，手动编译可以成功。

**Comment by x-magus** [comment]
不用重复\usepackage{glossaries}，模版类文件里已经导入了。我用latexmk编译没问题的。

**Comment by zhangji2015zhj** [comment]
清除编译的中间文件（aux,gls）等 
连续运行两次latexmk 依然无法成功编译
第二次编译的输出log如下：
Latexmk: This is Latexmk, John Collins, 25 October 2018, version: 4.61.
=== TeX engine is 'XeTeX'
Latexmk: Missing input file: 'thesis.gls' from line
  'No file thesis.gls.'
Latexmk: Found input bbl file 'thesis.bbl'
Latexmk: References changed.
Latexmk: Log file says output to 'thesis.pdf'
Latexmk: Found bibliography file(s) [reference.bib]
=== TeX engine is 'XeTeX'
Latexmk: Missing input file: 'thesis.gls' from line
  'No file thesis.gls.'
Latexmk: Found input bbl file 'thesis.bbl'
Latexmk: References changed.
Latexmk: Log file says output to 'thesis.pdf'
Latexmk: ===For rule 'latex', the extensions differ between the
   actual output file 'thesis.pdf',
   and the expected output 'thesis.dvi'.
   This could arise from use of \pdfoutput in the source file,
   or from a configuration error
   A future version of latexmk should be able to make dynamically
   adjustments to deal with this problem
Latexmk: Found bibliography file(s) [reference.bib]
Latexmk: applying rule 'cusdep glo gls thesis'...
Rule 'cusdep glo gls thesis': File changes, etc:
   Non-existent destination files:
      'thesis.gls'
------------
Run number 1 of rule 'cusdep glo gls thesis'
------------
For rule 'cusdep glo gls thesis', running '&do_cusdep( run_makeglossaries )' ...
makeglossaries version 4.41 (2018-07-23)
Auxiliary file ''thesis'.aux' doesn't exist. Have you run LaTeX?
D:\texlive\2018\bin\win32\runscript.tlu:902: command failed with exit code 2:
perl d:\texlive\2018\texmf-dist\scripts\glossaries\makeglossaries 'thesis'
Rule 'cusdep glo gls thesis', function 'run_makeglossaries'
   failed with return code = 512
Latexmk: Errors, so I did not complete making targets
Collected error summary (may duplicate other messages):
  cusdep glo gls thesis: Command for 'cusdep glo gls thesis' gave return code 512
Latexmk: Use the -f option to force complete processing,
 unless error was exceeding maximum runs, or warnings treated as errors.
D:\texlive\2018\bin\win32\runscript.tlu:902: command failed with exit code 12:
perl.exe d:\texlive\2018\texmf-dist\scripts\latexmk\latexmk.pl



此后，运行makeglossaries thesis（主文件名）输出如下：
PS E:\OneDrive\2019Thesis> makeglossaries thesis
makeglossaries version 4.41 (2018-07-23)
added glossary type 'main' (glg,gls,glo)
Warning: File 'thesis.glo' is empty.
Have you used any entries defined in glossary 'main'?
Remember to use package option 'nomain' if you
don't want to use the main glossary.
PS E:\OneDrive\2019Thesis>

在此之后latexmk可以正常编译

**Comment by zhangji2015zhj** [comment]
![image](https://user-images.githubusercontent.com/14149012/54016296-5ad45500-41bd-11e9-9609-025687d3141c.png)

**Comment by zhangji2015zhj** [comment]
@x-magus @garylavayou 
对latexmkrc 文件的做出如下修改，latexmk即可正常编译带略缩词表项的的文件
去除 $_[0] 的单引号

sub run_makeglossaries {
  if ( $silent ) {
    system "makeglossaries -q $_[0]";
  }
  else {
    system "makeglossaries $_[0]";
  };
}

**Comment by x-magus** [comment]
也可能是编译缩略词的shell命令在Windows系统有问题，一般是按Unix的Bash习惯编的。我在MacOS上编译没有问题。

**Comment by zhangji2015zhj** [comment]
https://dev.seemoo.tu-darmstadt.de/templates/seemoo-thesis-template/commit/e6c458c8829dbe3655d38eb5e65b95b9ef2bc5e3
系统问题

**Comment by x-magus** [comment]
已经更新了latexmk的代码。
