### ISSUE TITLE
参考文献article类型必须指定volume参数？

### ISSUE THREAD

**Issue by callofdutyops** [x-magus/ThesisUESTC#30]
若不指定则会报错：
`volume' is a missing field, not a string, for entry xxx
但是似乎不是所有期刊都有volume

**Comment by callofdutyops** [comment]
其他参数也有类似的问题，留空会导致格式出错，bst里似乎没有做处理

**Comment by x-magus** [comment]
格式是按学校的要求给的，我不太清楚有的期刊没有volume，还有是哪个期刊没有分卷？大多数参数都是必需给出的。

**Comment by callofdutyops** [comment]
[1]王友发,周献中.国内外智能制造研究热点与发展趋势[J].中国科技论坛,2016(04):154-160.

这个我用cnki，Google学术，百度学术导出BibTex格式的时候都没有卷号，我去中国科技论坛网站看了一下，似乎确实没有卷号，只有期号；同时搜索了一下和卷号相关的信息，有[博客](http://blog.sciencenet.cn/home.php?mod=space&uid=54276&do=blog&id=309739)说这个可以没有

**Comment by callofdutyops** [comment]
如果将volume留空，例如这样写volume={}，产生的格式是这样的：

[1] 王友发, 周献中. 国内外智能制造研究热点与发展趋势[J]. 中国科技论坛, 2016, (4):154-160

主要区别就在`2016(04)`和`2016, (4)`

**Comment by x-magus** [comment]
国内的期刊都不规范，不太可能全都照顾到的。

**Comment by callofdutyops** [comment]
国外期刊有些也没有，目前我是按照一年一卷计算的。
希望可以加个判断完善，因为卷号有年份的情况确实是可以省略的。

**Comment by callofdutyops** [comment]
似乎留空即可，例如这篇，IEEE xplore到处的格式：
@article{8417407, 
author={A. A. Munshi and Y. A. I. Mohamed}, 
journal={IEEE Access}, 
title={Data Lake Lambda Architecture for Smart Grids Big Data Analytics}, 
year={2018}, 
volume={6}, 
number={}, 
pages={40463-40471}, 
keywords={Smart grids;Big Data;Computer architecture;Real-time systems;Data mining;Distributed databases;Task analysis;Smart grids;smart meter;big data;cloud;data mining;clustering;visualization}, 
doi={10.1109/ACCESS.2018.2858256}, 
ISSN={2169-3536}, 
month={},}
其中number就留空了

已经将此issue标记为close
