### ISSUE TITLE
参考文献作者多于3个会显示“et al”.而不是中文的“等”

### ISSUE THREAD

**Issue by callofdutyops** [x-magus/ThesisUESTC#31]
例如：

author={张三 and 李四 and 王五 and 赵六},
[1] **张三, 李四, 王五, et al.** 题目[J]. 期刊, 年份, 卷号(期号): 页数

**Comment by x-magus** [comment]
可以只写三个作者名字，像author={张三 and 李四 and 王五等}。

**Comment by callofdutyops** [comment]
目前是这样写的，希望可以提供更加clean的解决方案。

**Comment by callofdutyops** [comment]
@FFengIll 
感谢科普，已关闭issue
