### ISSUE TITLE
standalone导致包引用出现问题

### ISSUE THREAD

**Issue by gutouyu** [x-magus/ThesisUESTC#32]
# 问题复现
在子文档`chapter/c2.tex`中使用todonotes 
先 usepackage 然后写一个todo  发现编译报错：`undefined control sequence \todo`

# 问题解决
把usepackage{todonotes}写到主文档main.tex中就可以了。

# 怀疑原因
查看standalone文档，有如下描述：

>The package standalone can be used in the main document to skip all extra
preambles in included files. The main file must load all packages and settings
required by the sub-files.

根据上面的描述，standalone默认会跳过子文件中的所有preambles，所以需要些在main file中。

# 建议
是否考虑去掉standalone或者修改readme说明一下，chapter/c*.tex文件中的注释会误导用户以为可以直接在这里引入新包。

**Comment by x-magus** [comment]
我改一下，是有这个问题⊙﹏⊙

**Comment by FFengIll** [comment]
@x-magus 我一开始的想法有误，误用了standalone。
你在修改了么？我正打算做删减和测试。

**Comment by gutouyu** [comment]
拉了最新的代码  可以了，关闭问题了哈
