### ISSUE TITLE
附录使用问题

### ISSUE THREAD

**Issue by gutouyu** [x-magus/ThesisUESTC#35]
# 问题描述：附录使用问题
readme里面没有详细介绍，只是说可以在附录中写section 或 chapter，
* 试了下chapter 附录里面会显示第X章这样的继续编号，这显然是不对的；
* 试了下section 附录里面会编号1 2 3

# 期待表现
应该是附录中没有编号才对吧？只有附录A 附录B 

还有个问题就是，如果我想写两个附录怎么弄那？table是浮动的格式，附录B的内容会跑到附录A的table的前面，这样好像不太对。应该是附录A全部完了之后才有附录B的内容。

能否麻烦给一个具体的使用示例那？或者丰富下readme之类的，谢谢

**Comment by x-magus** [comment]
是分小结，也就是section，不是章（chapter）。

**Comment by gutouyu** [comment]
@x-magus  分section后还是有编号 1 2 这样的，比如
![image](https://user-images.githubusercontent.com/13641361/51227650-45e2fe80-1990-11e9-8d22-f761f2cf21fc.png)

**Comment by gutouyu** [comment]
好的 谢谢
