### ISSUE TITLE
第二页似乎和目前的模板 有不同

### ISSUE THREAD

**Issue by FanGhost** [x-magus/ThesisUESTC#36]
指导教师处和 latex 相比不同
![_20190129114540](https://user-images.githubusercontent.com/9609368/51882877-76c52980-23bb-11e9-88d6-c96a5e674bba.png)

**Comment by x-magus** [comment]
最后正式提交的封面都是文印中心提供的，格式就算没问题也会重新给你做一个，这个没什么影响。

**Comment by FanGhost** [comment]
> 最后正式提交的封面都是文印中心提供的，格式就算没问题也会重新给你做一个，这个没什么影响。

thx~
