### ISSUE TITLE
相对学校模板缺少英文扉页与独创性声明页

### ISSUE THREAD

**Issue by izhaolei** [x-magus/ThesisUESTC#37]
如题，更具学校研究生的模板([http://gr.uestc.edu.cn/xiazai/114/3917]())，好像缺少这两页，希望大佬能够完善。

**Comment by FFengIll** [comment]
印象中，这些部分最后都要单独打，因为包括封面在内等内容都要额外打印，最后装订到一起（装订时还涉及一些其他材料）。
> 首先确定封面和扉页是文印负责打印的，其次，声明是手写签字的，所以只要打印就好了，不必要和模板关联。

**Comment by x-magus** [comment]
README的封面部分已经更新了。

> 模版不会生成英文扉页和独创性声明，这两页包括中文封面最后正式提交时会由文印中心统一提供，无论自己排版的封面是否符合格式要求。已经包含的封面也不会影响任何前期的审核。
