### ISSUE TITLE
请问有硕士论文的原文么？

### ISSUE THREAD

**Issue by randomwangran** [x-magus/ThesisUESTC#38]
对瞬变电磁非常感兴趣。

想深入阅读这篇硕士论文。

**Comment by x-magus** [comment]
是计算电磁学的论文么？这个评论是毕业论文模版的。

**Comment by randomwangran** [comment]
对的，我发现这个模板只有一部分内容。

第一章绪论里，我看到作者提到，在频率域研究有用到 FEM 的方法。 在我较为熟悉的领域： 计算流体力学，计算固体力学中用的很广泛。

矩量法，快速多极子法是我想了解的东西。

另外，瞬变电磁散射的问题也非常有意思的话题。

希望得到作者的原文进一步阅读。

**Comment by x-magus** [comment]
电磁学很多用积分方程的加略金方法，也就是矩量法。这个论文不是我写的，我也只有一些片段。矩量法和快速多极子有一本_The Method of Moments in Electromagnetics_可以下载到电子书。据我了解研究瞬变电磁场一般用时域方法，不过因为电磁场方程的复杂计算起来非常繁琐。
