### ISSUE TITLE
how about \citeup ?

### ISSUE THREAD

**Issue by FFengIll** [x-magus/ThesisUESTC#39]
模板中使用了citing用于上标引用（相应地，cite为常规引用），对应代码为
`\newcommand{\citing}[1]{\textsuperscript{\cite{#1}}}`

在一些模板（包括老模板中）使用了citeup，对应代码为
`\newcommand{\citeup}[1]{\textsuperscript{\cite{#1}}}`

是否考虑 **添加** citeup？就当初的使用来说，citeup确实更加直观（上标 up）。

**Comment by x-magus** [comment]
从英语的角度讲citeup是很直观但是有点脑残。都大学生了应该适应点不那么直观不那么浅显的东西ˇ﹏ˇ。
