### ISSUE TITLE
目前的算法环境下，algorithm2e自定义样式无效

### ISSUE THREAD

**Issue by FFengIll** [x-magus/ThesisUESTC#40]
审稿发现算法呈现有些“简陋”，讨论和实验后发现是因为样式无效。

首先确定编译上没有问题，但是由于cls重新申明了algorithm环境，

> \DeclareFloatingEnvironment{algorithm}

导致algorithm2e的许多样式设定都不能实际生效（推测有冲突或覆盖）（如boxed，ruled）。

算法的呈现方式非常多样（建议意义明确，且呈现相对美观），在规范上，对算法的呈现也没有严格限制，
因而建议支持使用algorithm2e的丰富设定。

**Comment by FFengIll** [comment]
目前已经尝试得出了一个解决方案，若有需要晚些时候上传。
在此之前，则希望有所讨论。

**Comment by FFengIll** [comment]
主要是去除 \DeclareFloatingEnvironment{algorithm} 和一些相关内容，
并在algorithm2e提供的环境基础上进行cls定义和修改。
最初发现\thealgorithm无效，查询后确定
\renewcommand{\thealgocf}{\arabic{chapter}-\arabic{algocf}}
为有效指令。

**Comment by x-magus** [comment]
algorithm2e宏包是做了很多hack的，主要是算法的标号跟其他float类型的环境很不一致。

**Comment by FFengIll** [comment]
![image](https://user-images.githubusercontent.com/7359555/52710291-f4975080-2fc9-11e9-92a1-8ff14459625c.png)
目前能做到这个程度。
但是如果是这个样式，caption字体就有问题，这个要在想办法了（2e并不能直接captionsetup）
![image](https://user-images.githubusercontent.com/7359555/52710386-25778580-2fca-11e9-97f3-966075e84aa4.png)

**Comment by FFengIll** [comment]
最后字体问题也解决了。如果字体统一为正常，这个样式就会很难看
![image](https://user-images.githubusercontent.com/7359555/52710840-573d1c00-2fcb-11e9-9d11-9871e7cb15b4.png)

所以想讨论下，
个人建议还是统一用\small + 普通字体，保证在任何样式下，都是符合规范的；其他的任何效果，都可以由使用者自行调用algorithm2e的命令去修改，我们只需要简单补充readme即可；规范和自定义需求都可以满足。

**Comment by x-magus** [comment]
我自己是觉得以前那个是挺简洁清晰的，可能改成居中会比较好。这个感觉每个人的喜好都不一样的。

**Comment by FFengIll** [comment]
@x-magus 嗯，每个人喜好不同，这个就放给使用者自行定义吧，无冲突了，可以通过set完成各种定义。
PR#41 已经发送，请review后考虑merge。

**Comment by x-magus** [comment]
<img width="587" alt="screen shot 2019-02-13 at 9 28 04 pm" src="https://user-images.githubusercontent.com/3732959/52715037-62497980-2fd6-11e9-9b3f-3ee89a992319.png">
这个算法环境主要的问题是hang结构的小标题，要与图表的样式保持一致，尤其是多行的时候像上面那样。

**Comment by FFengIll** [comment]
![image](https://user-images.githubusercontent.com/7359555/52758556-bb032b80-3043-11e9-8f70-76ab8516ccf1.png)
长标题多行的问题之前忽视了（PR未处理）。
调整style，暂时是这样的，看来还需要修改。

**Comment by gutouyu** [comment]
所以现在到底怎么样了？最近写论文快被这个问题折磨死了。。
请问下如果我想要下面这样的效果，应该怎么办那?
![image](https://user-images.githubusercontent.com/13641361/53093786-5c621400-3553-11e9-92fb-f1925f9d0f93.png)

**Comment by gutouyu** [comment]
我用`algpseudocode`试了下，可以很轻松的实现上述样式。但是在我们的模板上面使用总是报错。

请问下可以考虑下使用这个包吗？如果可以的话，能否说一下怎么改可以支持这个包的使用吗？

非常感谢~

**Comment by FFengIll** [comment]
@gutouyu 如果你的语法和algorithm2e是一致且兼容的，那么可以考虑使用 pr #41 对应的 cls文件（仅cls即可）。
并在\begin{document} 前
申明\RestyleAlgo[boxruled]  //表示算法为边框显示样式
就可以实现你现在的这个要求，具体效果你可以看看上面的回复。

但这只算是一个临时方案，不过我这边验证是有效的。

**Comment by gutouyu** [comment]
@FFengIll  我按照你说的替换了cls文件，并且加上了`\RestyleAlgo[boxruled] ` 但是报错了：
```
./main.tex:3: LaTeX Error: Missing \begin{document}
```
能加个QQ交流下么？卡在这里很久了。。 毕业季呀。。
麻花藤：531267557  谢谢啦

**Comment by FFengIll** [comment]
@gutouyu 最后的调整了，个人推荐的解决方案如 #41 所述。

**Comment by gutouyu** [comment]
@FFengIll  按你说的改了，非常感谢 基本已经满足我的需求了

**Comment by garylavayou** [comment]
@FFengIll 我想改变一下算法的宽度，可以设置么？还是说论文格式规定与正文一样宽？

**Comment by x-magus** [comment]
问题是带边框algorithm的caption是否能通过格式审查呢？按图表float环境的标题要求的话因该保持一致才对。有同学试过默认的标注格式审查老师有什么反应没有？

**Comment by FFengIll** [comment]
@x-magus rule和box的算法，近两年我们这边（计算机）的格式审查是通过了的。

**Comment by Cubernet** [comment]
@FFengIll 感谢小师姐的这个issue解救我于水火之中😂

**Comment by x-magus** [comment]
重定义的algorithm环境已经在https://github.com/x-magus/ThesisUESTC/commit/7879a144bd0ad3096a5b0e0ea7fbc123642e0275 取消了。
