### ISSUE TITLE
公式中字母加粗，\mathbf变回正体，\bm无效，请问可以用什么代替

### ISSUE THREAD

**Issue by LiPancheng** [x-magus/ThesisUESTC#47]
\mathbf{}加粗并不是数学粗体，而是数学式里头的“一般文字”的粗体，使用后公式由斜体变回正体。
然而用bm包、amsmath包试过都没有效果。
前面已有issue#26提到，作者说可能是与模板使用的mathspec包冲突。那大家在论文写作中是怎么解决的？
另请问作者，如果要换mathspec包该怎么操作！
谢谢！

**Comment by x-magus** [comment]
可以用\pmb命令，另外\mathbf的加粗不符合要求么？

**Comment by LiPancheng** [comment]
是我表述有问题。不是指不符合学校论文要求，论文撰写规范中没有要求公式粗体的形式。只是个人期望是斜体加粗。
另外，\pmb命令确实有效！感谢
