### ISSUE TITLE
关于图片\caption的对齐问题

### ISSUE THREAD

**Issue by dengzelu** [x-magus/ThesisUESTC#50]
希望得到的结果如下：
![tim 20190305172002](https://user-images.githubusercontent.com/29471980/53794464-0043ba80-3f6b-11e9-8165-843044ae9646.png)
即换行后分图题与主图题首字对齐

如果这样写\caption{主图题\\\(a)分图题；(b)分图题}
![tim 20190305172642](https://user-images.githubusercontent.com/29471980/53794932-dccd3f80-3f6b-11e9-8705-26a9666893f5.png)
分图题则会居中对齐

希望能解决一下这个问题

**Comment by callofdutyops** [comment]
研究生院[给出的](http://gr.uestc.edu.cn/xiazai/114/3917)`研究生学位论文（含研究报告）撰写范例（中文）`中，格式是这样的：
![pic](https://user-images.githubusercontent.com/5207896/54110967-b735af80-441d-11e9-924c-57ea89e7ca50.png)
因此我认为这个格式问题并不存在
