### ISSUE TITLE
makeatletter和makeatother在模板类中使用的必要性？

### ISSUE THREAD

**Issue by garylavayou** [x-magus/ThesisUESTC#55]
参考：[Is it really bad to use \makeatletter and \makeatother in a package or class file?][ref1]

如上述资料所述：`@`在`cls`文件和`sty`文件中均默认为字符类型（`catcode=11`），我也在cls文件中定义了以下命令进行测试，
``` latex
\newcommand{\getcatcodeat}{\the\catcode`@}% @ in class is 11
\edef\catcodeat{\the\catcode`@}
```
第一个命令在正文中执行时，返回的是正文中@的类型；第二个命令是获取了在cls文件中@的类型。
因此根据上述资料建议，不必使用`\makeatletter`和`\makeatother`（尤其是`\makeatother`会改变@在`cls`文件中的类型）。

但是我不太清楚在命令的内容部分是否需要执行以上命令。我猜测是需要的，命令的定义应该是在调用的时候才执行的，而不是在`cls`文件中定义时执行的。以下给出`cls`文件中的几处可能的改动：

**1. 环境开始**

``` latex
\makeatletter
\AtBeginEnvironment{table}{
  \def\@floatboxreset{\centering}
}
\makeatother
```
改为
``` latex
\AtBeginEnvironment{table}{
  \makeatletter
  \def\@floatboxreset{\centering}
  \makeatother
}
```
**2. 命令名称**
``` latex
\makeatletter
\renewcommand{\@biblabel}[1]{[#1]\hfill}
\makeatother
```
改为
``` latex
\renewcommand{\@biblabel}[1]{[#1]\hfill}
```
**3. 环境定义**
``` latex
\makeatletter
\renewenvironment{proof}[1][\proofname]{\par
  \pushQED{\qed}
  \normalfont
  \topsep0pt \partopsep0pt
  \trivlist
  \item[\hskip5\labelsep
        \heiti
    #1\@addpunct{:}]\ignorespaces
}{
  \popQED\endtrivlist\@endpefalse
}
\makeatother
```
改为
``` latex
\renewenvironment{proof}[1][\proofname]{
  \par
  \pushQED{\qed}
  \normalfont
  \topsep0pt \partopsep0pt
  \trivlist
  \makeatletter
  \item[\hskip5\labelsep
        \heiti
    #1\@addpunct{:}]\ignorespaces
  \makeatother
}{
  \makeatletter
  \popQED\endtrivlist\@endpefalse
  \makeatother
}
```
不知以上改动是否合适？

[ref1]: https://tex.stackexchange.com/questions/62583/is-it-really-bad-to-use-makeatletter-and-makeatother-in-a-package-or-class-fil/62586

**Comment by x-magus** [comment]
当调整宏包内部结构的时候（一半是含有@的指令）总要加这个命令。

**Comment by garylavayou** [comment]
`@`用于sty或cls文件的内部命令中。
在模板文件中`@`默认是有效的命令字符，而非特殊字符；在文档中则相反。
因此，在文档中调整宏包内容时需要使用`\makeatletter`和`\makeatother`，从而更改这些内部命令；在模板中则可以直接更改，无需上述命令（例如问题中的第二个例子）。

另一方面，我的理解是，模板中定义的命令内容可能不会立即展开，而是在文档中使用时展开。因此，如果命令的内容中又包含内部命令（包含`@`的命令），则在前后添加`\makeatletter`和`\makeatother`（例如问题中的第一个例子）。

**Comment by muzimuzhi** [comment]
@x-magus 
> 当调整宏包内部结构的时候（一半是含有@的指令）总要加这个命令。我也不太清楚深入的机制，但是这确实是规范。

通过 `\documentclass` 载入 cls 文件时会强制修改 @ 的字符类，相当于 cls 文件的开头和结尾有隐形的 `\makeatletter` 和 `\makeatother` 命令。

所以，当前 `thesis-uestc.cls` 文件中的 `\makeatletter` 和 `\makeatother` 都是不必要的。

**Comment by garylavayou** [comment]
@muzimuzhi 同意！但是，如果是模板中定义的命令，其内容包含了`@`，是否需要在前后添加`\makeatletter` 和 `\makeatother `命令，例如以下情况
```latex
% in template file
\AtBeginEnvironment{table}{
  \makeatletter
  \def\@floatboxreset{\centering}
  \makeatother
}
```
此类命令应该是在文档中才会被展开执行？而在文档中`@`属于**其他字符**，所以需要以上两个命令。

**Comment by muzimuzhi** [comment]
> 但是，如果是模板中定义的命令，其内容包含了`@`，是否需要在前后添加`\makeatletter` 和 `\makeatother `命令

是否需要在前后添加？不需要

> 此类命令应该是在文档中才会被展开执行？而在文档中`@`属于**其他字符**，所以需要以上两个命令。

应该是在文档中才会被展开执行？不是

------

首先，`\AtBeginEnvironment` 仍然是在定义新宏。

根据定义
```latex
% etoolbox.sty, line 1751:
\newrobustcmd{\AtBeginEnvironment}[1]{%
  \csgappto{@begin@#1@hook}}
```
其原理是，
 1. `etoolbox` 宏包首先会在 `\begin` 命令里插入一个钩子 `\@begin@<env name>@hook`，默认为空
 1. `\AtBeginEnvironment{<env name>}{<hook code>}` 把 `<hook code>` 追加到钩子 `\@begin@<env name>@hook` 的末尾。

------

其次，更一般地，
 1. 在展开宏（和 primitive 原语）时，宏名和宏参数的字符类已经被唯一确定，都是被展开的宏所在位置（对应下面例子中 `\newcommand` 所处的位置）当前的字符类（对应下面例子中的字符类状态a）
 1. 定义宏的过程，实际也是 `\def`, `\newcommand` 等命令的展开，所以第一条已经包含了所有情况

举个例子

```latex
\documentclass{article}
\begin{document}
\makeatletter
% <字符类状态 a>
\def\@xxx{yyy}
\newcommand\@abc[1]{
  \makeatother
  % <字符类状态b>
  #1\@xxx#1}

\@abc{a}
\end{document}
```

 - 按你的理解，`\@abc` 的定义中 `\@xxx` 应该被 TeX 理解为命令 `\@` 和字母 `xxx` 的组合。这样，`\@abc{a}` 就应该输出 "axxxa"，而实际输出的是 "ayyya"
 - 实际上，`\makeatother #1\@xxx#1` 整个部分作为 `\newcommand` 的参数被读入时，遵循的就都是字符状态类a。`\makeatother` 不会改变 `\@xxx` 被读入时的字符状态类。

------
这个解释远不够清晰。但你的猜测是否为真，都可以通过具体的例子来验证。另外，我会找一找 `texdoc texbytopic` 里与此对应的章节，贴过来。

**Comment by x-magus** [comment]
根据LaTeX2e unofficial reference manual（[https://latexref.xyz/_005cmakeatletter-_0026-_005cmakeatother.html#g_t_005cmakeatletter-_0026-_005cmakeatother](https://latexref.xyz/_005cmakeatletter-_0026-_005cmakeatother.html#g_t_005cmakeatletter-_0026-_005cmakeatother)。Don’t use these inside .sty or .cls files since the \usepackage and \documentclass commands already arrange that the at-sign has the character code of a letter, catcode 11.看起来在class加这两个命令并无必要。
