### ISSUE TITLE
采用mathptmx包影响数学手写字体（\mathcal），建议采用newtxmath包

### ISSUE THREAD

**Issue by garylavayou** [x-magus/ThesisUESTC#58]
在仅使用`mathptmx`包的时候，得到的手写体（花体，使用`\mathcal`得到的，需要`amsfonts`包支持）是这样的
<img src="https://user-images.githubusercontent.com/25133690/54170158-8d799880-44b0-11e9-8cfd-d0ca6fe668dd.png" alt="drawing" height="100"/>
不太美观。
比较正常的手写体显示应该是
<img src="https://user-images.githubusercontent.com/25133690/54170086-3d9ad180-44b0-11e9-951e-653e88acbbe6.png" alt="drawing" height="100"/>
这是在使用`mathptmx`包以后，[重新定义数学符号](https://github.com/shifujun/UESTCthesis)得到的
``` latex
\RequirePackage{mathptmx}
\RequirePackage{amssymb,amsfonts}
\DeclareSymbolFont{symbols} {OMS}{cmsy}{m}{n}
\DeclareSymbolFont{largesymbols}{OMX}{cmex}{m}{n}
\DeclareSymbolFont{operators} {OT1}{cmr} {m}{n}
\DeclareSymbolFont{letters} {OML}{cmm} {m}{it}
\SetSymbolFont{operators}{bold}{OT1}{cmr} {bx}{n}
\SetSymbolFont{letters} {bold}{OML}{cmm} {b}{it}
\SetSymbolFont{symbols} {bold}{OMS}{cmsy}{b}{n}
\RequirePackage{bm}
\RequirePackage{fontspec}
```
我这里没有去深究哪个命令实际影响了手写体的字形，更加详细的可以参考[这里的问答](https://tex.stackexchange.com/questions/58098/what-are-all-the-font-styles-i-can-use-in-math-mode)。
但是以上方式会使得小写字母的字形改变。以下是仅使用`mathptmx`的情况
<img src="https://user-images.githubusercontent.com/25133690/54172539-65dafe00-44b9-11e9-922c-daee4b64caa3.png" alt="drawing" height="40"/>
以下是添加以上代码的输出
<img src="https://user-images.githubusercontent.com/25133690/54172576-886d1700-44b9-11e9-93c5-3ce7dd303f45.png" alt="drawing" height="40"/>
应该是以上的代码设置的字形影响了小写字母。

----------------------------------------------------------------
另一种方式是使用`newtxmath`包，代替`mathptmx`
``` latex
\RequirePackage{lmodern}
\RequirePackage{amsthm}%place it before loading newtxmath
\RequirePackage[cmintegrals,smallerops]{newtxmath}%newtxmath requires <amsmath> [tbtags]clash
% \RequirePackage[tbtags]{amsmath}
```
**注意：这里需要先加载`amsthm`包，避免选项冲突；`newtxmath`会引入`amsmath`，如果再使用`\RequirePackage[tbtags]{amsmath}`的话会导致`[tbtags]`选项冲突；`lmodern`包需要先加载，否则某些符号不能显示。**
这种方式得到的字母字形为
<img src="https://user-images.githubusercontent.com/25133690/54171509-8b660880-44b5-11e9-9d4f-14ce859554bb.png" alt="drawing" height="100"/>
和上一种方法的显示效果基本一样，小写字母也是正常显示。
<img src="https://user-images.githubusercontent.com/25133690/54172652-ca965880-44b9-11e9-9c4a-71bb34a8b2e4.png" alt="drawing" height="40"/>

**Comment by x-magus** [comment]
[tbtags]选项是为了满足学校公式编号底部显示的要求，不能取消的，另外花体在数学文献中也频繁使用。

**Comment by garylavayou** [comment]
@x-magus 我以为`\RequirePackage[tbtags]{amsmath}`会与`newtxmath`发生冲突。其实只要将`\RequirePackage[tbtags]{amsmath}`放在`newtxmath`之前即可。
``` latex
\RequirePackage[tbtags]{amsmath}% avoid [tbtags] clash by loading it before newtxmath
\RequirePackage{amsthm}%place it before loading newtxmath
\RequirePackage[cmintegrals,smallerops]{newtxmath}%newtxmath requires <amsmath> inside
```

**Comment by x-magus** [comment]
据我所知花体一般在数学文献里表示算子operator，像傅立叶变换的F和线性变换的L。花体一般容易跟一般函数或者泛函相区别。可能不是newtxmath但是我会考虑换一个合适的。

**Comment by x-magus** [comment]
现在已经换回mathspec字体方案，花体字体这些都比较美观。
