### ISSUE TITLE
公式很长的情况下，后面的编号在两行的缝中间显示

### ISSUE THREAD

**Issue by mzpmazeping** [x-magus/ThesisUESTC#62]
![image](https://user-images.githubusercontent.com/4424353/54902457-7311d700-4f14-11e9-9026-e082363f39e2.png)

**Comment by mzpmazeping** [comment]
![image](https://user-images.githubusercontent.com/4424353/54902527-a6546600-4f14-11e9-867a-7867edc8f5dd.png)

**Comment by x-magus** [comment]
可以输入多行公式，具体方法看一下latex的教程就行。
