### ISSUE TITLE
取得成果部分，作者顺序在第三作者后不显示

### ISSUE THREAD

**Issue by callofdutyops** [x-magus/ThesisUESTC#65]
若发表刊物在三作之后，会直接显示et al.
可否加大这部分文献作者显示深度值？
目前我的临时解决方法是复制了一份`thesis-uestc.bst`命名为`thesis-uestc-publications.bst`，并修改了`thesis-uestc.cls`中成果部分的引用样式名称为`thesis-uestc-publications`

**Comment by x-magus** [comment]
学校的要求是两个我记得。
