### ISSUE TITLE
封面有“隐藏数据”？

### ISSUE THREAD

**Issue by callofdutyops** [x-magus/ThesisUESTC#66]
使用Adobe PDF阅读器导出TXT格式时，会有

> 博士学位论文
DOCTORAL DISSERTATION 
论文题目基于东拼西凑的电子科技大学毕业论文LATEX模板
生成样例
学科专业软件工程
学号2923000000 
作者姓名时富军

等字样，并且使用邮箱附件预览工具预览时如图所示：
![cover](https://user-images.githubusercontent.com/5207896/55288307-39474180-53e8-11e9-9362-cc51c3f40021.png)

不执行makecover命令无此问题

**Comment by x-magus** [comment]
不太可能吧，你确定没有点错文件么？˙▽˙

**Comment by callofdutyops** [comment]
@x-magus 确定，因为原文件内容还在。感觉像是pdf的metadata之类的

**Comment by callofdutyops** [comment]
example文件导出也有这些信息

**Comment by callofdutyops** [comment]
已确定是logo.pdf的元数据问题，我替换了这个为截图，暂时解决，但是由于不是矢量图，放大会模糊，希望有更优解决方案。

**Comment by x-magus** [comment]
我用acrobat导出看不到这些东西。你用的什么`邮箱附件预览工具`？

**Comment by callofdutyops** [comment]
我是用的也是acrobat，对example.pdf执行文件-导出-txt文件操作
QQ邮箱上传附件，点击文件预览PDF也会显示

**Comment by x-magus** [comment]
我重新处理了一下图片，现在应该没问题了。

**Comment by callofdutyops** [comment]
确实已经没有问题了
