### ISSUE TITLE
偶数页摘要空页有页眉和页码

### ISSUE THREAD

**Issue by callofdutyops** [x-magus/ThesisUESTC#68]
如图所示，但这一页文印中心的人说应该是空白的，并且不算页数。也就是对于这种情况，此页完全空白，紧接着的英文摘要从II开始编号。
![github](https://user-images.githubusercontent.com/5207896/56480744-062b3600-64ee-11e9-8da4-c596fd86a556.png)

**Comment by zhangji2015zhj** [comment]
检查中文摘要内有没有强制换页，另外确保模板是最新状态！

**Comment by callofdutyops** [comment]
@zhangji2015zhj 确定模板是最新的，中文摘要没有强制换页。我用的是`main_multifile.tex`写的，不知道这个有没有关系

**Comment by callofdutyops** [comment]
@zhangji2015zhj 我发现了，多了`隐形`（不知如何描述）空格，我删了几个字就好了

**Comment by callofdutyops** [comment]
补充信息：
似乎我遇到的是临界状况（摘要删除了几个字，少了一行就好了）。
虽然算是解决了，但应该也算模板的bug，因此先不关闭issue......

**Comment by x-magus** [comment]
如果是多文件的文档插入内容用\input而不是\include，后者貌似会加入额外的空白内容。

**Comment by callofdutyops** [comment]
@x-magus 用的是`\input`，如图所示
![github](https://user-images.githubusercontent.com/5207896/57059081-2aed8d80-6ce6-11e9-9684-2443e003ba61.png)
去掉`测试测试测试测试测试测试`减少一行后，就正常了。

**Comment by x-magus** [comment]
最近更新的模版已经解决此问题（ 580f90b86e0f17ccad2620c964cf72db1d9eead3 ），感谢各位的帮助和支持。
