### ISSUE TITLE
多页参考文献时，底部有留白

### ISSUE THREAD

**Issue by zhangji2015zhj** [x-magus/ThesisUESTC#69]
![image](https://user-images.githubusercontent.com/14149012/56953847-fbb51000-6b6f-11e9-98b2-92e9717bba29.png)

在参考文献模块中，本页有两行空间，下一条参考文献条目有三行，此时会形成留白。
有没有可能是某一条目文献的前两行显示在上一页，后一行显示在下一页？

**Comment by x-magus** [comment]
学校要求是一个参考文献不能跨行，这样很容易有大量空白。模版只是按照格式规范而已。

**Comment by zhangji2015zhj** [comment]
好的谢谢
