### ISSUE TITLE
<argument> \str_if_eq:eeTF   {\exp_not:o {\use_none:n [\rmfamily ,\sffamily }}... l.16  [\rmfamily,\sffamily]

### ISSUE THREAD

**Issue by jpainam** [x-magus/ThesisUESTC#72]
Hi, i'm facing this error when running this latex on Windows 10. 
```bash
<argument> \str_if_eq:eeTF
                           {\exp_not:o {\use_none:n [\rmfamily ,\sffamily }}...
l.16  [\rmfamily,\sffamily]
```
Any help will be appreciated

**Comment by muzimuzhi** [comment]
The error message you provided is not complete. A LaTeX error message begins with a `!`, and ends with a `?` (if compiled without `-interactive=nonstopmode`, for example:
```latex
! Undefined control sequence.
\pgf@setup@shading@model ...delgrayfalse \XC@sdef 
                                                  \pgf@mod@test {\XC@tgt@mod...

\pgfdeclareverticalshading ...setup@shading@model 
                                                  \pgfutil@ifnextchar [\pgf@...
l.577 \pgfdeclareverticalshading
                                [tikz@axis@top,tikz@axis@middle,tikz@axis@bo...

? ^D
```

A guess: your local installation of package `l3kernel` is outdated, since the control command `\str_if_eq:eeTF` is updated on 2018-06-18. (from `texdoc interface3`, sec. VII.4) Try update that package using the package manager in your LaTeX distribution.

**Comment by jpainam** [comment]
Thank you, you are right; `!Undefined control sequence` was missing in my LaTeX error. Updating `l3kernet` fixed the problem. Now having a problem with  CJK.  xecjk and cjk are installed
```bash
! Undefined control sequence.
\xeCJK/family/rm ...e:n \fontspec_gset_family:Nnn
                                                  \g__xeCJK_fontspec_family_...
l.47   \setCJKmainfont[AutoFakeBold=true]{SimSun}
```

**Comment by muzimuzhi** [comment]
@jpainam 
If the followed problem is not solved yet, and you think it has something to do with this repo (latex template), you can open a new issue.

**Comment by x-magus** [comment]
@jpainam What's the distribution of your LaTeX, and what's the operating system you're working on? The TeXLive is recommended on both Windows and Linux. The once large and complete installation is also suggested.

**Comment by jpainam** [comment]
@x-magus @muzimuzhi . i just forgot to mention, a complete update of my tex distribution (i'm using miktex on windows 10) actually solved the problem. thank you once again
