### ISSUE TITLE
! Undefined control sequence. l.48   \newCJKfontfamily   {\heiti}{SimHei}

### ISSUE THREAD

**Issue by ghghgh0001** [x-magus/ThesisUESTC#73]
我现在用的是WinEdt10.2，然后使用的是XeLaTeX进行编译，我按照readme里的要求装了perl，然后我的windows/fonts里是有simhei和simsun文件的，可是这里会报错，请问这是为什么会出现这样的问题啊。
! Undefined control sequence.
l.48   \newCJKfontfamily
                        {\heiti}{SimHei}
? 
报的错误是这样的。

**Comment by muzimuzhi** [comment]
报错信息是说，控制序列 `\newCJKfontfamily` 未定义，和字体文件无关。

 - `\newCJKfontfamily` 是[五年前的提交](https://github.com/CTeX-org/ctex-kit/commit/116d2da13bd038769cba3bdfa366620aeed580e6)中新定义的命令，建议检查 `ctex` 宏包的版本。
 - 如果你是 CTeX 套装，根据模板的 README，
    > 使用模板需要系统安装任意一种TeX环境，如TeXLive、MacTeX和MiKTeX（都自动带有XeLaTeX引擎，但是不推荐CTeX）
 - WinEdt 是编辑器，编辑器版本与宏包版本之间没有关系。

**Comment by ghghgh0001** [comment]
嗯，我之前用的CTEX，换成TEXlive之后就没有这个问题了，太感谢了。
