### ISSUE TITLE
建议在 git commit message 中记录具体的修改内容

### ISSUE THREAD

**Issue by muzimuzhi** [x-magus/ThesisUESTC#75]
目前，这个 git 项目的所有 commit message 都是 "update"，这会给后续维护带来不便。

例如，#40 中的问题涉及「模板重定义了 `algorithm` 环境」，可以找到对应的提交 https://github.com/x-magus/ThesisUESTC/commit/3ec48d904d28c504b4556492b2d526d7908ac15d 。但因为缺乏源码注释，简单的 commit message "update" 也无法提供更多信息，我们很难了解到 2 年多前重定义 `algorithm` 环境的原因和目的。

强烈建议，在 commit message 中记录主要的修改内容，github 也提供了「把提交和讨论（issue）关联起来」的功能。

有关 commit message 的编写方式，有不少风格指南，例如[这则](http://www.ruanyifeng.com/blog/2016/01/commit_message_change_log.html)；考虑到这个项目规模稳定、维护人员简单，可以不使用特定的风格，但记录有意义的信息、描述提交所做修改，仍然有必要，也对提高可维护性有帮助。

**Comment by x-magus** [comment]
我注意一下。。

**Comment by x-magus** [comment]
重定义了algorithm环境是为了caption的格式与图表一致，因为算法包覆写了默认的caption机制。由于有反映不一致的caption也能通过审查就在https://github.com/x-magus/ThesisUESTC/commit/7879a144bd0ad3096a5b0e0ea7fbc123642e0275 取消了。
