### ISSUE TITLE
目前模板为何需要重定义 algorithm 环境？

### ISSUE THREAD

**Issue by muzimuzhi** [x-magus/ThesisUESTC#76]
重定义 `algorithm` 环境带来了「无法使用 `algorithm2e` 宏包的丰富配置项」的问题，见 #40 。基于这个 issue 的 push request #41（已关闭）提供了一种兼容修改，但我觉得这个修改把事情变复杂了，提高了模板的维护难度。

当前 issue 的目的，是想
1. 了解重定义 `algorithm` （该修改由提交 https://github.com/x-magus/ThesisUESTC/commit/3ec48d904d28c504b4556492b2d526d7908ac15d 加入）的意义
2. 根据意义，尝试提供无需重定义环境、且 `algorithm2e` 的配置命令可正常使用的方案。

从之前的交流中，我了解和猜测到，重定义是为了提高样式的一致性，包括
1. 让 `algorithm` 环境内标题使用悬挂缩进的风格，根据交流 https://github.com/x-magus/ThesisUESTC/issues/40#issuecomment-463200481
1. 使算法的标号与其他浮动体环境一致，根据交流 https://github.com/x-magus/ThesisUESTC/issues/40#issuecomment-463078905

**Comment by muzimuzhi** [comment]
以下例子，配合提交 https://github.com/muzimuzhi/ThesisUESTC/commit/3d6ce71460d8c51e1bb8f504f2820de0599854fe 更改后的 `cls` 文件使用（这个提交只做了一件事，把模板中与 algorithm 环境有关的设置注释掉），能在满足上述我猜测的（重定义的）两个目的的同时，兼容 `algorithm2e` 的正常配置。

一些代码说明
 - `algorithm2e` 宏包定义的 `algorithm` 环境，其使用的计数器是 `algocf`，而不是习惯上使用的与环境同名的 `algorithm`。所以我们尽可能使用宏包提供的命令进行配置，只在修改计数器输出样式时，直接重定义 `\thealgocf`。
 - `\algocf@captionlayout@hang` 接受的参数，共包含五个 token，其中前两个用于生成 "算法 2-1"，后两个用于生成标题内容，第三个对应两者之间的分隔符。代码中使用 `\hangindent` 设置标题的首行悬挂缩进，且缩进距离为 "算法 2-1<分隔符>" 的宽度，这样就达到了悬挂的效果。

```latex
%% user-specified algo settings, passed as package options
\PassOptionsToPackage{algochapter, ruled, linesnumbered}{algorithm2e}
\documentclass[master]{thesis-uestc}

%% config counter style
\SetAlgorithmName{算法}{算法}{算法列表}
\renewcommand\thealgocf{\arabic{chapter}-\arabic{algocf}}

\makeatletter
%% config caption style as "hang"
\SetAlgoCaptionLayout{algocf@captionlayout@hang}

\newcommand\algocf@captionlayout@hang[1]{%
  \algocf@captionlayout@hang@i#1
}

\newsavebox\algo@caption@header@box

\newcommand\algocf@captionlayout@hang@i[3]{%
  \savebox\algo@caption@header@box{#1#2#3}%
  \hangindent=\wd\algo@caption@header@box
  \noindent\usebox\algo@caption@header@box%
}
\makeatother

%% some user-specified algo settings
\SetAlCapFnt{\small}
\SetAlCapNameFnt{\small}
\SetAlFnt{\small\linespread{1}\selectfont}

\begin{document}
\listofalgocfs
\chapter{title}
\begin{algorithm}[H]
 \KwData{this text}
 \KwResult{how to write algorithm with \LaTeX2e }
 initialization\;
 \While{not at end of this document}{
  read current\;
  \eIf{understand}{
   go to next section\;
   current section becomes this one\;
   }{
   go back to the beginning of current section\;
  }
 }
 \caption{How to wirte an algorithm. How to wirte an algorithm. How to wirte an algorithm. How to wirte an algorithm. How to wirte an algorithm.}\label{algo:x}
\end{algorithm}

测试引用：见\autoref{algo:y}。

\chapter{title}
\begin{algorithm}[H]
 \KwData{this text}
 \KwResult{how to write algorithm with \LaTeX2e }
 initialization\;
 \While{not at end of this document}{
  read current\;
 }
 \caption{How to wirte an algorithm.}\label{algo:y}
\end{algorithm}
\end{document}
```

输出效果
![image](https://user-images.githubusercontent.com/6376638/63642151-b0f66f80-c6ed-11e9-9b5c-75ccd94a35c4.png)
![image](https://user-images.githubusercontent.com/6376638/63642154-b653ba00-c6ed-11e9-9b19-53f18571dca3.png)
![image](https://user-images.githubusercontent.com/6376638/63642157-bc499b00-c6ed-11e9-808e-6143a5c88b5f.png)

**Comment by x-magus** [comment]
谢谢诸位的贡献，如果不一致的caption格式可以通过格式审查的话就可以考虑取消重定义的algorithm环境。
