### ISSUE TITLE
bibtex in WindEdt pulls all the biobliography from the bib file

### ISSUE THREAD

**Issue by jpainam** [x-magus/ThesisUESTC#77]
Hi,
Thank you for sharing this latex. 
When I generate the bbl file from the bib file; the bst and latex class pull all the bibliography; even those that are not cited.
I usually keep all my bibliography in one place and use it in all my papers. And it works fine for other latex formats.
Any help on how I can generate only the cited bibliography ?

**Comment by x-magus** [comment]
You should not use `nocite` with `\thesisloadbibliography` command.
