### ISSUE TITLE
如何避免使用伪加粗

### ISSUE THREAD

**Issue by dnsilence** [x-magus/ThesisUESTC#79]
使用模板编译出来的公式加粗指令是伪加粗，字体很不好看
![7C B%F$TSM(T{U5SJZ@}D I](https://user-images.githubusercontent.com/24773583/68085899-da1b4500-fe80-11e9-897f-9962e6e559c8.png)
调用bm宏包并注释.cls伪加粗指令后后因为设定公式环境字体为times new roman，导致加粗指令失效。请问如何避免使用伪加粗

**Comment by x-magus** [comment]
加上
```
\makeatletter
\DeclareMathAlphabet{\mathbf}{\eu@enc}{\eu@mathrm}{bx}{it}
\makeatother
```
使用`\mathbf`应该没问题。

**Comment by x-magus** [comment]
我补过字体设置了，用新一点的模版吧。

**Comment by muzimuzhi** [comment]
> 加上
> 
> ```
> \makeatletter
> \DeclareMathAlphabet{\mathbf}{\eu@enc}{\eu@mathrm}{bx}{it}
> \makeatother
> ```
> 
> 使用`\mathbf`应该没问题。

默认的 `\mathbf` 是 bold roman，你这样修改后，bold roman 就输出不了了 。建议为 bold italic 分配新的命令。
可以参考 https://github.com/wspr/mathspec/issues/2

**Comment by x-magus** [comment]
不知道什么原因其实LaTeX数学字体传统上不提供原生的斜体加粗的符号，像表示向量都是用的\mathbf的加粗。但是就写论文的情况从来都不愿意用这种加粗方式。提供斜体的加粗以后跟原来的粗体区分度又不够，一般不选择两种字体代表不同的数学含义。其实只需要斜体加粗就够了。

**Comment by dnsilence** [comment]
我觉得正体粗体和斜体粗体的需求还是很多的，因为首先都是表示向量，而正体一般用在多字母变量上。我查到的说是times new roman不是数学字体，所以需要额外配置

**Comment by x-magus** [comment]
但是工程上用的多字母变量一般不加粗，这样的话最多\mathrm就够了。我觉得还是按latex的习惯只提供一种加粗方案。Times New Roman字体本身包含的数学符号是非常全的，但是latex并没有支持的很好。

**Comment by muzimuzhi** [comment]
你在 https://github.com/x-magus/ThesisUESTC/issues/79#issuecomment-549197194 里建议的重定义 `\mathbf` 的方式，有多个问题
 - 改变了 latex 的默认行为，即把（数学模式下） `\mathbf` 输出 bold roman 修改为了输出 bold itatlic。这会增加用户的学习和记忆成本。
 - 给使用 bold roman 带来了麻烦。
   - latex2e 确实只提供了一种加粗方案，即 `\mathbf` 输出 bold roman，但用户通过简单配置，例如加载 `bm` 宏包，仍然可以使用 bold italic。
   - 但经你重定义后，用户使用 bold italic 变方便了了，但使用 bold roman 会十分麻烦。

于是，我的建议是：
 - 不要改变 latex 的默认行为，仍然让 `\mathbf` 输出 bold roman
 - 为 bold italic 分配一个新命令，是否使用 \mathbfit` 可讨论

最后，这是一个不限定使用学科的论文模板，无法假设用户「只需要使用哪些符号」。

**Comment by dnsilence** [comment]
哈哈哈楼主制作并维护这个模板这么多年很不容易，都在慢慢变好。把cls文件里面配字体的\mathbf换成\mathbfit就行，然后尊重用户习惯还能继续使用\bm多好😁

**Comment by dnsilence** [comment]
哈哈哈楼主制作并维护这个模板这么多年很不容易，都在慢慢变好。把cls文件里面配字体的\mathbf换成\mathbfit就行，然后尊重用户习惯还能继续使用\bm多好😁

**Comment by x-magus** [comment]
这个有点见仁见智了，很多优秀的工具设计的时候都会考虑约束使用者的行为，避免容易滥用的功能。这一点歌德有一句诗挺好的：“在限制中才能显出名手，只有法则给我们自由。”

**Comment by muzimuzhi** [comment]
> 加上
> 
> ```
> \makeatletter
> \DeclareMathAlphabet{\mathbf}{\eu@enc}{\eu@mathrm}{bx}{it}
> \makeatother
> ```
> 
> 使用`\mathbf`应该没问题。

这么定义后，用户如果想使用 bold roman，应该怎么输入呢？

**Comment by zepinglee** [comment]
我也建议不要修改原来的 `\mathbf`，粗斜体可以使用 `\bm` 或者 `\symbf`，前者是 `bm` 宏包的用法，后者是 `unicode-math` 的用法。

> 不知道什么原因LaTeX数学字体传统上不提供原生的斜体加粗的符号。

在 TeX 出现前，数学界已经形成了使用粗正体表示向量和矩阵的习惯。`unicode-math` 的文当中猜测：
>  Presumably, this was due to the relatively scarcity of bold italic fonts in the pre-digital typesetting era.

AMS 的数学家们比较传统，所以沿用了粗正体的用法。而且从某些数学领域（特别是代数）的角度，向量和矩阵并没有本质的特殊之处，所以也有的甚至不用粗体。

> 但是就写论文的情况，因为不太好看从来都不愿意用这种加粗方式。

这个要区分领域。我所了解的有：PDE 的经典教科书 Evans 使用的是粗正体；机器学习领域的文章基本都是用粗正体。其他的领域我不太了解或者记不清了。

> 其实只需要斜体加粗就够了。

GB/T 3102.11—1993 和 ISO 80000-2:2019 中 grad 和 rot 两个 operator 需要用粗正体，另外还有使用粗正体表示数域 R, C, Z。

> 很多优秀的工具设计的时候都会考虑约束使用者的行为，避免容易滥用的功能。

我觉得符号习惯应该符合领域内的主流用法，而且粗正体并不能算是滥用。

**Comment by x-magus** [comment]
学校的规范跟国标和ISO本来就不一样，伪粗体的数学符号当然没有真正的粗体好看，所以没必要使用。

**Comment by zepinglee** [comment]
> 学校的规范跟国标和ISO本来就不一样

我的意思是，粗正体有合理的使用场景，修改 `\mathbf` 导致这些情况下无法正常使用。

> 很多优秀的工具设计的时候都会考虑约束使用者的行为，避免容易滥用的功能。

约束用户应该仅在无副作用的情况下进行。
