### ISSUE TITLE
几个行间距设置问题

### ISSUE THREAD

**Issue by dnsilence** [x-magus/ThesisUESTC#80]
这里有几个行距设置疑问：
1. 文本行距学校要求20pt，cls中采用
```
\linespread{1.391}
```
由于20pt/12pt/1.2=1.389，这里设置值是不是有问题？而且为啥不直接用
```
\setlength\baselineskip{20pt} 
```
2. 设置caption格式的时候，使用了
```
\captionsetup{width=\textwidth - 42pt}
```
这个42pt是如何计算的？学校模板要求左右缩进两个字符（12pt*4=48pt），再补上悬挂缩进的编号（6pt）吗？但是编号不是时长（1-11）时短（1-1）吗？为啥不用caption margin设置
```
\captionsetup{margin=24pt} 
```
这样不论保证编号变化，标题左右缩进是一样的吧。
3. 还是一个关于caption问题想请教，模板要求图片标题段前6pt，段后12pt，表格相反。然后cls文件是这么定义的
```
\captionsetup[figure]{aboveskip=6pt, belowskip=0pt} 
\captionsetup[table]{belowskip=6pt}
```
这里的设置为什么不是对应值呢？

**Comment by x-magus** [comment]
图表标题的间距还要考虑\intextsep的数值。另外caption的间距是按caption的10.5磅的字体算的。还有\setlength\baselineskip{20pt} 的设置我试了一下没什么效果。
