### ISSUE TITLE
SimHei font erroe

### ISSUE THREAD

**Issue by SalahuddinSwati** [x-magus/ThesisUESTC#82]
Hello, when I compile the main.tex file I got an error "Package fontspec Error: The font "SimHei" cannot be found. \setallmainfonts". How to resolve this issue. Thank you...

**Comment by x-magus** [comment]
What's the platform you're working on? Did you compile your document with latexmk?

**Comment by SalahuddinSwati** [comment]
Windows 10, Miktex, Texstudio. Yes, I compiled it with latexmk using the command line and also in Texstudio. Only I faced this font issue.

**Comment by x-magus** [comment]
The English version Windows 10 might not contain the SimHei font, which is for Chinese characters. You can check if the font is installed, or download and install the font by yourself. The [Overleaf Template](https://www.overleaf.com/latex/templates/uestc-thesis-template/nwpkhtrtjhrg) is distributed with all necessary font files.

**Comment by muzimuzhi** [comment]
@SalahuddinSwati 
SimHei is one of four [Chinese (Simplified) Supplemental Fonts](https://docs.microsoft.com/en-us/typography/fonts/windows_10_font_list#chinese-simplified-supplemental-fonts) of Win 10. In case this font is not pre-installed on your computer, you can
> Select the Start button, and then select Settings > Apps > Apps & features > Manage optional features.
> ref: [Win 10 Font List | Introduction](https://docs.microsoft.com/en-us/typography/fonts/windows_10_font_list#introduction)

to add font packages manually.

**Comment by SalahuddinSwati** [comment]
Thanks...
