### ISSUE TITLE
建议开个新分支

### ISSUE THREAD

**Issue by huqianshan** [x-magus/ThesisUESTC#83]
#### 同时也可以增加此`pdf`作为上手教程
![file](https://user-images.githubusercontent.com/23468665/69875969-5d517e80-12f9-11ea-9cf7-5f8cc3e83b5a.jpg)
![file2](https://user-images.githubusercontent.com/23468665/69875970-5dea1500-12f9-11ea-9b34-18732a8148e8.jpg)

http://www.lib.uestc.edu.cn/activity?id=100

**Comment by x-magus** [comment]
最新的格式说明谁有吗？还有这些链接都是图片，有没有ppt过来传一份啊？

**Comment by x-magus** [comment]
课件能不能帮我下载一份啊，我没有账号了现在。还有最新的格式说明有吗？

**Comment by huqianshan** [comment]
看来已经是两个不同的分支了 : )  是否打算合并一下呢:)

**Comment by x-magus** [comment]
我看看他们都新加了什么吧，好像主要是封面，还有一个专业博士的学位选项。

**Comment by x-magus** [comment]
现在这个分支的所有功能都已经在本项目实现（ f05462354134e5e34f322a7f5f8b70ee88a9b220 ）。
