### ISSUE TITLE
模板公式问题

### ISSUE THREAD

**Issue by dnsilence** [x-magus/ThesisUESTC#84]
模板中公式出现粘连，以下代码
```
\begin{equation}
{\rm{SNR}} = \dfrac{{\int_{ - \infty }^{ + \infty } {{{\left| {S\left( f \right)X\left( f \right)H\left( f \right)} \right|}^2}{\rm{d}}f} }}{{\int_{ - \infty }^{ + \infty } {\left( {{P_{\rm{n}}}\left( f \right)} \right){{\left| {H\left( f \right)} \right|}^2}{\rm{d}}f} }}
\label{eq_snr}
\end{equation}
```
使用article类，则是以下正常的显示效果
![批注 2019-12-04 164132](https://user-images.githubusercontent.com/24773583/70127063-41612a80-16b5-11ea-8873-1a689d70427d.jpg)
但是使用模板类，显示括号中的变量和括号发生粘连。
![批注 2019-12-04 164137](https://user-images.githubusercontent.com/24773583/70127072-44f4b180-16b5-11ea-8647-1c98f70423e9.jpg)

**Comment by x-magus** [comment]
这是Time New Roman字体设计的问题，使用article类不设置字体的话是Computer Modern。另外f不要当成函数参数，除非这是一个Operator。

**Comment by dnsilence** [comment]
查了一下午资料，这里有几个问题和建议想和作者分享：
* cls文件中使用了mathspec宏包，并使用 **\setallmainfonts{Times New Roman}** 设置数学字体，问题就出在**times new roman其实是不适合用作数学字体** 的。
  - 有一个折中的方案是采用mathspec说明文档sec 6中给出的解决办法。
![批注 2019-12-04 230413](https://user-images.githubusercontent.com/24773583/70153769-720f8700-16ea-11ea-8fa5-228fc12eb85a.jpg)
但是这里也说明了**The reason is that the font has metrics that are suitable for use in text, but not for mathematics.**
* 鉴于latex自带computer modern字体不太符合习惯。同时模板中使用的mathspec宏包较旧，而且bug较多，论坛吐槽贴常见。推荐解决方案是使用fontspec宏包，同时使用newtxtext，newtxmath等现代化的times系字体。参考lshort-zh-cn sec5.1.5 tab5.4
![批注 2019-12-04 230413](https://user-images.githubusercontent.com/24773583/70154305-46d96780-16eb-11ea-8d42-b1617bcba416.jpg)
* 个人认为模板作者可以规范模板使用者的使用方式，但不应该限定模板使用者的使用内容。况且f还是一个常见的物理变量（frequency domain）

**Comment by x-magus** [comment]
这个主要是学校要求英语字体是Times New Roman，现有的字体设置基本只有f会出问题。如果使用其他字体会风格上会显得很不一致。如果有粘连的话也可以用波浪符号调整距离$S(~f~)X(~f~)H(~f~)$。

**Comment by muzimuzhi** [comment]
PS: `mathspec` 提供的增加公式中单个字母间距的方式，是 `$"f(x)$`。参考 `texdoc mathspec`，sec. 6.

**Comment by dnsilence** [comment]
> PS: `mathspec` 提供的增加公式中单个字母间距的方式，是 `$"f(x)$`。参考 `texdoc mathspec`，sec. 6.

这个方法在模板里不起作用，估计是哪里配置冲突了，只能采用~。
