### ISSUE TITLE
请问OverLeaf上的论文模板是最新的吗？

### ISSUE THREAD

**Issue by IrvingBei** [x-magus/ThesisUESTC#85]
学长好，我是用的overleaf，在上面也找到了这个[latex模板](https://www.overleaf.com/latex/templates/uestc-thesis-template/nwpkhtrtjhrg)，可以编译成功，所以问问那个是最新版本吗？是的话我就直接用那个了。谢谢哈

**Comment by x-magus** [comment]
现在是最新的。想要使用最新的模版只要更新相应的cls文件和bst文件就可以了。

**Comment by IrvingBei** [comment]
好的，谢谢学长，我之前对比了下，好像是不一样的，后面就直接替换的
