### ISSUE TITLE
建议：使用xurl宏包替换url宏包

### ISSUE THREAD

**Issue by dnsilence** [x-magus/ThesisUESTC#87]
引用online时，由于“-”在url中属于有效字符，导致过长的url不会生成断词，从而产生排版警告
举例：
在使用url宏包情况下，若引用下列条目
```latex
@digital{the2014nasa,
  author = {The Engineer},
  title = {NASA Funds Lockheed for SR-72 Hypersonic Spy drone},
  type = {EB/OL},
  date = {2014},
  url = {https://wonderfulengineering.com/nasa-funds-lockheed-for-sr-72-hypersonic-spy-drone/},
}
```
排版效果如下
![批注 2019-12-31 155938](https://user-images.githubusercontent.com/24773583/71614438-96c22600-2be6-11ea-865f-ba74a0c578a4.jpg)
可以看出排版过松，并伴随**underfull \hbox**警告。
但是如果修改使用xurl宏包，即可完美解决这个问题，排版效果如下
![批注 2019-12-31 160401](https://user-images.githubusercontent.com/24773583/71614531-2ff13c80-2be7-11ea-9b93-dba989d82cc7.jpg)
正常排版且无警告。xurl宏包可以在单词中间断行，不会填加额外断词符号，可以正常使用超链接。与url完美兼容(配置一致)，使用方便，直接替换cls文件中的url即可。

**Comment by x-magus** [comment]
在Commit 25371b6e21707a4c208b9531279ac46ea214db3f 已经采用了以上建议，感谢同学的建议。
