### ISSUE TITLE
the sections/subsections were not bold as required by the graduate school

### ISSUE THREAD

**Issue by jpainam** [x-magus/ThesisUESTC#89]
Hi, A copy of this thesis was just rejected because the sections and the subsections were not bold. Is it possible to make it available? Likewise, the Chapter in the table of content needs to be bold. 
Thank you.

**Comment by jpainam** [comment]
i managed to solve it editing the class file and adding `\bfseries`  to the section cmmand.

**Comment by x-magus** [comment]
As far as I know, the section titles of English mode is properly configured to be bold. Do you have screenshot of this problem, so I can make certain of the bug?

**Comment by jpainam** [comment]
The ThesisUESTC folder I had was downloaded in June 2019. I just updated the template and it's working fine. Thank you.
