### ISSUE TITLE
references after 100 are slightly misaligned

### ISSUE THREAD

**Issue by jpainam** [x-magus/ThesisUESTC#90]
Hi; here is the picture. Any idea how to solve this misalignement?
The following image is wrong.
![image](https://user-images.githubusercontent.com/1701705/71767266-64e1f400-2f45-11ea-8f52-f66f0f389465.png)

it should be
![image](https://user-images.githubusercontent.com/1701705/71767283-b7231500-2f45-11ea-8c3c-77dccc612466.png)

Thank you

**Comment by muzimuzhi** [comment]
Add following lines to your preamble (after `\documentclass` and before `\begin{document}`):
```tex
\makeatletter
\renewcommand{\@biblabel}[1]{[#1]}
\renewcommand{\bstlabelmark}{999}
\makeatother
```
![image](https://user-images.githubusercontent.com/6376638/71767598-b770df80-2f48-11ea-9f62-41cb57322794.png)

**Comment by jpainam** [comment]
thank you.
 I have this error
```
main_multifile.tex:72: LaTeX Error: Command \bstlabelmark undefined.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.72 \renewcommand{\bstlabelmark}
                                 {999}
? 
```

**Comment by jpainam** [comment]
I just noticed that i don't have the latest version. i'll download and  try it now.

**Comment by jpainam** [comment]
Thank you, it worked. but calling `\input{misc/appendix}` import `apendix A` but he page title shows `Chapter 1`
![image](https://user-images.githubusercontent.com/1701705/71768947-1db02f00-2f56-11ea-9948-889b00070348.png)

Maybe i'll opend another issue
