### ISSUE TITLE
\thesisloadaccomplish{publications} not working

### ISSUE THREAD

**Issue by jpainam** [x-magus/ThesisUESTC#92]
Hi, this command does not add the accomplisments/publications. The file publications.bib contains my publications. Kindly confirm. Even in the example.pdf

thanks

**Comment by x-magus** [comment]
In the example, the accomplishments are listed after the appendices. To correctly include the publications, you need to call specifically `bibtex accomplish.aux`. The `latexmk` compilation method is also recommended for easy use.

**Comment by jpainam** [comment]
It's working; please add this detail in the readme file . I'm using xelatex
```
To generate the publications/accomplishment, run bibtex accomplish.aux after la latex/xelatex
```
