### ISSUE TITLE
段落中插入图片环境，前后文字中间会多出空白

### ISSUE THREAD

**Issue by dnsilence** [x-magus/ThesisUESTC#95]
ctex模板测试无该问题，mwe如下
```latex
\documentclass{article}
\usepackage{ctex}
\usepackage{graphicx}
\begin{document}
你好。如图所示。
\begin{figure}[htbp]
  \centering
  \includegraphics[width=0.5\linewidth]{example-image}
  \caption{image}
\end{figure}
其中，再见。
\end{document} 
```
编译结果如图，可以看到 **所示。** 和 **其中** 之间的空白是与前面 **你好。** 和 **如图**之间的空白间距是一致的。
![image](https://user-images.githubusercontent.com/24773583/73336379-a481ce80-42ac-11ea-8acb-4050d190e7e3.png)
但是模板中如果这么写的话，效果如下
![image](https://user-images.githubusercontent.com/24773583/73336560-1b1ecc00-42ad-11ea-8ff9-a5ab1b5a4da1.png)
可以看到，**所示。** 和 **其中** 之间的空白是要大于正常间距的。

**Comment by muzimuzhi** [comment]
模板当前实现中，在 patch 浮动体环境时，插入了额外的空格（由换行符生成）
https://github.com/x-magus/ThesisUESTC/blob/e592a6fef85b3f409744ec5995937c7c53804ff8/thesis-uestc.cls#L155-L161

用 `%` 注释掉即可
```tex
\AtBeginEnvironment{figure}{%
  \def\@floatboxreset{\centering}%
}

\AtBeginEnvironment{table}{%
  \def\@floatboxreset{\centering}%
}
```

**Comment by muzimuzhi** [comment]
补充：由提交 https://github.com/x-magus/ThesisUESTC/commit/8796a5d3d6719351398174afedc3d3cc08d90297 修复
