### ISSUE TITLE
你好，mac上的subfloat报错

### ISSUE THREAD

**Issue by perryupan** [x-magus/ThesisUESTC#96]
报错说：undefined control sequence. \subfloat 这样。这个问题出现在了所有使用subfloat的地方。版本为当前github 的 master 源代码。

请问这个怎么解决呢？

**Comment by dnsilence** [comment]
> 报错说：undefined control sequence. \subfloat 这样。这个问题出现在了所有使用subfloat的地方。版本为当前github 的 master 源代码。
> 
> 请问这个怎么解决呢？

没有所需宏包，应该是引擎未成功安装，参考https://github.com/OsbertWang/install-latex/releases/download/v2020.1.1/Install-LaTeX.pdf 重新安装引擎

**Comment by muzimuzhi** [comment]
`\subfloat` 命令由 `subcaption` 宏包 v1.3 开始提供，建议检查本地的 `subcaption` 宏包版本。

**Comment by perryupan** [comment]
谢谢了哈，确实是这个原因

muzimuzhi <notifications@github.com> 于2020年1月31日周五 下午9:48写道：

**Comment by perryupan** [comment]
> `\subfloat` 命令由 `subcaption` 宏包 v1.3 开始提供，建议检查本地的 `subcaption` 宏包版本。

谢谢了哈，确实是这个原因

**Comment by perryupan** [comment]
> > 报错说：undefined control sequence. \subfloat 这样。这个问题出现在了所有使用subfloat的地方。版本为当前github 的 master 源代码。
> > 请问这个怎么解决呢？
> 
> 没有所需宏包，应该是引擎未成功安装，参考https://github.com/OsbertWang/install-latex/releases/download/v2020.1.1/Install-LaTeX.pdf 重新安装引擎

谢谢，应该是包没有更新的原因

**Comment by muzimuzhi** [comment]
今天遇到有相同问题的用户，可以在文档类层面做一点提醒，方便用户知道出错原因：

1. 在载入宏包时，指定最低版本
```tex
\RequirePackage{subcaption}[2019/09/10]
```
当用户本地版本低于最低版本时，会报类似下方的警告
```
LaTeX Warning: You have requested, on input line 2, version
               `2020/08/10' of package subcaption,
               but only version
               `2020/01/22 v1.3d Sub-captions (AR)'
               is available.

```

2. 如果觉得警告的强度不够，还可以手动输出报错，例如
```tex
\@ifpackagelater{subcaption}{2019/09/10}{}{%
  \ClassError{thesis-uestc}{请升级 subcaption 宏包到 v1.3 及以上版本}{}%
}
```

参考资料：https://github.com/ustctug/ustcthesis/wiki/LaTeX-模板开发最佳实践#一般 ，第 11 点

**Comment by x-magus** [comment]
下次补丁加上吧。
