### ISSUE TITLE
反馈几个小bug

### ISSUE THREAD

**Issue by dnsilence** [x-magus/ThesisUESTC#98]
* 最近作者去掉了subcaption宏包并改为subfig包，但是在三张图并排显示的时候标题会对不上正确位置，而subcaption宏包不会有这个问题。相对而言subcaption宏包最近更新日期（2020.01.22）也要比subfig（2018.11.28）近，不知道出于什么考虑替换。
* 最近一次latex2e更新中，把粗体字族由bx改为了b（参考下面链接第156行）
[https://github.com/latex3/latex2e/blob/master/base/changes.txt#L152-L158](url)
因此，原来cls文件中的
```latex
\DeclareMathAlphabet{\mathbf}{\eu@enc}{\eu@mathrm}{bx}{it}
```
会报错

**Comment by muzimuzhi** [comment]
> 不知道出于什么考虑替换

猜测是因为类似 #96 的问题。

> 最近一次latex2e更新中，把粗体字族由bx改为了b

引用的信息是我在 qq 群给出的。可考虑把 `bx` 改为 `\bfdefault` 进行修复。

**Comment by x-magus** [comment]
最新的texlive2019-20190410所带的subcaptiion包还比较老，在windows上编译可能会提示\subfloat未定义。另外`\DeclareMathAlphabet{\mathbf}{\eu@enc}{\eu@mathrm}{bx}{it}`是覆写的mathspec包的命令，不知道你是在什么条件下编译报错的？

**Comment by dnsilence** [comment]
> 最新的texlive2019-20190410所带的subcaptiion包还比较老，在windows上编译可能会提示\subfloat未定义。另外`\DeclareMathAlphabet{\mathbf}{\eu@enc}{\eu@mathrm}{bx}{it}`是覆写的mathspec包的命令，不知道你是在什么条件下编译报错的？

命令行使用tlmgr update --self --all，目前的tlmgr版本号：r53576，tlshell版本号：r53801。学长说的subcaption包比较老，提示\subfloat未定义，使用命令更新以后问题不存在。同时也是因为更新最近版本，其字体族也出了问题，可以考虑在readme文件中给出texlive安装与更新教程：https://github.com/OsbertWang/install-latex

**Comment by x-magus** [comment]
还要更新刚下载的TeXlive对使用者来说有点麻烦，这个问题最新的commit( ccc7bd9f59e8b8b84767f62a551b9bd7ee58bb07 )已经解决。倒是数学字体具体出了什么问题？有没有编译失败的提示或者有问题的输出？

**Comment by dnsilence** [comment]
有的，就是bx字体族官方包里面替换成了b，导致编译无法识别，报错信息如下
![image](https://user-images.githubusercontent.com/24773583/75086800-1c24df80-5573-11ea-8134-5a976106d86c.png)
这将导致加粗斜体符号被配置为普通正体。
如果不更新最新的宏包（2020.02.02）是没有这个问题的，不过建议使用者还是可以保持一个比较新的状态（更新宏包也就一句命令行的事）。这样大家遇到的问题就可以都统一，否则各个版本都可能有各个版本遗留的问题，比如之前的\subfloat未定义。

**Comment by x-magus** [comment]
在commit 7c24783d333d88865e55a5efab349b296f7b7a91 已经解决了数学粗体失效的问题。因为2019版的TeXlive所带的subcaption宏包比较老旧，等新的TeXlive发布以后再将subfig替换成suncaption。
